Repository bcgov/tno, pull requests merged in 2021-12, with the labels that each got.

#16 Fix make setup
  Makefile
Labels: bug

#18 Fix script
  tools/scripts/gen-keys.sh
Labels: bug

#19 Fix Environment Config
  Makefile
  db/elasticsearch/elasticsearch.yml
  db/elasticsearch/scripts/migration.sh
  db/kafka/docker-compose.yml
  db/kafka/migrations/U1.0.0.sh
  db/kafka/migrations/V1.0.0.sh
  db/kafka/scripts/migration.sh
  db/postgres/docker/scripts/init-user-db.sh
  docker-compose.yml
  libs/java/core/.gitignore
  libs/java/dal/db/.gitignore
  libs/java/dal/db/bin/README.md
  libs/java/dal/elastic/.gitignore
  libs/java/service/.gitignore
  tools/scripts/gen-env-files.sh
  tools/scripts/gen-maven-files.sh
  tools/scripts/nuke.sh
  tools/scripts/variables.sh
Labels: bug, enhancement, devops

#20 Fix postgres config
  db/postgres/docker/scripts/init-user-db.sh
  tools/scripts/gen-env-files.sh
Labels: bug, devops

#21 Fix make build command
  Makefile
Labels: bug, devops

#24 updated scripts
  .gitignore
  tools/scripts/gen-maven-files.sh
  tools/scripts/nuke.sh
  tools/scripts/variables.sh
Labels: enhancement, devops

#23 TNO-141 Add database backup
  .vscode/settings.json
  api/editor/README.md
  api/editor/api-editor/bin/api-editor/src/main/resources/application.yml
  api/editor/api-editor/src/main/resources/application.yml
  app/editor/public/keycloak.json
  app/subscriber/public/keycloak.json
  docs/DEVELOPMENT.md
  libs/java/core/README.md
  libs/java/dal/db/README.md
  libs/java/dal/elastic/README.md
  libs/java/service/README.md
  openshift/templates/backup/README.md
  openshift/templates/backup/build.yaml
  openshift/templates/backup/deploy.yaml
  services/elastic/src/main/resources/application.yml
  services/syndication/src/main/resources/application.yml
  test/README.md
  tools/scripts/gen-maven-files.sh
Labels: documentation, devops

#25 TNO-126 Update make commands
  Makefile
  api/editor/api-editor/src/main/resources/application.yml
  auth/keycloak/README.md
  auth/keycloak/config/realm-export.json
  db/kafka/docker-compose.yml
  docker-compose.yml
  docs/DEVELOPMENT.md
  network/nginx/config/default.conf
Labels: bug, documentation, devops
