Repository bcgov/tno, pull requests merged in 2022-11, with the labels that each got.

#374 TNO-702: Default date
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: enhancement

#375 TNO-710 Enhance connection admin
  app/editor/src/features/admin/connections/ConnectionForm.tsx
  app/editor/src/features/admin/connections/ConnectionList.tsx
  app/editor/src/features/admin/connections/ConnectionListFilter.tsx
  app/editor/src/features/admin/connections/configurations/AWSConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/AzureConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/ConnectionConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/FTPConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/HTTPConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/LocalVolumeConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/NASConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/SFTPConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/SSHConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/index.ts
  app/editor/src/features/admin/connections/constants/connectionTypeOptions.ts
  app/editor/src/features/admin/connections/constants/index.ts
  app/editor/src/hooks/api-editor/constants/ConnectionType.ts
  app/editor/src/hooks/api-editor/constants/ConnectionTypeName.ts
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-api.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-service.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-services.yaml
  openshift/kustomize/tekton/base/tasks/build-component.yaml
  openshift/kustomize/tekton/base/tasks/buildah.yaml
Labels: enhancement

#377 TNO-710 Update Tekton tasks
  .vscode/launch.json
  .vscode/tasks.json
  libs/net/core/Extensions/StringExtensions.cs
  libs/net/dal/Extensions/IngestExtensions.cs
  libs/net/dal/Services/IngestService.cs
  libs/net/services/Helpers/ApiService.cs
  openshift/kustomize/tekton/base/tasks/build-component.yaml
  openshift/kustomize/tekton/base/tasks/buildah.yaml
  openshift/kustomize/tekton/base/tasks/db-migration-conditional.yaml
  openshift/kustomize/tekton/base/tasks/db-migration.yaml
  openshift/kustomize/tekton/base/tasks/git-conditions.yaml
  openshift/kustomize/tekton/base/tasks/git-pull.yaml
  openshift/kustomize/tekton/base/tasks/oc-backup.yaml
  openshift/kustomize/tekton/base/tasks/oc-deploy-with-tag.yaml
  openshift/kustomize/tekton/base/tasks/oc-patch-route.yaml
  openshift/kustomize/tekton/base/tasks/owasp-scanner.yaml
  openshift/kustomize/tekton/base/tasks/pipeline-wait.yaml
  services/net/Makefile
  services/net/filemonitor/FilemonitorAction.cs
  services/net/image/ImageAction.cs
  services/net/image/ImageManager.cs
Labels: bug, devops

#378 Reduce logs
  api/net/Middleware/LogRequestMiddleware.cs
  libs/net/core/Http/HttpRequestClient.cs
  openshift/kustomize/services/capture/base/config-map.yaml
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/services/clip/base/config-map.yaml
  openshift/kustomize/services/clip/base/deploy.yaml
  openshift/kustomize/services/filemonitor/base/config-map.yaml
  openshift/kustomize/services/filemonitor/base/deploy.yaml
  openshift/kustomize/services/image/base/config-map.yaml
  openshift/kustomize/services/image/base/deploy.yaml
  openshift/kustomize/services/syndication/base/config-map.yaml
  openshift/kustomize/services/syndication/base/deploy.yaml
  services/net/capture/appsettings.Development.json
  services/net/capture/appsettings.Staging.json
  services/net/capture/appsettings.json
  services/net/clip/appsettings.Development.json
  services/net/clip/appsettings.Staging.json
  services/net/clip/appsettings.json
  services/net/filemonitor/appsettings.Development.json
  services/net/filemonitor/appsettings.Staging.json
  services/net/filemonitor/appsettings.json
  services/net/image/appsettings.Development.json
  services/net/image/appsettings.Staging.json
  services/net/image/appsettings.json
  services/net/syndication/appsettings.Development.json
  services/net/syndication/appsettings.Staging.json
  services/net/syndication/appsettings.json
Labels: bug

#379 Fix image/file ingest path
  api/net/Dockerfile
  openshift/kustomize/tekton/base/tasks/build-component.yaml
  openshift/kustomize/tekton/base/tasks/buildah.yaml
  services/net/capture/appsettings.json
  services/net/clip/appsettings.json
  services/net/content/appsettings.json
  services/net/filemonitor/FilemonitorAction.cs
  services/net/filemonitor/appsettings.json
  services/net/image/ImageAction.cs
  services/net/image/appsettings.json
  services/net/indexing/appsettings.json
  services/net/nlp/appsettings.json
  services/net/syndication/appsettings.json
  services/net/transcription/appsettings.json
Labels: bug, devops

#380 Change api Dockerfile image
  api/net/Dockerfile
  api/net/Dockerfile.aspnet
Labels: devops

#381 Reduce api build image size
  api/net/Dockerfile
Labels: devops

#382 Fix content service file copy
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/services/clip/base/deploy.yaml
  openshift/kustomize/services/filemonitor/base/deploy.yaml
  openshift/kustomize/services/image/base/deploy.yaml
  services/net/capture/CaptureAction.cs
  services/net/capture/appsettings.json
  services/net/clip/ClipAction.cs
  services/net/clip/appsettings.json
  services/net/content/ContentManager.cs
  services/net/content/appsettings.json
  services/net/filemonitor/appsettings.json
  services/net/image/ImageAction.cs
  services/net/image/appsettings.json
  services/net/indexing/appsettings.json
  services/net/nlp/appsettings.json
  services/net/syndication/appsettings.json
  services/net/transcription/appsettings.json
Labels: bug, devops

#383 Correct Front page published on date
  app/editor/src/features/admin/ingests/configurations/FrontPage.tsx
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  services/net/image/ImageAction.cs
Labels: enhancement

#376 TNO-679: Allow user editing
  app/editor/src/features/admin/users/UserForm.tsx
Labels: enhancement

#386 TNO-710 Update Clip service to run remotely
  app/editor/src/features/admin/connections/configurations/AWSConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/AzureConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/FTPConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/HTTPConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/NASConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/SFTPConfiguration.tsx
  app/editor/src/features/admin/connections/configurations/SSHConfiguration.tsx
  app/editor/src/features/admin/ingests/IngestSettings.tsx
  app/editor/src/features/admin/ingests/configurations/AudioClip.tsx
  app/editor/src/features/admin/ingests/configurations/AudioStream.tsx
  app/editor/src/features/admin/ingests/configurations/VideoClip.tsx
  app/editor/src/features/admin/ingests/configurations/VideoStream.tsx
  libs/net/core/Extensions/StringExtensions.cs
  libs/net/dal/Extensions/IngestExtensions.cs
  services/net/Makefile
  services/net/clip/ClipAction.cs
  services/net/clip/TNO.Services.Clip.csproj
  services/net/content/ContentManager.cs
  services/net/filemonitor/FilemonitorAction.cs
  services/net/image/ImageAction.cs
Labels: bug, enhancement

#389 Fixed TNO-535
  app/editor/src/features/content/form/ContentForm.tsx
Labels: enhancement

#391 Fixed TNO-665
  libs/net/dal/Migrations/Initial/Up/PostUp/00-Connection.sql
Labels: bug, enhancement

#385 Fixed TNO-697
  api/net/Areas/Admin/Controllers/WorkOrderController.cs
  api/net/Areas/Editor/Controllers/WorkOrderController.cs
  api/net/Areas/Services/Controllers/WorkOrderController.cs
  api/net/Program.cs
  api/net/WorkOrderHub.cs
  api/net/appsettings.json
  app/editor/.yarn/cache/@microsoft-signalr-npm-6.0.10-e238925b6c-dc25a2afee.zip
  app/editor/.yarn/cache/abort-controller-npm-3.0.0-2f3a9a2bcb-170bdba9b4.zip
  app/editor/.yarn/cache/event-target-shim-npm-5.0.1-cb48709025-1ffe3bb22a.zip
  app/editor/.yarn/cache/eventsource-npm-1.1.2-7fcd82f3f4-fe8f2ac3c7.zip
  app/editor/.yarn/cache/fetch-cookie-npm-0.11.0-c1249118a6-0d2082cb7d.zip
  app/editor/.yarn/cache/node-fetch-npm-2.6.7-777aa2a6df-8d816ffd1e.zip
  app/editor/.yarn/cache/querystringify-npm-2.2.0-4e77c9f606-5641ea231b.zip
  app/editor/.yarn/cache/tough-cookie-npm-4.1.2-09068826e1-a7359e9a3e.zip
  app/editor/.yarn/cache/tr46-npm-0.0.3-de53018915-726321c5ea.zip
  app/editor/.yarn/cache/universalify-npm-0.2.0-9984e61c10-e86134cb12.zip
  app/editor/.yarn/cache/url-parse-npm-1.5.10-64fa2bcd6d-fbdba6b1d8.zip
  app/editor/.yarn/cache/webidl-conversions-npm-3.0.1-60310f6a2b-c92a0a6ab9.zip
  app/editor/.yarn/cache/whatwg-url-npm-5.0.0-374fb45e60-b8daed4ad3.zip
  app/editor/.yarn/cache/ws-npm-7.5.9-26f12a5ed6-c3c100a181.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/hooks/api-editor/constants/Settings.ts
  app/editor/src/hooks/api-editor/editor/index.ts
  app/editor/src/hooks/api-editor/editor/useApiHubConnection.ts
  app/editor/yarn.lock
Labels: enhancement

#394 Fixed TNO-635
  libs/net/dal/Migrations/Initial/Up/PostUp/00-License.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/01-Source.sql
Labels: bug, enhancement

#390 Changes for TNO-709 in new branch TNO-709-2
  api/net/Areas/Admin/Models/Ingest/SourceModel.cs
  api/net/Areas/Admin/Models/Source/SourceModel.cs
  app/editor/src/features/admin/sources/SourceDetails.tsx
  app/editor/src/hooks/api-editor/interfaces/ISourceModel.ts
  libs/net/dal/Migrations/Initial/Up/PostUp/01-Source.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  libs/net/dal/Models/SourceFilter.cs
  libs/net/models/Areas/Editor/Models/Content/SourceModel.cs
  libs/net/models/Areas/Editor/Models/Source/SourceModel.cs
  libs/net/models/Areas/Services/Models/Ingest/SourceModel.cs
  services/net/filemonitor/FilemonitorAction.cs
Labels: enhancement

#397 Fixed TNO-717
  api/net/Areas/Admin/Models/Action/ActionModel.cs
  api/net/Areas/Admin/Models/Product/ProductModel.cs
Labels: bug

#396 TNO-734 Update capture
  app/editor/src/features/admin/ingests/configurations/VideoRPi.tsx
  app/editor/src/features/admin/ingests/configurations/VideoStream.tsx
  services/net/capture/CaptureAction.cs
Labels: bug

#400 Fixed TNO-719
  app/editor/src/features/content/list-view/ContentFilter.tsx
Labels: enhancement

#395 TNO-697 updates just for testing on dev only
  api/net/Program.cs
  api/net/appsettings.json
  app/editor/nginx/local.conf
  app/editor/src/hooks/api-editor/editor/useApiHubConnection.ts
Labels: bug

#401 Fixed TNO-675
  services/net/content/ContentManager.cs
Labels: bug

#399 Modify to process only one file at a time and create a single SourceContent object at a time
  services/net/filemonitor/FilemonitorAction.cs
Labels: enhancement

#402 Adding style to retain front page image aspect ratio
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/styled/ContentSummaryForm.tsx
Labels: enhancement

#403 TNO-643 Fix content service ssh
  app/editor/src/features/admin/ingests/configurations/AudioClip.tsx
  app/editor/src/features/admin/ingests/configurations/VideoClip.tsx
  app/editor/src/features/admin/ingests/configurations/VideoRPi.tsx
  libs/net/ches/TNO.Ches.csproj
  libs/net/core/Extensions/StringExtensions.cs
  libs/net/core/TNO.Core.csproj
  services/net/capture/CaptureManager.cs
  services/net/clip/ClipAction.cs
  services/net/clip/ClipManager.cs
  services/net/content/ContentManager.cs
  services/net/content/TNO.Services.Content.csproj
  tools/scripts/purge-folders.sh
Labels: bug, enhancement

#398 TNO-730: Clear button on react-select
  app/editor/src/components/form/select/Select.tsx
  app/editor/src/components/form/select/styled/Select.tsx
  app/editor/src/components/form/select/styled/SelectField.tsx
  app/editor/src/features/admin/users/UserForm.tsx
  app/editor/src/features/admin/users/styled/UserList.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/list-view/ContentFilter.tsx
Labels: enhancement

#407 TNO-728: Scrolling styling and removing footer
  app/editor/src/components/form/formpage/styled/FormPage.tsx
  app/editor/src/components/layout/DefaultLayout.tsx
  app/editor/src/components/layout/LayoutAnonymous.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
Labels: enhancement

#404 TNO-697 updates for testing on dev #2
  api/net/appsettings.json
  app/editor/nginx/local.conf
  app/editor/src/hooks/api-editor/editor/useApiHubConnection.ts
  network/nginx/config/default.conf
Labels: bug, enhancement

#408 Fixed TNO-753
  app/editor/src/features/admin/licenses/LicenseForm.tsx
  app/editor/src/features/admin/licenses/LicenseList.tsx
  app/editor/src/features/admin/sources/SourceDetails.tsx
  app/editor/src/features/admin/sources/constants/columns.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/navbar/NavBar.tsx
  app/editor/src/hooks/api-editor/validation/SourceSchema.ts
Labels: bug, enhancement

#409 TNO-670 Fix content redux hook
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/store/hooks/editor/useContent.ts
  app/editor/src/store/hooks/editor/useWorkOrders.ts
  network/nginx/config/default.conf
Labels: bug

#410 Fixed TNO-703
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: enhancement

#412 Fixed TNO-760
  libs/npm/core/src/components/button/styled/Button.tsx
Labels: bug

#411 Fixed TNO-747
  app/editor/public/assets/mminsights_logo.svg
  libs/npm/core/src/components/header/Header.tsx
  libs/npm/core/src/components/header/styled/Header.tsx
Labels: enhancement

#413 WYSIWYG Bugs - Part 1/2
  app/editor/src/components/form/wysiwyg/CustomToolbar.tsx
  app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
  app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx
Labels: bug

#416 TNO-764, TNO-765: Select Field Tweaks
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/list-view/ContentFilter.tsx
Labels: bug

#415 Add manual page length selector to PagedTable and increase the default list length in UserList to 20
  app/editor/src/features/admin/users/UserFilter.tsx
  app/editor/src/features/admin/users/UserList.tsx
  app/editor/src/store/slices/admin/adminSlice.ts
  libs/npm/core/src/components/grid-table/Pager.tsx
Labels: enhancement

#421 Clearable dropdown bugs
  app/editor/src/components/form/select/Select.tsx
  app/editor/src/components/form/select/styled/Select.tsx
Labels: bug

#422 TNO-764 Fix dropdown Event of Day Category
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/navbar/NavBar.tsx
Labels: bug
