Repository bcgov/tno, pull requests merged in 2022-03, with the labels that each got.

#54 TNO-223 Add CBRA report
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/core/excel/CBRAReport.java
Labels: enhancement

#56 TNO-208 Fix content actions
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/ContentModel.java
  libs/java/dal/db/dal-db-test/src/main/java/ca/bc/gov/tno/dal/db/ContentTest.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentAction.java
  test/TNO.postman_collection.json
Labels: bug

#57 TNO-208 Fix content time tracking
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/ContentModel.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ContentService.java
Labels: bug

#58 TNO-208 Fix update content
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/controllers/ContentController.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Action.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Category.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Claim.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Content.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentAction.java
Labels: bug

#59 TNO-208 Fix content service
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/converters/LocalDateTimeConverter.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/converters/ZonedDateTimeConverter.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentCategory.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentLink.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentReference.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTag.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTone.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentType.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTypeAction.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSource.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSourceSchedule.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/FileReference.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/License.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/MediaType.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/PrintContent.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Role.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/RoleClaim.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Schedule.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Series.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Tag.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/TimeTracking.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/TonePool.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/User.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/UserRole.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/repositories/interfaces/IActionRepository.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/repositories/interfaces/IRefreshRepository.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ActionService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ContentActionService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ContentCategoryService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ContentLinkService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ContentService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ContentTagService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/ContentToneService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/Settings.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/interfaces/IContentActionService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/interfaces/IContentCategoryService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/interfaces/IContentLinkService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/interfaces/IContentTagService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/interfaces/IContentToneService.java
Labels: bug

#61 Fix content list view filter
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/constants/defaultFilter.ts
  app/editor/src/features/content/list-view/constants/index.ts
  app/editor/src/store/hooks/content/useContent.ts
  app/editor/src/store/slices/content/useContentStore.ts
Labels: bug

#64 TNO-250: Reusable Modal
  app/editor/src/components/modal/Modal.tsx
  app/editor/src/components/modal/index.ts
  app/editor/src/components/modal/styled/Modal.tsx
  app/editor/src/components/modal/styled/index.ts
  app/editor/src/components/row/Row.tsx
  app/editor/src/hooks/modal/useModal.ts
Labels: enhancement

#67 TNO-246 Add audio clip service
  openshift/templates/services/audio/clip/build.yaml
  openshift/templates/services/audio/clip/deploy.yaml
  services/capture/pom.xml
Labels: bug, devops

#70 TNO-228 Yarn clean cache
  app/editor/Dockerfile.nginx
  app/editor/Dockerfile.rhel8
Labels: devops

#71 Content List View Bug Fix
  app/editor/src/features/content/list-view/ContentListView.tsx
Labels: bug

#72 Fixed delete content
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/controllers/ContentController.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/ContentModel.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Action.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Category.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Claim.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Content.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentAction.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentCategory.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentLink.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentReference.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTag.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTone.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentType.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTypeAction.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataLocation.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSource.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSourceSchedule.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/FileReference.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/License.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/MediaType.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/PrintContent.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Role.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/RoleClaim.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Schedule.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Series.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Tag.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/TimeTracking.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/TonePool.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/User.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/UserRole.java
Labels: bug

#77 TNO-243 Update tno-core
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/admin/sources/DataSource.tsx
  app/editor/src/features/admin/sources/schedules/Schedule.tsx
  app/editor/src/features/admin/sources/schedules/ScheduleContinuos.tsx
  app/editor/src/features/admin/sources/schedules/ScheduleProgram.tsx
  app/editor/src/features/admin/sources/schedules/ScheduleSingle.tsx
  app/editor/src/features/admin/sources/schedules/constants/columns.tsx
  app/editor/src/features/admin/sources/schedules/constants/index.ts
  app/editor/src/features/admin/sources/schedules/styled/Schedule.tsx
  app/editor/src/hooks/api-editor/constants/WeekDay.ts
  app/editor/src/hooks/api-editor/constants/WeekDayName.ts
  app/editor/src/hooks/api-editor/constants/index.ts
  app/editor/yarn.lock
Labels: bug

#78 Tno 255
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/config/DataSourceConfig.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/events/ErrorEvent.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/handlers/ErrorHandler.java
  services/capture/src/main/java/ca/bc/gov/tno/services/capture/config/CaptureConfig.java
  services/capture/src/main/java/ca/bc/gov/tno/services/capture/handlers/FetchDataService.java
  services/capture/src/main/java/ca/bc/gov/tno/services/capture/handlers/ScheduledService.java
Labels: enhancement
