Repository bcgov/tno, pull requests merged in 2022-01, with the labels that each got.

#28 Initial version of the audio service
  .gitignore
  db/kafka/migrations/U1.0.0.sh
  db/kafka/migrations/V1.0.0.sh
  docker-compose.yml
  services/audio/.devcontainer/Dockerfile
  services/audio/.devcontainer/devcontainer.json
  services/audio/.dockerignore
  services/audio/.gitignore
  services/audio/.prettier.js
  services/audio/.vscode/launch.json
  services/audio/.vscode/settings.json
  services/audio/.vscode/tasks.json
  services/audio/Dockerfile
  services/audio/Makefile
  services/audio/README.md
  services/audio/pom.xml
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/AudioServiceApp.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/config/AudioCollectionConfig.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/config/AudioConfig.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/events/ProducerSendEvent.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/handlers/FetchDataService.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/handlers/ScheduledService.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/kafka/KafkaAudioProducer.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/models/PublishedRecord.java
  services/audio/src/main/resources/application.yml
  services/audio/src/main/resources/log4j2.yml
  services/audio/src/test/java/ca/bc/gov/tno/services/audio/AudioServiceAppTests.java
  tools/scripts/gen-env-files.sh
  tools/scripts/variables.sh
Labels: enhancement

#30 TNO-129 Add elasticsearch devops templates
  openshift/templates/api/route.yaml
  openshift/templates/app/route.yaml
  openshift/templates/elastic/cluster/README.md
  openshift/templates/elastic/cluster/deploy.yaml
  openshift/templates/elastic/cluster/route.yaml
  openshift/templates/elastic/cluster/secrets.yaml
  openshift/templates/elastic/singleton/README.md
  openshift/templates/elastic/singleton/config.yaml
  openshift/templates/elastic/singleton/deploy.yaml
  openshift/templates/elastic/singleton/pvc.yaml
  openshift/templates/elastic/singleton/route.yaml
  openshift/templates/elastic/singleton/secrets.yaml
  openshift/templates/postgres/patroni/deploy.yaml
  openshift/templates/postgres/patroni/pvc.yaml
  openshift/templates/postgres/patroni/secrets.yaml
  openshift/templates/postgres/patroni/service-account.yaml
  openshift/templates/postgres/singleton/build.yaml
  openshift/templates/postgres/singleton/deploy.yaml
  openshift/templates/postgres/singleton/pvc.yaml
  openshift/templates/postgres/singleton/secrets.yaml
  tools/scripts/variables.sh
Labels: devops

#32 TNO-116 Add Kafka devops
  Makefile
  db/kafka/broker/Dockerfile
  db/kafka/cat/Dockerfile
  db/kafka/kowl/Dockerfile
  db/kafka/ksqldb/Dockerfile
  db/kafka/rest-proxy/Dockerfile
  db/kafka/schema-registry/Dockerfile
  db/kafka/zookeeper/Dockerfile
  libs/java/core/.devcontainer/Dockerfile
  libs/java/core/.devcontainer/devcontainer.json
  libs/java/core/pom.xml
  libs/java/dal/db/.devcontainer/Dockerfile
  libs/java/dal/db/.devcontainer/devcontainer.json
  libs/java/dal/elastic/.devcontainer/Dockerfile
  libs/java/dal/elastic/.devcontainer/devcontainer.json
  libs/java/dal/elastic/pom.xml
  libs/java/service/.devcontainer/Dockerfile
  libs/java/service/.devcontainer/devcontainer.json
  libs/java/service/pom.xml
  openshift/README.md
  openshift/templates/api/README.md
  openshift/templates/kafka/README.md
  openshift/templates/kafka/broker/build.yaml
  openshift/templates/kafka/broker/deploy.yaml
  openshift/templates/kafka/ksql/build.yaml
  openshift/templates/kafka/ksql/deploy.yaml
  openshift/templates/kafka/rest-proxy/deploy.yaml
  openshift/templates/kafka/rest-proxy/route.yaml
  openshift/templates/kafka/schema-registry/deploy.yaml
  openshift/templates/kafka/zookeeper/build.yaml
  openshift/templates/kafka/zookeeper/deploy.yaml
  services/audio/.devcontainer/Dockerfile
  services/audio/.devcontainer/devcontainer.json
  services/audio/pom.xml
  services/elastic/.devcontainer/Dockerfile
  services/elastic/.devcontainer/devcontainer.json
  services/elastic/pom.xml
  services/nlp/.devcontainer/Dockerfile
  services/nlp/.devcontainer/devcontainer.json
  services/nlp/pom.xml
  services/syndication/.devcontainer/Dockerfile
  services/syndication/.devcontainer/devcontainer.json
  services/syndication/pom.xml
  tools/scripts/gen-env-files.sh
Labels: devops

#33 Fixed maven package gpg issue
  .github/CODEOWNERS
  docs/DEVELOPMENT.md
  libs/java/dal/db/.devcontainer/Dockerfile
  libs/java/dal/db/dal-db/pom.xml
  libs/java/dal/db/scripts/close-staging-repo.sh
  libs/java/dal/db/scripts/deploy-release.sh
  libs/java/dal/db/scripts/deploy-staging.sh
  libs/java/dal/db/scripts/drop-staging-repo.sh
  libs/java/dal/db/scripts/release-staging-repo.sh
  libs/java/dal/db/scripts/setup.sh
  tools/scripts/gen-maven-files.sh
  tools/scripts/os.sh
  tools/scripts/variables.sh
Labels: bug

#34 TNO-116 Kafka DevOps
  Makefile
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/ApiEditor.java
  openshift/README.md
  openshift/templates/api/deploy.yaml
  openshift/templates/elastic/cluster/deploy.yaml
  openshift/templates/kafka/broker/deploy.yaml
  openshift/templates/kafka/ksql/deploy.yaml
  openshift/templates/kafka/rest-proxy/deploy.yaml
  openshift/templates/kafka/zookeeper/deploy.yaml
  openshift/templates/postgres/patroni/deploy.yaml
  openshift/templates/sonarqube/README.md
  openshift/templates/sonarqube/deploy.yaml
  openshift/templates/sonarqube/postgres/deploy.yaml
  openshift/templates/sonarqube/postgres/pvc.yaml
  openshift/templates/sonarqube/postgres/secrets.yaml
  openshift/templates/sonarqube/pvc.yaml
  openshift/templates/sonarqube/route.yaml
  openshift/templates/sonarqube/secrets.yaml
  openshift/templates/sysdig/README.md
  openshift/templates/sysdig/authorize.yaml
  openshift/templates/tekton/README.md
  openshift/templates/tekton/build/react-nginx.yaml
  openshift/templates/tekton/conditions/run-owasp.yaml
  openshift/templates/tekton/pipelines/build-deploy-with-template.yaml
  openshift/templates/tekton/service-account/role.yaml
  openshift/templates/tekton/service-account/service-account.yaml
  openshift/templates/tekton/tasks/oc-deploy-with-tag.yaml
  openshift/templates/tekton/tasks/owasp-scanner.yaml
  openshift/templates/tekton/triggers/git-pipeline-with-template.yaml
  tools/scripts/switch-project.sh
Labels: devops

#35 Fix maven gpg signing
  libs/java/dal/db/.devcontainer/Dockerfile
  libs/java/dal/db/.devcontainer/gpg-agent.conf
  libs/java/dal/db/.devcontainer/gpg.conf
  libs/java/dal/db/Makefile
  libs/java/dal/db/scripts/close-staging-repo.sh
  libs/java/dal/db/scripts/deploy-release.sh
  libs/java/dal/db/scripts/deploy-staging.sh
  libs/java/dal/db/scripts/drop-staging-repo.sh
  libs/java/dal/db/scripts/release-staging-repo.sh
  libs/java/dal/db/scripts/setup.sh
Labels: bug

#36 Fix Kafka local docker
  Makefile
  db/kafka/broker/Dockerfile
  db/kafka/broker/Dockerfile.rhel
  db/kafka/ksqldb/Dockerfile
  db/kafka/ksqldb/Dockerfile.rhel
  db/kafka/migrations/U1.0.0.sh
  db/kafka/migrations/V1.0.0.sh
  db/kafka/scripts/migration.sh
  db/kafka/zookeeper/Dockerfile
  db/kafka/zookeeper/Dockerfile.rhel
  openshift/templates/kafka/broker/build.yaml
  openshift/templates/kafka/ksql/build.yaml
  openshift/templates/kafka/zookeeper/build.yaml
  tools/scripts/gen-env-files.sh
Labels: bug

#38 TNO-185 Refactoring DB
  Makefile
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/controllers/ActionController.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/controllers/ContentController.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/controllers/HealthController.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/controllers/HomeController.java
  libs/java/dal/db/dal-db-migration/pom.xml
  libs/java/dal/db/dal-db-migration/src/main/resources/application.yml
  libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/U1_0_0__Init.sql
  libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/U1__Init.sql
  libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/V1_0_0__Init.sql
  libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/V1__Init.sql
  libs/java/dal/db/dal-db-test/pom.xml
  libs/java/dal/db/dal-db-test/src/main/java/ca/bc/gov/tno/dal/db/ContentReferenceTest.java
  libs/java/dal/db/dal-db-test/src/main/java/ca/bc/gov/tno/dal/db/ContentTest.java
  libs/java/dal/db/dal-db-test/src/main/resources/application.yml
  libs/java/dal/db/dal-db/pom.xml
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/AuditColumns.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Action.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Category.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Claim.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Content.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentAction.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentCategory.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentLink.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentReference.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTag.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTagPK.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentTone.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentType.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSource.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/FileReference.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/License.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/MediaType.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Role.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/RoleClaim.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Schedule.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Tag.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/TimeTracking.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/TonePool.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/User.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/UserRole.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/models/ConnectionSyndication.java
  libs/java/dal/db/scripts/db-update.sh
  openshift/README.md
  openshift/templates/api/deploy.yaml
  openshift/templates/tekton/build/java-maven.yaml
  openshift/templates/tekton/build/react-nginx.yaml
  openshift/templates/tekton/pipelines/build-deploy-with-template.yaml
  openshift/templates/tekton/tasks/oc-build-with-template.yaml
  openshift/templates/tekton/triggers/git-binding.yaml
  openshift/templates/tekton/triggers/git-eventlistener.yaml
  openshift/templates/tekton/triggers/git-ingress.yaml
  openshift/templates/tekton/triggers/git-triggertemplate.yaml
Labels: bug, enhancement, DB Migration, devops

#39 Fix DB Migration
  Makefile
  app/editor/.devcontainer/devcontainer.json
  db/kafka-enterprise/docker-compose.yml
  db/kafka/docker-compose.yml
  docker-compose.yml
  libs/java/dal/db/dal-db-migration/pom.xml
  libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/U1__Init.sql
  libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/V1__Init.sql
  network/nginx/config/default.conf
  tools/scripts/db-update.sh
Labels: bug, DB Migration
