Repository bcgov/tno, pull requests merged in 2022-09, with the labels that each got.

#243 TNO-451 Transcription DevOps
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Config/KafkaOptions.cs
  libs/net/core/Converters/EnumValueJsonConverter.cs
  libs/net/kafka/Interfaces/IKafkaMessenger.cs
  libs/net/kafka/KafkaListener`.cs
  libs/net/kafka/KafkaMessenger.cs
  libs/net/models/Kafka/ContentBase.cs
  libs/net/models/Kafka/IndexRequest.cs
  libs/net/models/Kafka/NotificationRequest.cs
  libs/net/models/Kafka/SourceContent.cs
  libs/net/models/Kafka/Tag.cs
  libs/net/models/Kafka/TrascriptRequest.cs
  openshift/kustomize/services/transcription/base/config-map.yaml
  openshift/kustomize/services/transcription/base/deploy.yaml
  openshift/kustomize/services/transcription/base/kustomization.yaml
  openshift/kustomize/services/transcription/base/secret.yaml
  openshift/kustomize/services/transcription/base/service.yaml
  openshift/kustomize/services/transcription/overlays/dev/kustomization.yaml
  openshift/kustomize/services/transcription/overlays/prod/kustomization.yaml
  openshift/kustomize/services/transcription/overlays/test/kustomization.yaml
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/content/ContentManager.cs
  services/net/image/ImageAction.cs
  services/net/image/appsettings.json
  services/net/nlp/NLPAction.cs
  services/net/syndication/SyndicationAction.cs
  services/net/transcription/TranscriptionManager.cs
  services/net/transcription/TranscriptionService.cs
  services/net/transcription/appsettings.json
  tools/scripts/gen-env-files.sh
Labels: bug, devops

#245 Fixed the TNO-521 issue
  app/editor/src/features/content/form/ContentClipForm.tsx
Labels: enhancement

#244 configure data source for clip and capture services
  app/editor/src/features/admin/sources/DataSourceDetails.tsx
  libs/net/dal/Migrations/Initial/Up/PostUp/01-DataSource.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/02-DataSourceSchedule.sql
Labels: DB Migration

#247 TNO-451 Fix kafka consumer
  .code-workspace
  .vscode/launch.json
  .vscode/tasks.json
  TNO.sln
  libs/net/TNO.sln
  libs/net/kafka/KafkaListener`.cs
  openshift/kustomize/app/editor/build/base/build.yaml
  services/net/content/ContentManager.cs
  services/net/indexing/IndexingManager.cs
  services/net/transcription/TranscriptionManager.cs
Labels: bug

#246 Fixed TNO-522
  app/editor/src/features/content/form/ContentClipForm.tsx
Labels: enhancement

#248 TNO-520: Breadcrumb trail for clips
  app/editor/src/components/breadcrumb/Breadcrumb.tsx
  app/editor/src/components/breadcrumb/index.ts
  app/editor/src/components/breadcrumb/styled/Breadcrumb.tsx
  app/editor/src/components/breadcrumb/styled/index.ts
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/styled/Breadcrumb.tsx
  app/editor/src/features/content/form/styled/index.ts
Labels: enhancement

#250 Minor clip styling
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/constants/clipDirectoryColumns.tsx
  app/editor/src/features/content/form/styled/ContentClipForm.tsx
Labels: enhancement

#251 Breadcrumb UI tweaks
  app/editor/src/components/breadcrumb/Breadcrumb.tsx
  app/editor/src/components/breadcrumb/styled/Breadcrumb.tsx
  app/editor/src/features/content/form/styled/Breadcrumb.tsx
  app/editor/src/features/content/form/styled/index.ts
Labels: bug

#252 Fixed TNO-585
  app/editor/src/hooks/api-editor/constants/ScheduleType.ts
  libs/net/dal/Migrations/Initial/Up/PostUp/01-DataSource.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/02-DataSourceSchedule.sql
  libs/net/entities/ScheduleType.cs
Labels: enhancement, DB Migration

#254 Fixed TNO-586
  libs/net/dal/Migrations/Initial/Up/PostUp/01-DataSource.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/02-DataSourceSchedule.sql
Labels: enhancement, DB Migration

#255 TNO-91 Add content labels
  .vscode/launch.json
  .vscode/tasks.json
  api/net/Areas/Services/Controllers/DataSourceController.cs
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentLabelsForm.tsx
  app/editor/src/features/content/form/constants/defaultFormValues.ts
  app/editor/src/features/content/form/constants/index.ts
  app/editor/src/features/content/form/constants/labelOptions.ts
  app/editor/src/features/content/form/index.tsx
  app/editor/src/features/content/form/interfaces/IContentForm.tsx
  app/editor/src/features/content/form/styled/ContentLabelsForm.tsx
  app/editor/src/features/content/form/styled/index.ts
  app/editor/src/features/content/form/utils/toForm.ts
  app/editor/src/features/content/form/utils/toModel.ts
  libs/net/dal/Services/DataSourceService.cs
  libs/net/dal/Services/Interfaces/IDataSourceService.cs
  libs/net/entities/ContentLabel.cs
  openshift/kustomize/services/build/base/nlp.yaml
  openshift/kustomize/services/capture/base/config-map.yaml
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/services/clip/base/config-map.yaml
  openshift/kustomize/services/clip/base/deploy.yaml
  openshift/kustomize/services/content/base/config-map.yaml
  openshift/kustomize/services/indexing/base/config-map.yaml
  openshift/kustomize/services/indexing/base/deploy.yaml
  openshift/kustomize/services/nlp/base/config-map.yaml
  openshift/kustomize/services/nlp/base/deploy.yaml
  openshift/kustomize/services/syndication/base/config-map.yaml
  openshift/kustomize/services/syndication/base/deploy.yaml
  openshift/kustomize/services/transcription/base/config-map.yaml
  openshift/kustomize/services/transcription/base/deploy.yaml
  services/net/nlp/OpenNLP/EntityExtractor.cs
  test/TNO.postman_collection.json
Labels: bug, enhancement

#256 Fixing various bugs
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentLabelsForm.tsx
  app/editor/src/features/content/form/ContentTranscriptForm.tsx
  libs/net/dal/Models/ContentFileReference.cs
  libs/net/models/Areas/Editor/Models/Content/FileReferenceModel.cs
  libs/net/models/Areas/Services/Models/Content/FileReferenceModel.cs
  services/docker-compose.yml
  services/net/transcription/appsettings.json
Labels: bug

#261 Fix data source bug
  .vscode/launch.json
  .vscode/tasks.json
  api/net/Areas/Services/Controllers/DataSourceController.cs
  libs/net/dal/Services/DataSourceService.cs
  libs/net/dal/Services/Interfaces/IDataSourceService.cs
  libs/net/kafka/KafkaListener`.cs
  services/net/capture/CaptureAction.cs
Labels: bug

#258 TNO-531. 530
  app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx
  libs/net/dal/Migrations/Initial/Up/PostUp/01-DataSource.sql
Labels: bug

#257 Fixed TNO-521 (#2)
  app/editor/src/features/content/form/ContentClipForm.tsx
Labels: bug, enhancement

#259 TNO-428: Print content
  app/editor/src/features/content/form/ContentActions.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/FormPicker.tsx
  app/editor/src/features/content/form/constants/defaultFormValues.ts
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/router/AppRouter.tsx
Labels: enhancement

#263 TNO-577: Allow access from iOS
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#264 TNO-597 Update DB migration
  Makefile
  api/net/Areas/Admin/Models/DataSource/DataSourceModel.cs
  app/editor/src/features/admin/sources/DataSourceDetails.tsx
  app/editor/src/features/admin/sources/DataSourceForm.tsx
  app/editor/src/features/admin/sources/connections/AudioClip.tsx
  app/editor/src/features/admin/sources/connections/AudioStream.tsx
  app/editor/src/features/admin/sources/connections/Syndication.tsx
  app/editor/src/features/admin/sources/connections/VideoClip.tsx
  app/editor/src/features/admin/sources/connections/VideoStream.tsx
  app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx
  app/editor/src/features/admin/sources/services/ServiceSchedule.tsx
  app/editor/src/hooks/api-editor/interfaces/IDataSourceModel.ts
  libs/net/dal/Configuration/ContentConfiguration.cs
  libs/net/dal/Migrations/20220912221332_Initial.Designer.cs
  libs/net/dal/Migrations/20220912221332_Initial.cs
  libs/net/dal/Migrations/Initial/Up/PostUp/00-ContentType.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/01-DataSource.sql
  libs/net/dal/Migrations/TNOContextModelSnapshot.cs
  libs/net/entities/Content.cs
  libs/net/entities/ContentType.cs
  libs/net/entities/DataSource.cs
  libs/net/kafka/Interfaces/IKafkaListener`.cs
  libs/net/kafka/KafkaListener`.cs
  libs/net/models/Areas/Editor/Models/Content/ContentModel.cs
  libs/net/models/Areas/Editor/Models/Content/DataSourceModel.cs
  libs/net/models/Areas/Editor/Models/DataSource/DataSourceModel.cs
  libs/net/models/Areas/Services/Models/Content/ContentModel.cs
  libs/net/models/Areas/Services/Models/DataSource/DataSourceModel.cs
  openshift/kustomize/api/build/base/build.yaml
  openshift/kustomize/app/editor/build/base/build.yaml
  openshift/kustomize/db-migration/build/base/build.yaml
  openshift/templates/tekton/pipelines/complete.yaml
  services/net/content/ContentManager.cs
  services/net/content/ContentService.cs
  services/net/content/appsettings.Development.json
  services/net/content/appsettings.Staging.json
  services/net/content/appsettings.json
  services/net/indexing/IndexingManager.cs
  services/net/nlp/NLPManager.cs
  services/net/transcription/TranscriptionManager.cs
  tools/import/etl/ImportService.cs
Labels: bug, enhancement, DB Migration

#266 TNO-581, 602
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/FormPicker.tsx
Labels: bug

#267 Fix Kafka Consumer Services
  libs/net/core/Exceptions/HttpClientRequestException.cs
  libs/net/kafka/KafkaListener`.cs
  openshift/kustomize/api/build/base/build.yaml
  openshift/kustomize/app/editor/build/base/build.yaml
  openshift/kustomize/db-migration/build/base/build.yaml
  openshift/templates/tekton/pipelines/complete.yaml
  services/net/content/ContentManager.cs
  services/net/indexing/IndexingManager.cs
  services/net/nlp/NLPManager.cs
  services/net/transcription/TranscriptionManager.cs
Labels: bug

#268 Fix Kafka consumer
  libs/net/kafka/KafkaListener`.cs
Labels: bug

#271 TNO-427: Tooltip not disappearing on dropdown
  app/editor/src/components/form/select/Select.tsx
Labels: bug

#269 Fixed TNO-598
  app/editor/src/features/content/form/styled/ContentForm.tsx
Labels: enhancement

#270 Fix Kafka Consumer Services
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/list-view/constants/condensedColumns.tsx
  app/editor/src/hooks/api-editor/validation/DataSourceSchema.ts
  libs/net/core/Exceptions/HttpClientRequestException.cs
  libs/net/core/Http/HttpRequestClient.cs
  libs/net/kafka/ConsumerAction.cs
  libs/net/kafka/Interfaces/IKafkaListener`.cs
  libs/net/kafka/KafkaListener`.cs
  openshift/kustomize/services/content/base/deploy.yaml
  openshift/kustomize/services/content/overlays/dev/kustomization.yaml
  openshift/kustomize/services/content/overlays/prod/kustomization.yaml
  openshift/kustomize/services/content/overlays/test/kustomization.yaml
  services/net/content/Config/ContentOptions.cs
  services/net/content/ContentManager.cs
  services/net/content/appsettings.json
  services/net/indexing/Config/IndexingOptions.cs
  services/net/indexing/IndexingManager.cs
  services/net/indexing/appsettings.json
  services/net/nlp/Config/NLPOptions.cs
  services/net/nlp/NLPManager.cs
  services/net/nlp/appsettings.json
  services/net/transcription/Config/TranscriptionOptions.cs
  services/net/transcription/TranscriptionManager.cs
  services/net/transcription/appsettings.json
Labels: bug

#272 TNO-418: Change error validation
  app/editor/src/components/form/checkbox/Checkbox.tsx
  app/editor/src/components/form/datepicker/SelectDate.tsx
  app/editor/src/components/form/error/Error.tsx
  app/editor/src/components/form/error/index.ts
  app/editor/src/components/form/index.ts
  app/editor/src/components/form/radio/RadioGroup.tsx
  app/editor/src/components/form/select/Select.tsx
  app/editor/src/components/form/textarea/TextArea.tsx
  app/editor/src/components/form/timeinput/TimeInput.tsx
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/styled/ContentClipForm.tsx
Labels: enhancement

#265 Deploy image service
  openshift/kustomize/services/build/base/image.yaml
  openshift/kustomize/services/build/overlays/dev/kustomization.yaml
  openshift/kustomize/services/image/base/README.md
  openshift/kustomize/services/image/base/config-map.yaml
  openshift/kustomize/services/image/base/deploy.yaml
  openshift/kustomize/services/image/base/kustomization.yaml
  openshift/kustomize/services/image/base/pvc.yaml
  openshift/kustomize/services/image/base/service.yaml
  openshift/kustomize/services/image/overlays/dev/kustomization.yaml
  openshift/kustomize/services/image/overlays/prod/kustomization.yaml
  openshift/kustomize/services/image/overlays/test/kustomization.yaml
  services/net/image/Dockerfile
  services/net/image/ImageAction.cs
Labels: devops

#273 Fixed TNO-420
  app/editor/src/components/layout/DefaultLayout.tsx
Labels: bug

#275 Fixed TNO-420 #2
  app/editor/src/components/layout/DefaultLayout.tsx
Labels: bug

#276 TNO-121 Fix DB migration script
  libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/03-IngestSchedule.sql
Labels: bug, DB Migration

#277 Fixed a code merge issue for TNO-598
  app/editor/src/features/content/form/styled/ContentForm.tsx
Labels: bug, enhancement

#278 TNO-519: Clip warnings
  app/editor/src/features/content/form/ContentClipForm.tsx
Labels: bug

#279 Move byline
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug

#282 Fix Tag Admin
  app/editor/src/features/admin/tags/TagList.tsx
  app/editor/src/features/admin/tags/TagsForm.tsx
  app/editor/src/features/admin/tags/constants/columns.tsx
Labels: bug

#281 Content form validation
  .vscode/settings.json
  app/editor/.yarn/cache/tno-core-npm-0.0.165-043f99583f-2d70e0d546.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.172-4fbe354af6-30b17aff15.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/components/form/area/styled/Area.tsx
  app/editor/src/components/form/datepicker/SelectDate.tsx
  app/editor/src/components/form/datepicker/styled/SelectDate.tsx
  app/editor/src/components/form/radio/Radio.tsx
  app/editor/src/components/form/radio/RadioGroup.tsx
  app/editor/src/components/form/radio/styled/Radio.tsx
  app/editor/src/components/form/radio/styled/RadioGroup.tsx
  app/editor/src/components/formik/datepicker/FormikDatePicker.tsx
  app/editor/src/features/admin/sources/SourceForm.tsx
  app/editor/src/features/admin/users/UserList.tsx
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/hooks/useTabValidationToasts.ts
  app/editor/src/utils/hasErrors.ts
  app/editor/src/utils/index.ts
  app/editor/yarn.lock
  libs/npm/core/package.json
  libs/npm/core/src/components/tabs/Tab.tsx
  libs/npm/core/src/components/tabs/styled/Tab.tsx
Labels: enhancement

#283 Mapping paper names to source configuration
  services/net/filemonitor/FilemonitorAction.cs
  services/net/filemonitor/models/Fields.cs
Labels: enhancement

#287 TNO-627 Fix EoD filter
  app/editor/src/features/content/list-view/ContentFilter.tsx
  app/editor/src/features/content/list-view/constants/defaultFilter.ts
  app/editor/src/features/content/list-view/interfaces/IContentListFilter.ts
  app/editor/src/features/content/list-view/utils/makeFilter.ts
  app/editor/src/hooks/api-editor/interfaces/IContentFilter.ts
  app/editor/src/store/slices/content/contentSlice.ts
  libs/net/dal/Models/ContentFilter.cs
  libs/net/dal/Services/ContentService.cs
Labels: bug

#288 Fix ingest services
  libs/net/kafka/Models/ContentBase.cs
  libs/net/kafka/Models/SourceContent.cs
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/content/ContentManager.cs
  services/net/image/ImageAction.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#289 TNO-610 Fix Capture Services
  app/editor/src/features/admin/ingests/configurations/AudioClip.tsx
  app/editor/src/features/admin/ingests/configurations/AudioStream.tsx
  app/editor/src/features/admin/ingests/configurations/VideoClip.tsx
  app/editor/src/features/admin/ingests/configurations/VideoStream.tsx
  app/editor/src/hooks/api-editor/constants/WorkflowStatus.ts
  app/editor/src/hooks/api-editor/constants/WorkflowStatusName.ts
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  libs/net/entities/WorkflowStatus.cs
  services/net/content/ContentManager.cs
Labels: bug

#291 Fixed TNO-578
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug, enhancement

#292 TNO-637 Fix content body bugs
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/ContentTranscriptForm.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/validation/ContentFormSchema.ts
  services/net/content/ContentManager.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#293 TNO-445 Fix Kafka consumers
  app/editor/src/features/content/form/ContentForm.tsx
  libs/net/kafka/KafkaListener`.cs
  openshift/kustomize/README.md
  openshift/kustomize/services/transcription/base/config-map.yaml
  openshift/kustomize/services/transcription/base/deploy.yaml
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/content/ContentManager.cs
  services/net/indexing/IndexingManager.cs
  services/net/nlp/NLPManager.cs
  services/net/transcription/TranscriptionManager.cs
Labels: bug

#295 TNO-445 Fixing clip bugs
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Dockerfile
  app/editor/src/features/content/form/ContentClipForm.tsx
  libs/net/dal/Helpers/FfmpegHelper.cs
Labels: bug

#294 TNO-621, 611
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
Labels: bug

#297 Fix kafka consumers
  libs/net/kafka/KafkaListener`.cs
  services/net/content/ContentManager.cs
  services/net/indexing/IndexingManager.cs
  services/net/nlp/NLPManager.cs
  services/net/transcription/TranscriptionManager.cs
Labels: bug

#298 Slight tweak for TNO-611
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
Labels: bug

#299 TNO-639 Fix syndication content without body
  services/net/content/ContentManager.cs
  services/net/nlp/NLPManager.cs
Labels: bug

#300 TNO-639 Fix textarea layout
  app/editor/.yarn/install-state.gz
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
  app/editor/src/features/content/form/styled/ContentSummaryForm.tsx
  app/editor/src/features/content/form/styled/ContentTranscriptForm.tsx
Labels: bug

#301 TNO-610 Fix clip service
  services/net/clip/ClipAction.cs
Labels: bug

#296 Transcription video service
  services/net/transcription/TranscriptionManager.cs
  tools/scripts/db-drop.sh
Labels: enhancement

#303 Update image service
  services/net/image/ImageAction.cs
Labels: bug

#304 Fix Kafka Producers
  app/editor/src/features/admin/ingests/configurations/Audio.tsx
  app/editor/src/features/admin/ingests/configurations/AudioStream.tsx
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/filemonitor/FilemonitorAction.cs
  services/net/image/ImageAction.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#306 Log ffmpeg
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/command/CommandAction`.cs
Labels: enhancement
