Repository bcgov/tno, pull requests merged in 2022-12, with the labels that each got.

#423 TNO-8 Update DevOps for Keycloak Gold
  openshift/kustomize/api/base/config-map.yaml
  openshift/kustomize/api/base/deploy.yaml
  openshift/kustomize/api/base/kustomization.yaml
  openshift/kustomize/api/overlays/dev/kustomization.yaml
  openshift/kustomize/api/overlays/prod/kustomization.yaml
  openshift/kustomize/api/overlays/test/kustomization.yaml
  openshift/kustomize/app/editor/base/config-map.yaml
  openshift/kustomize/app/editor/overlays/dev/kustomization.yaml
  openshift/kustomize/app/editor/overlays/prod/kustomization.yaml
  openshift/kustomize/app/editor/overlays/test/kustomization.yaml
Labels: devops

#424 TNO-8 Fix work orders controller
  api/net/Areas/Admin/Controllers/WorkOrderController.cs
Labels: bug

#425 TNO-8 Reduce security to temporarily enable keycloak gold realm
  api/net/Areas/Admin/Controllers/WorkOrderController.cs
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/LookupController.cs
  api/net/Areas/Kafka/Controllers/ProducerController.cs
  api/net/Areas/Services/Controllers/ConnectionController.cs
  api/net/Areas/Services/Controllers/ContentController.cs
  api/net/Areas/Services/Controllers/ContentReferenceController.cs
  api/net/Areas/Services/Controllers/DataLocationController.cs
  api/net/Areas/Services/Controllers/IngestController.cs
  api/net/Areas/Services/Controllers/SourceController.cs
  api/net/Areas/Services/Controllers/WorkOrderController.cs
Labels: bug

#426 TNO-805 Keycloak Gold realm integration
  libs/net/css/Extensions/ServiceCollectionExtensions.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Runners/BaseService.cs
  libs/net/services/TNO.Services.csproj
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/services/clip/base/deploy.yaml
  openshift/kustomize/services/config-map.yaml
  openshift/kustomize/services/content/base/deploy.yaml
  openshift/kustomize/services/filemonitor/base/deploy.yaml
  openshift/kustomize/services/image/base/deploy.yaml
  openshift/kustomize/services/indexing/base/deploy.yaml
  openshift/kustomize/services/nlp/base/deploy.yaml
  openshift/kustomize/services/syndication/base/deploy.yaml
  openshift/kustomize/services/transcription/base/deploy.yaml
  services/net/capture/appsettings.Development.json
  services/net/capture/appsettings.Staging.json
  services/net/capture/appsettings.json
  services/net/clip/appsettings.Development.json
  services/net/clip/appsettings.Staging.json
  services/net/clip/appsettings.json
  services/net/content/appsettings.Development.json
  services/net/content/appsettings.Staging.json
  services/net/content/appsettings.json
  services/net/filemonitor/appsettings.Development.json
  services/net/filemonitor/appsettings.Staging.json
  services/net/filemonitor/appsettings.json
  services/net/image/appsettings.Development.json
  services/net/image/appsettings.Staging.json
  services/net/image/appsettings.json
  services/net/indexing/appsettings.Development.json
  services/net/indexing/appsettings.Staging.json
  services/net/indexing/appsettings.json
  services/net/nlp/appsettings.Development.json
  services/net/nlp/appsettings.Staging.json
  services/net/nlp/appsettings.json
  services/net/syndication/appsettings.Development.json
  services/net/syndication/appsettings.Staging.json
  services/net/syndication/appsettings.json
  services/net/transcription/appsettings.Development.json
  services/net/transcription/appsettings.Staging.json
  services/net/transcription/appsettings.json
  tools/scripts/gen-env-files.sh
Labels: bug, enhancement, devops

#427 TNO-805 Integrate services with keycloak gold realm
  api/net/Program.cs
  api/net/appsettings.Development.json
  api/net/appsettings.Staging.json
  api/net/appsettings.json
  libs/net/core/Http/OpenIdConnectRequestClient.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Runners/BaseService.cs
  libs/net/services/TNO.Services.csproj
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/services/clip/base/deploy.yaml
  openshift/kustomize/services/config-map.yaml
  openshift/kustomize/services/content/base/deploy.yaml
  openshift/kustomize/services/filemonitor/base/deploy.yaml
  openshift/kustomize/services/image/base/deploy.yaml
  openshift/kustomize/services/indexing/base/deploy.yaml
  openshift/kustomize/services/nlp/base/deploy.yaml
  openshift/kustomize/services/syndication/base/deploy.yaml
  openshift/kustomize/services/transcription/base/deploy.yaml
  services/net/capture/appsettings.Development.json
  services/net/capture/appsettings.Staging.json
  services/net/capture/appsettings.json
  services/net/clip/appsettings.Development.json
  services/net/clip/appsettings.Staging.json
  services/net/clip/appsettings.json
  services/net/content/appsettings.Development.json
  services/net/content/appsettings.Staging.json
  services/net/content/appsettings.json
  services/net/filemonitor/appsettings.Development.json
  services/net/filemonitor/appsettings.Staging.json
  services/net/filemonitor/appsettings.json
  services/net/image/appsettings.Development.json
  services/net/image/appsettings.Staging.json
  services/net/image/appsettings.json
  services/net/indexing/appsettings.Development.json
  services/net/indexing/appsettings.Staging.json
  services/net/indexing/appsettings.json
  services/net/nlp/appsettings.Development.json
  services/net/nlp/appsettings.Staging.json
  services/net/nlp/appsettings.json
  services/net/syndication/appsettings.Development.json
  services/net/syndication/appsettings.Staging.json
  services/net/syndication/appsettings.json
  services/net/transcription/appsettings.Development.json
  services/net/transcription/appsettings.Staging.json
  services/net/transcription/appsettings.json
  tools/scripts/gen-env-files.sh
Labels: bug, enhancement, devops

#428 Fixed TNO-753 (based on the demo feedbacks)
  api/net/Areas/Admin/Controllers/LicenseController.cs
  api/net/Areas/Editor/Controllers/LicenseController.cs
  app/editor/src/features/admin/AdminRouter.tsx
  app/editor/src/features/admin/licenses/LicenseForm.tsx
  app/editor/src/features/admin/licenses/LicenseList.tsx
  app/editor/src/features/navbar/NavBar.tsx
  app/editor/src/hooks/api-editor/admin/useApiAdminLicenses.ts
  app/editor/src/hooks/api-editor/editor/useApiLicenses.ts
Labels: bug, enhancement

#420 TNO-783: Infinite scroll
  app/editor/.yarn/cache/tno-core-npm-0.0.197-a652184346-b6bd688dde.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/yarn.lock
  libs/npm/core/.yarn/install-state.gz
  libs/npm/core/package.json
  libs/npm/core/src/components/grid-table/GridTable.tsx
  libs/npm/core/src/components/grid-table/PagedTable.tsx
Labels: enhancement

#429 TNO-8 Fix approve user
  api/net/Keycloak/CssHelper.cs
  app/editor/src/components/toggle-group/ToggleGroup.tsx
  app/editor/src/features/admin/users/UserForm.tsx
  libs/net/css/CssService.cs
  libs/net/css/Extensions/HttpResponseMessageExtensions.cs
  openshift/kustomize/api/base/config-map.yaml
Labels: bug

#430 Disable infinite table for now
  app/editor/src/features/content/list-view/ContentListView.tsx
Labels: bug

#431 TNO-755 Resolve duplicate content
  api/net/Areas/Services/Controllers/ContentReferenceController.cs
  app/editor/src/App.tsx
  libs/net/css/IdentityProvider.cs
  libs/net/dal/Services/ContentReferenceService.cs
  libs/net/services/Actions/IngestAction.cs
  libs/net/services/Actions/ServiceAction.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Interfaces/IApiService.cs
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/command/CommandAction`.cs
  services/net/content/ContentManager.cs
  services/net/filemonitor/FilemonitorAction.cs
  services/net/image/ImageAction.cs
  services/net/syndication/SyndicationAction.cs
  tools/scripts/gen-env-files.sh
  tools/scripts/gen-maven-files.sh
Labels: bug

#434 TNO-792 Fix ingest services
  libs/net/core/Http/HttpRequestClient.cs
  libs/net/core/Http/OpenIdConnectRequestClient.cs
  libs/net/services/Helpers/ApiService.cs
Labels: bug

#435 Fixed TNO-808
  app/editor/src/features/content/tool-bar/sections/CreateNewSection.tsx
Labels: enhancement

#436 Fix styling bug for WYSIWYG
  app/editor/src/components/form/wysiwyg/CustomToolbar.tsx
  app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
Labels: bug

#437 Fixed TNO-337
  app/editor/src/features/content/form/ContentForm.tsx
Labels: enhancement

#439 TNO-697 Update SignalR
  api/net/Areas/Admin/Controllers/WorkOrderController.cs
  api/net/Areas/Editor/Controllers/WorkOrderController.cs
  api/net/Areas/Services/Controllers/WorkOrderController.cs
  api/net/Config/SIgnalROptions.cs
  api/net/Program.cs
  api/net/SignalR/WorkOrderHub.cs
  api/net/appsettings.Development.json
  api/net/appsettings.Staging.json
  api/net/appsettings.json
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/WorkOrderStatus.tsx
  app/editor/src/features/content/form/utils/index.ts
  app/editor/src/features/content/form/utils/isWorkOrderStatus.ts
  app/editor/src/features/content/index.ts
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
  app/editor/src/features/content/utils/findWorkOrder.ts
  app/editor/src/features/content/utils/index.ts
  app/editor/src/features/content/utils/isWorkOrderStatus.ts
  app/editor/src/hooks/api-editor/constants/HubMethodName.ts
  app/editor/src/hooks/api-editor/constants/index.ts
  app/editor/src/hooks/api-editor/editor/index.ts
  app/editor/src/hooks/api-editor/editor/useApiHub.ts
  app/editor/src/hooks/api-editor/editor/useApiHubConnection.ts
  app/editor/src/store/hooks/app/useApp.ts
  app/editor/src/store/hooks/editor/useContent.ts
  app/editor/src/store/hooks/useAjaxWrapper.ts
  app/editor/src/store/slices/app/appSlice.ts
  app/editor/src/store/slices/app/useAppStore.ts
  services/net/capture/appsettings.Development.json
  services/net/capture/appsettings.Staging.json
  services/net/content/appsettings.Development.json
  services/net/content/appsettings.Staging.json
  services/net/nlp/Config/NLPOptions.cs
  tools/scripts/purge-folders.sh
Labels: bug, enhancement

#440 TNO-792 Fix Content service
  app/editor/src/features/content/form/WorkOrderStatus.tsx
  libs/net/kafka/KafkaListener`.cs
  services/net/content/ContentManager.cs
  tools/scripts/gen-env-files.sh
Labels: bug

#438 Fixed TNO-761
  app/editor/src/components/form/wysiwyg/CustomToolbar.tsx
  app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
  app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx
  app/editor/src/components/modal/styled/Modal.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: enhancement

#441 TNO-815 Fix keycloak gold
  api/net/Controllers/AuthController.cs
  api/net/Keycloak/CssHelper.cs
Labels: bug

#445 TNO-815 (a minor update)
  libs/net/core/Http/HttpRequestClient.cs
Labels: bug

#442 Fixed TNO-810
  app/editor/.yarn/cache/@bcgov-bc-sans-npm-1.0.1-fbde31a79a-88c820e9f1.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/css/_fonts.scss
  app/editor/src/index.scss
  app/editor/src/index.tsx
  app/editor/yarn.lock
  app/subscriber/src/index.scss
  libs/npm/core/src/css/_variables.scss
  libs/npm/core/src/index.scss
  network/nginx/html/css/maintenance.css
Labels: bug

#446 Allow user to have no email
  api/net/Keycloak/CssHelper.cs
  libs/net/core/Http/OpenIdConnectRequestClient.cs
Labels: bug

#450 TNO-809: Column alignments
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
Labels: bug

#451 TNO-812: Paragraph spacing
  app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
Labels: bug

#448 Fixed TNO-761 #2
  app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
  app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx
  app/editor/src/components/modal/Modal.tsx
  app/editor/src/components/modal/styled/Modal.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: enhancement

#454 Fixed TNO-873
  app/editor/src/components/form/wysiwyg/CustomToolbar.tsx
Labels: bug, enhancement

#455 Fixed TNO-878
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug

#456 Fixed TNO-837
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug, enhancement

#457 Fixed TNO-864
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#458 Fixed TNO-826
  app/editor/src/features/content/form/constants/defaultFormValues.ts
Labels: bug

#459 Added tooltips to wysiwyg editor toolbar
  app/editor/src/components/form/wysiwyg/CustomToolbar.tsx
Labels: enhancement

#461 Fix ingest sorting by Enabled flag
  app/editor/src/features/admin/ingests/constants/columns.tsx
Labels: bug
