Repository bcgov/tno, pull requests merged in 2022-04, with the labels that each got.

#83 TNO-197 Update error handling
  app/editor/src/features/admin/sources/DataSource.tsx
  app/editor/src/features/login/UserInfo.tsx
  app/editor/src/store/hooks/app/useToastError.ts
Labels: bug, enhancement

#84 Tno 273
  libs/java/service/src/main/java/ca/bc/gov/tno/services/handlers/ErrorHandler.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/handlers/FetchDataService.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/kafka/KafkaAudioProducer.java
  services/syndication/src/main/java/ca/bc/gov/tno/services/syndication/handlers/FetchDataService.java
  services/syndication/src/main/java/ca/bc/gov/tno/services/syndication/handlers/KafkaSyndicationProducer.java
Labels: enhancement

#86 TNO-281 Fixing API
  .vscode/settings.json
  api/net/Controllers/AuthController.cs
  api/net/Dockerfile
  api/net/Program.cs
  api/net/TNO.API.csproj
  api/net/entrypoint.sh
  app/editor/src/hooks/api-editor/auth/useApiAuth.ts
  db/postgres/scripts/grant-permission.sql
  docker-compose.yml
  libs/net/core/Extensions/IdentityExtensions.cs
  libs/net/dal/TNOContext.cs
  libs/net/entities/AuditColumns.cs
  libs/net/entities/Interfaces/ISaveChanges.cs
  libs/net/entities/TNO.Entities.csproj
  network/nginx/config/default.conf
  openshift/templates/api/deploy.yaml
  openshift/templates/app/deploy.yaml
  tools/scripts/gen-env-files.sh
Labels: bug, devops

#88 TNO-283 Updated service config
  openshift/templates/services/audio/capture/deploy.yaml
  openshift/templates/services/audio/pvc.yaml
  openshift/templates/services/config.yaml
  services/audio/src/main/resources/application.yml
  services/capture/src/main/resources/application.yml
  services/nlp/src/main/resources/application.yml
  services/syndication/src/main/resources/application.yml
Labels: bug

#89 Fix login URL
  app/editor/src/features/login/LoginPanel.tsx
Labels: bug

#90 PSP-289: Update timelog to state variable
  app/editor/src/features/content/form/PropertiesContentForm.tsx
Labels: bug

#91 Update readme
  README.md
Labels: documentation

#92 TNO-297 Change logo URL
  app/editor/.devcontainer/devcontainer.json
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/App.tsx
  app/editor/src/components/form/checkbox/CheckboxGroup.tsx
  app/editor/src/components/form/radio/RadioGroup.tsx
  app/editor/src/components/formik/form/FormikForm.tsx
  app/editor/src/components/formik/form/styled/FormikForm.tsx
  app/editor/src/components/header/Header.tsx
  app/editor/src/components/layout/DefaultLayout.tsx
  app/editor/src/components/layout/LayoutErrorBoundary.tsx
  app/editor/src/components/layout/styled/Layout.tsx
  app/editor/src/components/modal/Modal.tsx
  app/editor/src/components/spinner/Spinner.tsx
  app/editor/src/components/spinner/SpinnerStyled.tsx
  app/editor/src/components/spinner/index.ts
  app/editor/src/features/admin/sources/schedules/constants/scheduleColumns.tsx
  app/editor/src/features/content/form/PropertiesContentForm.tsx
  app/editor/src/features/content/form/constants/timeLogColumns.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
  app/editor/src/features/login/UserInfo.tsx
  app/editor/src/features/router/AppRouter.tsx
  app/editor/yarn.lock
  libs/net/dal/Extensions/DbContextExtensions.cs
  libs/net/dal/Extensions/EntityEntryExtensions.cs
  libs/net/dal/TNOContext.cs
  libs/net/entities/AuditColumns.cs
  libs/npm/core/package.json
  libs/npm/core/src/components/spinners/Loader.tsx
  libs/npm/core/src/components/spinners/index.ts
  libs/npm/core/src/components/spinners/styled/Loader.tsx
  libs/npm/core/src/components/spinners/styled/Loading.tsx
  libs/npm/core/src/components/spinners/styled/Spinner.tsx
  libs/npm/core/src/components/spinners/styled/index.ts
Labels: bug, enhancement

#93 Bug Fixes and UI Improvements
  api/net/Areas/Services/Controllers/DataSourceController.cs
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/App.tsx
  app/editor/src/components/form/area/styled/Area.tsx
  app/editor/src/components/form/radio/RadioGroup.tsx
  app/editor/src/components/form/radio/styled/RadioGroup.tsx
  app/editor/src/components/header/Header.tsx
  app/editor/src/components/header/styled/index.ts
  app/editor/src/components/layout/DefaultLayout.tsx
  app/editor/src/components/layout/LayoutAnonymous.tsx
  app/editor/src/components/layout/styled/Layout.tsx
  app/editor/src/components/upload/styled/Upload.tsx
  app/editor/src/features/content/form/PropertiesContentForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/constants/defaultPage.ts
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
  app/editor/src/features/home/styled/InfoPanelStyled.tsx
  app/editor/src/features/navbar/NavBar.tsx
  app/editor/src/index.scss
  app/editor/src/store/hooks/content/useContent.ts
  app/editor/src/store/slices/content/contentSlice.ts
  app/editor/src/store/slices/content/interfaces/IContentState.ts
  app/editor/src/store/slices/content/useContentStore.ts
  app/editor/yarn.lock
  libs/net/dal/Services/ContentService.cs
  libs/npm/core/package.json
  libs/npm/core/src/components/grid-table/GridTable.tsx
  libs/npm/core/src/components/header/Header.tsx
  libs/npm/core/src/components/header/HeaderStyled.tsx
  libs/npm/core/src/components/header/styled/Header.tsx
  libs/npm/core/src/components/header/styled/index.ts
  libs/npm/core/src/components/index.ts
  libs/npm/core/src/components/layout/Layout.tsx
  libs/npm/core/src/components/layout/LayoutAnonymous.tsx
  libs/npm/core/src/components/layout/LayoutStyled.tsx
  libs/npm/core/src/components/layout/index.ts
  libs/npm/core/src/components/loading/Loading.tsx
  libs/npm/core/src/components/navbar/NavBarGroup.tsx
  libs/npm/core/src/components/navbar/styled/NavBarGroup.tsx
  libs/npm/core/src/components/navbar/styled/NavBarItem.tsx
  libs/npm/core/src/components/section/Section.tsx
  libs/npm/core/yarn.lock
Labels: bug, enhancement

#94 TNO-299 Fix API
  api/net/Middleware/ErrorHandlingMiddleware.cs
  libs/net/core/Exceptions/AuthenticationException.cs
Labels: bug, enhancement

#95 Update Kafka Broker and Audio Connection Config
  app/editor/.yarn/install-state.gz
  app/editor/src/features/admin/sources/DataSourceDetails.tsx
  app/editor/src/features/admin/sources/DataSourceStatus.tsx
  app/editor/src/features/admin/sources/media-types/Audio.tsx
  db/kafka/broker/Dockerfile.rhel
  openshift/templates/kafka/broker/deploy.yaml
  openshift/templates/services/audio/pvc.yaml
Labels: enhancement

#96 PSP-268: Time Input Mask
  app/editor/package.json
  app/editor/src/components/form/index.ts
  app/editor/src/components/form/timeinput/TimeInput.tsx
  app/editor/src/components/form/timeinput/index.ts
  app/editor/src/components/form/timeinput/styled/TimeInput.tsx
  app/editor/src/components/form/timeinput/styled/index.ts
  app/editor/src/features/admin/sources/schedules/ScheduleSingle.tsx
  app/editor/yarn.lock
Labels: enhancement

#98 TNO-214: React tooltip fix
  app/editor/src/App.tsx
Labels: bug

#97 TNO-295 Fix date format
  app/editor/.yarn/install-state.gz
  app/editor/src/features/content/form/PropertiesContentForm.tsx
  db/kafka/broker/Dockerfile
Labels: bug

#99 TNO-267: Page size consistency
  app/editor/src/components/form/area/styled/Area.tsx
  app/editor/src/components/form/formpage/FormPage.tsx
  app/editor/src/components/form/formpage/index.ts
  app/editor/src/components/form/formpage/styled/FormPage.tsx
  app/editor/src/components/form/formpage/styled/index.ts
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
Labels: bug

#100 TNO-214: React tooltip fix adjustment
  app/editor/src/App.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
Labels: bug

#102 Rename DataSource.ScheduleType
  libs/net/dal/Migrations/20220421130605_Initial.Designer.cs
  libs/net/dal/Migrations/20220421130605_Initial.cs
  libs/net/dal/Migrations/TNOContextModelSnapshot.cs
  libs/net/entities/DataSource.cs
Labels: DB Migration

#104 Fix api data source with parent
  api/net/Areas/Services/Models/DataSource/DataSourceModel.cs
Labels: bug

#105 Fix build error I introduced
  api/net/Areas/Services/Models/DataSource/DataSourceModel.cs
Labels: bug

#106 Fix service run config error
  services/audio/pom.xml
  services/capture/pom.xml
  services/elastic/pom.xml
  services/nlp/pom.xml
  services/syndication/pom.xml
Labels: bug

#107 TNO-318 Refactor CBRA Report
  api/net/.devcontainer/Dockerfile
  api/net/Areas/Reports/Controllers/CBRAController.cs
  api/net/Dockerfile
  api/net/Dockerfile.ocp
  api/net/TNO.API.csproj
  libs/net/TNO.sln
  libs/net/dal/Services/ActionService.cs
  libs/net/dal/Services/Interfaces/IActionService.cs
  libs/net/dal/Services/Interfaces/ITimeTrackingService.cs
  libs/net/dal/Services/TimeTrackingService.cs
  libs/net/reports/CBRAReport.cs
  libs/net/reports/TNO.Reports.csproj
Labels: bug, enhancement

#110 TNO-277 Fix content form ui
  app/editor/src/components/formik/select/styled/FormikSelect.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/PropertiesContentForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
Labels: bug

#111 TNO-226 Migrate to CrunchyDB
  .vscode/settings.json
  openshift/Makefile
  openshift/kustomize/README.md
  openshift/kustomize/postgres/crunchy/README.md
  openshift/kustomize/postgres/crunchy/base/deploy.yaml
  openshift/kustomize/postgres/crunchy/base/kustomization.yaml
  openshift/kustomize/postgres/crunchy/base/network.yaml
  openshift/kustomize/postgres/crunchy/base/role.yaml
  openshift/kustomize/postgres/crunchy/overlays/dev/deploy.yaml
  openshift/kustomize/postgres/crunchy/overlays/dev/kustomization.yaml
  openshift/kustomize/postgres/crunchy/overlays/prod/deploy.yaml
  openshift/kustomize/postgres/crunchy/overlays/prod/kustomization.yaml
  openshift/kustomize/postgres/crunchy/overlays/test/deploy.yaml
  openshift/kustomize/postgres/crunchy/overlays/test/kustomization.yaml
  openshift/kustomize/postgres/monitor/README.md
  openshift/kustomize/postgres/monitor/grafana-config.yaml
  openshift/kustomize/postgres/monitor/grafana-netpol.yaml
  openshift/kustomize/postgres/monitor/grafana-oauth.yaml
  openshift/kustomize/postgres/monitor/grafana-route.yaml
  openshift/kustomize/postgres/monitor/kustomization.yaml
  openshift/scripts/database-connect.sh
  openshift/templates/api/deploy.yaml
  openshift/templates/elastic/cluster/deploy.yaml
  openshift/templates/postgres/crunchy/deploy.yaml
  openshift/templates/postgres/crunchy/monitor/kustomization.yaml
  openshift/templates/postgres/crunchy/network-policy.yaml
  openshift/templates/postgres/crunchy/role-binding.yaml
  openshift/templates/tekton/pipelines/complete.yaml
  openshift/templates/tekton/pipelines/db-migration.yaml
  openshift/templates/tekton/pipelines/deploy.yaml
  openshift/templates/tekton/tasks/db-migration.yaml
Labels: devops

#108 Code changes to support api based data access
  app/editor/src/features/admin/sources/media-types/Audio.tsx
  db/kafka/migrations/U1.0.0.sh
  db/kafka/migrations/V1.0.0.sh
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/config/DataSourceConfig.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/models/DataSource.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/models/Schedule.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/config/AudioConfig.java
  services/audio/src/main/java/ca/bc/gov/tno/services/audio/handlers/ScheduledService.java
  services/audio/src/main/resources/application.yml
  services/capture/src/main/java/ca/bc/gov/tno/services/capture/config/CaptureConfig.java
  services/capture/src/main/java/ca/bc/gov/tno/services/capture/handlers/FetchDataService.java
  services/capture/src/main/java/ca/bc/gov/tno/services/capture/handlers/ScheduledService.java
  services/capture/src/main/resources/application.yml
Labels: bug, enhancement
