Repository bcgov/tno, pull requests merged in 2022-07, with the labels that each got.

#185 TNO-45 Update error handling
  .github/workflows/java-editor.yml
  .github/workflows/net-libs.yml
  api/net/Middleware/ErrorHandlingMiddleware.cs
  app/editor/.yarn/cache/tno-core-npm-0.0.156-4e2aca3e63-8494017544.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.157-b646c43d8e-5513167797.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/admin/sources/DataSourceForm.tsx
  app/editor/src/features/admin/users/UserForm.tsx
  app/editor/yarn.lock
  docs/DEVELOPMENT.md
  libs/net/TNO.sln
  libs/net/entities/Action.cs
  libs/net/entities/AuditColumns.cs
  libs/net/entities/BaseType`.cs
  libs/net/entities/Category.cs
  libs/net/entities/Tag.cs
  libs/net/models/ErrorResponseModel.cs
  libs/net/tests/README.md
  libs/net/tests/dal/TNO.Test.DAL.csproj
  libs/net/tests/dal/UnitTest1.cs
  libs/net/tests/dal/Usings.cs
  libs/net/tests/dal/coverlet.runsettings
  libs/net/tests/entities/ActionTest.cs
  libs/net/tests/entities/CacheTest.cs
  libs/net/tests/entities/CategoryTest.cs
  libs/net/tests/entities/ContentTypeTest.cs
  libs/net/tests/entities/DataLocationTest.cs
  libs/net/tests/entities/LicenseTest.cs
  libs/net/tests/entities/MediaTypeTest.cs
  libs/net/tests/entities/SeriesTest.cs
  libs/net/tests/entities/TNO.Test.Entities.csproj
  libs/net/tests/entities/TagTest.cs
  libs/net/tests/entities/Usings.cs
  libs/net/tests/entities/coverlet.runsettings
  libs/npm/core/Makefile
  libs/npm/core/package.json
  libs/npm/core/scripts/package.sh
  libs/npm/core/src/components/tabs/Tab.tsx
  libs/npm/core/src/components/tabs/styled/Tab.tsx
Labels: enhancement

#186 TNO-155 Add Unit Tests
  libs/net/tests/dal/Models/ContentFileReferenceTest.cs
  libs/net/tests/dal/TNO.Test.DAL.csproj
Labels: unit tests

#190 TNO-154 Add Unit Tests
  .github/workflows/net-libs.yml
  libs/net/TNO.sln
  libs/net/tests/core/MoqHelper.cs
  libs/net/tests/dal/Services/ActionServiceTest.cs
  libs/net/tests/services/Controllers/HealthControllerTest.cs
  libs/net/tests/services/ServiceStateTest.cs
  libs/net/tests/services/TNO.Test.Services.csproj
  libs/net/tests/services/Usings.cs
  libs/net/tests/services/coverlet.runsettings
Labels: unit tests

#191 Functioning CP News syndication service
  app/editor/src/features/admin/sources/connections/Syndication.tsx
  libs/net/core/Extensions/StringExtensions.cs
  services/net/syndication/SyndicationAction.cs
Labels: enhancement

#193 TNO-390: Combined View Bugs
  app/editor/src/features/content/combined-view/ListViewPanel.tsx
  app/editor/src/features/content/form/CondensedContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/TimeLogTable.tsx
  app/editor/src/features/content/list-view/ContentFilter.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
Labels: bug

#197 TNO-374: Get rid of duplicate data sources
  libs/net/dal/Services/DataSourceService.cs
Labels: bug

#200 TNO-392 Fixing Ingest Services
  services/net/capture/appsettings.json
  services/net/clip/appsettings.json
  services/net/command/TNO.Services.Command.csproj
  services/net/command/appsettings.Development.json
  services/net/command/appsettings.Staging.json
  services/net/command/appsettings.json
Labels: bug

#196 TNO-381 Ingest Service Timezone Bugs
  libs/net/services/Actions/Managers/DataSourceIngestManager`.cs
Labels: bug
