Repository bcgov/tno, pull requests merged in 2022-02, with the labels that each got.

#43 Navigation bar fix / Sign out fix
  app/editor/src/App.tsx
  app/editor/src/components/col/Col.tsx
  app/editor/src/components/col/ColStyled.tsx
  app/editor/src/components/col/index.ts
  app/editor/src/components/header/Header.tsx
  app/editor/src/components/header/HeaderStyled.tsx
  app/editor/src/components/header/index.ts
  app/editor/src/components/index.ts
  app/editor/src/components/layout/Layout.tsx
  app/editor/src/components/navbar/NavBar.tsx
  app/editor/src/components/navbar/NavBarGroup.tsx
  app/editor/src/components/navbar/NavBarItem.tsx
  app/editor/src/components/navbar/NavBarItemStyled.tsx
  app/editor/src/components/navbar/NavBarStyled.tsx
  app/editor/src/components/navbar/index.tsx
  app/editor/src/components/row/Row.tsx
  app/editor/src/components/row/RowStyled.tsx
  app/editor/src/components/row/index.ts
  app/editor/src/css/_fonts.scss
  app/editor/src/css/_variables.module.scss
Labels: bug

#45 TNO-69 Fix dropdown values
  app/editor/src/features/content/list-view/constants/fieldTypes.ts
Labels: bug

#46 TNO-136 Syndication Service
  Makefile
  api/editor/.devcontainer/devcontainer.json
  db/kafka/docker-compose.yml
  db/postgres/scripts/grant-permission.sql
  docker-compose.yml
  libs/java/core/.devcontainer/devcontainer.json
  libs/java/dal/db/.devcontainer/devcontainer.json
  libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/V1__Init.sql
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentReference.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSourceSchedulePK.java
  libs/java/dal/elastic/.devcontainer/devcontainer.json
  libs/java/service/.devcontainer/devcontainer.json
  libs/java/service/pom.xml
  libs/java/service/src/main/java/ca/bc/gov/tno/services/config/KeycloakConfig.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/config/SecurityConfig.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/BaseDbScheduleService.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/BaseScheduleService.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/ScheduleHelper.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/config/DataSourceConfig.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/config/ScheduleConfig.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/events/TransactionBeginEvent.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/events/TransactionCompleteEvent.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/kafka/BaseKafkaConsumerService.java
  openshift/Makefile
  openshift/README.md
  openshift/scripts/database-connect.sh
  openshift/templates/tekton/pipelines/deploy.yaml
  openshift/templates/tekton/tasks/db-migration.yaml
  services/audio/.devcontainer/devcontainer.json
  services/audio/pom.xml
  services/audio/src/main/resources/application.yml
  services/docker-compose.yml
  services/elastic/.devcontainer/devcontainer.json
  services/nlp/.devcontainer/devcontainer.json
  services/syndication/.devcontainer/devcontainer.json
  services/syndication/.vscode/launch.json
  services/syndication/pom.xml
  services/syndication/src/main/java/ca/bc/gov/tno/services/syndication/SyndicationServiceApp.java
  services/syndication/src/main/java/ca/bc/gov/tno/services/syndication/events/ProducerSendEvent.java
  services/syndication/src/main/java/ca/bc/gov/tno/services/syndication/handlers/FetchDataService.java
  services/syndication/src/main/java/ca/bc/gov/tno/services/syndication/handlers/KafkaSyndicationProducer.java
  services/syndication/src/main/java/ca/bc/gov/tno/services/syndication/handlers/ScheduledService.java
  services/syndication/src/main/resources/application.yml
  tools/scripts/gen-env-files.sh
Labels: bug, enhancement, DB Migration

#49 TNO-136 Fix hibernate concurrency
  Makefile
  api/editor/api-editor/pom.xml
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/admin/controllers/ScheduleController.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/controllers/ContentController.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/ContentModel.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/DataSourceModel.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/LicenseModel.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/MediaTypeModel.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/ScheduleModel.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/SeriesModel.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/areas/editor/models/UserModel.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/controllers/HealthController.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/controllers/HomeController.java
  api/editor/api-editor/src/main/java/ca/bc/gov/tno/models/AuditColumnModel.java
  api/editor/api-editor/src/main/resources/application.yml
  db/kafka/scripts/topic-add.sh
  libs/java/dal/db/dal-db-migration/pom.xml
  libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/U1__Init.sql
  libs/java/dal/db/dal-db-migration/src/main/resources/db/migration/V1__Init.sql
  libs/java/dal/db/dal-db-test/pom.xml
  libs/java/dal/db/dal-db-test/src/main/java/ca/bc/gov/tno/dal/db/App.java
  libs/java/dal/db/dal-db-test/src/main/java/ca/bc/gov/tno/dal/db/ContentReferenceTest.java
  libs/java/dal/db/dal-db-test/src/main/java/ca/bc/gov/tno/dal/db/ContentTest.java
  libs/java/dal/db/dal-db-test/src/main/java/ca/bc/gov/tno/dal/db/ScheduleTest.java
  libs/java/dal/db/dal-db/pom.xml
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/AuditColumns.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/converters/LocalDateTimeConverter.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/converters/ZonedDateTimeConverter.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Content.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentReference.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/ContentReferencePK.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSource.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/DataSourceSchedulePK.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/Schedule.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/TimeTrackingPK.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/entities/User.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/DataSourceService.java
  libs/java/dal/db/dal-db/src/main/java/ca/bc/gov/tno/dal/db/services/Settings.java
  libs/java/service/pom.xml
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/BaseDbScheduleService.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/BaseScheduleService.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/ScheduleHelper.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/config/DataSourceConfig.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/config/ScheduleConfig.java
  openshift/templates/services/syndication/deploy.yaml
  openshift/templates/tekton/pipelines/db-migration.yaml
  services/syndication/pom.xml
  services/syndication/src/main/java/ca/bc/gov/tno/services/syndication/handlers/KafkaSyndicationProducer.java
  services/syndication/src/main/resources/application.yml
Labels: bug, enhancement, DB Migration

#51 WIP TNO-182 / Styling
  app/editor/public/assets/back_arrow.svg
  app/editor/src/components/button/ButtonStyled.tsx
  app/editor/src/components/button/ButtonVariant.ts
  app/editor/src/components/form/area/Area.tsx
  app/editor/src/components/form/area/AreaStyled.tsx
  app/editor/src/components/form/area/index.ts
  app/editor/src/components/form/checkbox/CheckboxStyled.tsx
  app/editor/src/components/form/datepicker/SelectDate.tsx
  app/editor/src/components/form/datepicker/SelectDateStyled.tsx
  app/editor/src/components/form/dropdown/Dropdown.tsx
  app/editor/src/components/form/dropdown/DropdownStyled.tsx
  app/editor/src/components/form/index.ts
  app/editor/src/components/form/radio/RadioGroup.tsx
  app/editor/src/components/form/radio/RadioStyled.tsx
  app/editor/src/components/form/radio/SpanStyled.tsx
  app/editor/src/components/form/radio/StyledDiv.tsx
  app/editor/src/components/form/text/TextStyled.tsx
  app/editor/src/components/form/text/TextVariant.ts
  app/editor/src/components/formik/checkbox/FormikCheckbox.tsx
  app/editor/src/components/formik/checkbox/FormikCheckboxStyled.tsx
  app/editor/src/components/formik/dropdown/FormikDropdown.tsx
  app/editor/src/components/formik/text/FormikText.tsx
  app/editor/src/components/grid-table/GridTableStyled.tsx
  app/editor/src/components/layout/Layout.tsx
  app/editor/src/components/layout/LayoutStyled.tsx
  app/editor/src/components/tabs/Tab.tsx
  app/editor/src/components/tabs/TabContainer.tsx
  app/editor/src/components/tabs/TabContainerStyled.tsx
  app/editor/src/components/tabs/TabStyled.tsx
  app/editor/src/components/tabs/index.ts
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/IContentForm.tsx
  app/editor/src/features/content/form/PropertiesContentForm.tsx
  app/editor/src/features/content/form/TranscriptContentForm.tsx
  app/editor/src/features/content/form/constants/expireOptions.ts
  app/editor/src/features/content/form/constants/index.ts
  app/editor/src/features/content/form/constants/summaryOptions.ts
  app/editor/src/features/content/form/constants/toningOptions.ts
  app/editor/src/features/content/form/contentFormUtils.ts
  app/editor/src/features/content/form/index.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/ContentListViewStyled.tsx
  app/editor/src/hooks/api-editor/interfaces/IContentApi.ts
  app/editor/src/hooks/api-editor/interfaces/index.ts
  app/editor/src/hooks/api-editor/useApiEditor.ts
  app/editor/src/index.scss
Labels: enhancement

#52 TNO-210 Fix JWT Refresh Bug
  app/editor/package.json
  app/editor/src/App.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/makeFilter.ts
  app/editor/src/index.tsx
  app/editor/src/utils/index.ts
  app/editor/src/utils/interfaces/index.ts
  app/editor/yarn.lock
  libs/npm/core/package.json
  libs/npm/core/src/hooks/keycloak/createKeycloakInstance.ts
  libs/npm/core/src/hooks/keycloak/index.ts
  libs/npm/core/src/hooks/keycloak/interfaces/IKeycloakConfig.ts
  libs/npm/core/src/hooks/keycloak/interfaces/index.ts
  libs/npm/core/src/hooks/keycloak/useKeycloakEventHandler.ts
  libs/npm/core/src/hooks/summon/useSummon.tsx
  libs/npm/core/src/utils/createKeycloakInstance.ts
  libs/npm/core/src/utils/index.ts
  libs/npm/core/src/utils/interfaces/IKeycloakConfig.ts
  libs/npm/core/src/utils/interfaces/index.ts
  openshift/templates/tekton/triggers/git-eventlistener.yaml
Labels: bug
