Repository bcgov/tno, pull requests merged in 2022-06, with the labels that each got.

#154 TNO-341: Input sizing
  app/editor/src/components/form/checkbox/styled/CheckboxField.tsx
  app/editor/src/components/form/datepicker/styled/SelectDate.tsx
  app/editor/src/components/form/radio/styled/Radio.tsx
  app/editor/src/components/form/text/styled/TextField.tsx
  app/editor/src/components/form/textarea/styled/TextAreaField.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#157 NTO-213 Fixing bugs
  libs/net/services/Managers/DataSourceManager`.cs
  openshift/kustomize/api/base/config-map.yaml
Labels: bug, devops

#158 TNO-213 Fix Keycloak
  api/net/Keycloak/KeycloakHelper.cs
  auth/keycloak/config/realm-export.json
  libs/net/services/Config/ServiceOptions.cs
  openshift/kustomize/services/syndication/base/deploy.yaml
  services/net/capture/appsettings.Development.json
  services/net/capture/appsettings.Staging.json
  services/net/capture/appsettings.json
  services/net/clip/appsettings.Development.json
  services/net/clip/appsettings.Staging.json
  services/net/clip/appsettings.json
  services/net/command/appsettings.Development.json
  services/net/command/appsettings.Staging.json
  services/net/command/appsettings.json
  services/net/content/appsettings.Development.json
  services/net/content/appsettings.Staging.json
  services/net/content/appsettings.json
  services/net/nlp/appsettings.Development.json
  services/net/nlp/appsettings.Staging.json
  services/net/nlp/appsettings.json
  services/net/syndication/appsettings.Development.json
  services/net/syndication/appsettings.Staging.json
  services/net/syndication/appsettings.json
Labels: bug

#160 Fix bugs
  app/editor/src/features/admin/sources/DataSourceStatus.tsx
  app/editor/src/utils/formatIdir.ts
  openshift/kustomize/kafka/broker/base/statefulset.yaml
  openshift/kustomize/kafka/broker/overlays/dev/kustomization.yaml
  openshift/kustomize/kafka/broker/overlays/prod/kustomization.yaml
  openshift/kustomize/kafka/broker/overlays/test/kustomization.yaml
  tools/scripts/gen-env-files.sh
Labels: bug, devops

#162 Reduce log chatter
  services/net/capture/appsettings.Development.json
  services/net/capture/appsettings.Staging.json
  services/net/capture/appsettings.json
  services/net/clip/appsettings.Development.json
  services/net/clip/appsettings.Staging.json
  services/net/clip/appsettings.json
  services/net/command/appsettings.Development.json
  services/net/command/appsettings.Staging.json
  services/net/command/appsettings.json
  services/net/content/appsettings.Development.json
  services/net/content/appsettings.Staging.json
  services/net/content/appsettings.json
  services/net/nlp/appsettings.Development.json
  services/net/nlp/appsettings.Staging.json
  services/net/nlp/appsettings.json
  services/net/syndication/appsettings.Development.json
  services/net/syndication/appsettings.Staging.json
  services/net/syndication/appsettings.json
Labels: devops

#164 TNO-378 Fix syndication feed dates
  api/net/appsettings.Development.json
  api/net/appsettings.Staging.json
  api/net/appsettings.json
  libs/net/core/Extensions/StringExtensions.cs
  libs/net/services/Config/ServiceOptions.cs
  services/net/capture/appsettings.json
  services/net/clip/appsettings.json
  services/net/command/appsettings.json
  services/net/content/appsettings.json
  services/net/nlp/appsettings.json
  services/net/syndication/SyndicationAction.cs
  services/net/syndication/Xml/Rss/RssChannel.cs
  services/net/syndication/Xml/Rss/RssFeed.cs
  services/net/syndication/Xml/Rss/RssItem.cs
  services/net/syndication/appsettings.json
Labels: bug

#165 TNO-342 Add Storage Controller
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Areas/Editor/Models/Storage/FolderModel.cs
  api/net/Areas/Editor/Models/Storage/ItemModel.cs
  api/net/Dockerfile
  api/net/TNO.API.csproj
  api/net/appsettings.json
  app/editor/.yarn/install-state.gz
  app/editor/src/components/upload/Upload.tsx
  app/editor/src/features/navbar/NavBar.tsx
  app/editor/src/features/router/AppRouter.tsx
  app/editor/src/features/storage/StorageListView.tsx
  app/editor/src/features/storage/constants/defaultFolder.ts
  app/editor/src/features/storage/constants/index.ts
  app/editor/src/features/storage/index.ts
  app/editor/src/features/storage/styled/StorageListView.tsx
  app/editor/src/features/storage/styled/index.ts
  app/editor/src/hooks/api-editor/editor/index.ts
  app/editor/src/hooks/api-editor/editor/useApiStorage.ts
  app/editor/src/hooks/api-editor/interfaces/IFolderModel.ts
  app/editor/src/hooks/api-editor/interfaces/IItemModel.ts
  app/editor/src/hooks/api-editor/interfaces/index.ts
  app/editor/src/store/hooks/index.ts
  app/editor/src/store/hooks/storage/index.ts
  app/editor/src/store/hooks/storage/useStorage.ts
  app/editor/src/utils/extractFileName.ts
  app/editor/src/utils/index.ts
  docker-compose.yml
  libs/net/core/Extensions/StringExtensions.cs
  libs/net/dal/Config/StorageConfig.cs
  libs/net/dal/Extensions/FileReferenceExtensions.cs
  openshift/kustomize/api/base/deploy.yaml
  services/docker-compose.yml
  services/net/capture/CaptureAction.cs
  tools/scripts/gen-env-files.sh
Labels: enhancement

#166 TNO-342 Fix storage bug
  api/net/Areas/Editor/Models/Storage/FolderModel.cs
  app/editor/src/features/storage/StorageListView.tsx
  libs/net/core/Extensions/StringExtensions.cs
Labels: bug

#167 TNO-342 Fix stream bug
  api/net/Areas/Editor/Controllers/StorageController.cs
  app/editor/src/features/admin/sources/DataSourceDetails.tsx
  app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx
  app/editor/src/features/storage/StorageListView.tsx
Labels: bug

#172 TNO-356 Fix Clip Service
  libs/net/services/Actions/IngestAction.cs
  libs/net/services/Actions/Managers/ServiceActionManager`.cs
  libs/net/services/Actions/ServiceAction.cs
  libs/net/services/Interfaces/IIngestAction`.cs
  libs/net/services/Interfaces/IServiceAction`.cs
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/clip/ClipDataSourceManager.cs
  services/net/command/CommandAction`.cs
  services/net/nlp/NLPAction.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#173 TNO-345: Default sort on name not abbreviation
  app/editor/src/features/admin/sources/DataSourceLists.tsx
Labels: enhancement

#170 Added contents/stream endpoint
  api/net/Areas/Editor/Controllers/ContentController.cs
Labels: enhancement

#176 Fix data source admin
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx
Labels: bug

#171 First implementation of audio/video preview for snippet form
  app/editor/src/components/upload/Upload.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
  app/editor/src/features/content/form/styled/ContentSummaryForm.tsx
  app/editor/src/features/content/form/styled/index.ts
Labels: enhancement

#179 Fixed the issue where maintenance page doesn't handle paths
  network/nginx/html/index.html
Labels: bug

#181 TNO-386 Add Purge Service
  openshift/kustomize/cron/base/config-map.yaml
  openshift/kustomize/cron/base/cron-job.yaml
  openshift/kustomize/cron/base/kustomization.yaml
  openshift/kustomize/cron/overlays/dev/kustomization.yaml
  openshift/kustomize/cron/overlays/prod/kustomization.yaml
  openshift/kustomize/cron/overlays/test/kustomization.yaml
Labels: enhancement, devops

#182 Fix Capture Service
  services/net/command/CommandAction`.cs
  services/net/command/CommandProcess.cs
  services/net/command/ICommandProcess.cs
Labels: bug
