Repository bcgov/tno, pull requests merged in 2022-08, with the labels that each got.

#201 Remove java setup files
  Makefile
  docker-compose.yml
  services/docker-compose.yml
  tools/scripts/gen-env-files-java.sh
  tools/scripts/gen-env-files.sh
Labels: devops

#202 TNO-406
  app/editor/src/features/content/list-view/ContentFilter.tsx
Labels: bug

#205 Active hover adjustment
  app/editor/.yarn/cache/tno-core-npm-0.0.162-e4453969b0-69de44d9a0.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.163-53d18eb26f-0643e73560.zip
  app/editor/package.json
  app/editor/yarn.lock
  libs/npm/core/src/components/grid-table/GridTable.tsx
Labels: bug

#204 TNO-404: Increase width of URL field
  app/editor/src/features/admin/sources/connections/Syndication.tsx
Labels: bug

#206 TNO-407 Fix CP Feed Ingest Service
  app/editor/.yarn/install-state.gz
  app/editor/src/features/admin/sources/connections/Syndication.tsx
  docker-compose.yml
  libs/net/dal/Configuration/ContentReferenceConfiguration.cs
  libs/net/dal/Configuration/ContentReferenceLogConfiguration.cs
  libs/net/dal/Migrations/20220804171202_Initial.Designer.cs
  libs/net/dal/Migrations/20220804171202_Initial.cs
  libs/net/dal/Migrations/TNOContextModelSnapshot.cs
  services/net/.vscode/launch.json
  services/net/.vscode/tasks.json
  services/net/syndication/SyndicationAction.cs
  tools/scripts/docker-remove.sh
Labels: bug, DB Migration

#207 TNO-407 Fixing Syndication Ingest Service
  services/net/syndication/SyndicationAction.cs
Labels: bug

#211 Fixed issue with tno-image port
  services/docker-compose.yml
Labels: bug

#210 TNO-405: Time log table displaying wrong month
  app/editor/src/features/content/form/constants/timeLogColumns.tsx
Labels: bug

#212 TNO-321: Consistent Form Page
  app/editor/src/components/form/formpage/styled/FormPage.tsx
Labels: enhancement

#208 TNO-416: Tone values saving on create not update
  app/editor/src/features/content/form/CondensedContentForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug

#213 TNO-434 Fix Syndication Service
  app/editor/src/features/admin/sources/connections/Image.tsx
  services/net/syndication/SyndicationAction.cs
Labels: bug

#192 Created the ContentClipForm component and a tab for it in the snippet…
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Areas/Editor/Models/Storage/FolderModel.cs
  api/net/Areas/Editor/Models/Storage/ItemModel.cs
  app/editor/src/features/content/form/ClipDirectoryFilter.tsx
  app/editor/src/features/content/form/ClipDirectoryTable.tsx
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/constants/clipDirectoryColumns.tsx
  app/editor/src/features/content/form/constants/index.ts
  app/editor/src/features/content/form/index.tsx
  app/editor/src/features/content/form/styled/ClipDirectoryTable.tsx
  app/editor/src/features/content/form/styled/ContentClipForm.tsx
  app/editor/src/features/content/form/styled/index.ts
  app/editor/src/hooks/api-editor/editor/useApiStorage.ts
  app/editor/src/hooks/api-editor/interfaces/IClipModel.ts
  app/editor/src/hooks/api-editor/interfaces/IItemModel.ts
  app/editor/src/hooks/api-editor/interfaces/index.ts
  app/editor/src/store/hooks/storage/useStorage.ts
  libs/net/dal/Helpers/FfmpegHelper.cs
  libs/net/dal/Models/ContentFileReference.cs
  libs/net/dal/Services/FileReferenceService.cs
  libs/net/dal/Services/Interfaces/IFileReferenceService.cs
Labels: enhancement

#214 TNO-440 Updating Content Service
  api/net/Areas/Admin/Models/Tags/TagModel.cs
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Areas/Services/Controllers/DataSourceController.cs
  libs/net/dal/Models/ContentFileReference.cs
  libs/net/dal/Services/FileReferenceService.cs
  libs/net/dal/Services/Interfaces/IFileReferenceService.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Helpers/KafkaListener.cs
  libs/net/services/Helpers/KafkaListener`.cs
  libs/net/services/Interfaces/IApiService.cs
  libs/net/services/Interfaces/IKafkaListener.cs
  libs/net/services/Interfaces/IKafkaListener`.cs
  libs/net/services/Runners/KafkaConsumerService.cs
  services/net/content/Config/ContentOptions.cs
  services/net/content/ContentManager.cs
Labels: bug, enhancement

#216 TNO-431 Fix content source URL
  app/editor/src/features/content/form/CondensedContentForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug

#218 TNO-433: Click enter to search user filter
  app/editor/src/features/admin/users/UserFilter.tsx
  app/editor/src/features/admin/users/styled/UserFilter.tsx
  app/editor/src/features/admin/users/styled/index.ts
Labels: bug

#215 Tone pools bug fix
  app/editor/src/features/content/form/CondensedContentForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug

#220 TNO-449: Active tab bug fix
  app/editor/.yarn/cache/tno-core-npm-0.0.163-53d18eb26f-0643e73560.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.164-f994180313-c12a0e9b6f.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/yarn.lock
  libs/npm/core/package.json
  libs/npm/core/src/components/tabs/Tab.tsx
Labels: bug

#221 Update Image Service
  services/net/.gitignore
  services/net/image/Config/ImageOptions.cs
  services/net/image/ImageAction.cs
  services/net/image/ImageManager.cs
  services/net/image/appsettings.json
Labels: enhancement

#219 TNO-438: Adjust tags column width
  app/editor/src/features/admin/tags/constants/columns.tsx
Labels: enhancement

#223 TNO-430: Hidden expand button on combined view
  app/editor/src/components/form/formpage/FormPage.tsx
  app/editor/src/components/form/formpage/styled/FormPage.tsx
  app/editor/src/features/content/form/CondensedContentForm.tsx
Labels: bug

#224 TNO-452 Design Transcription Process
  app/editor/.yarn/install-state.gz
  app/editor/src/features/admin/categories/constants/defaultCategory.ts
  app/editor/src/features/admin/media-types/constants/defaultMediaType.ts
  app/editor/src/features/admin/series/constants/defaultSeries.ts
  app/editor/src/features/admin/sources/DataSourceDetails.tsx
  app/editor/src/features/admin/sources/constants/defaultDataSource.ts
  app/editor/src/features/login/LoginPanel.tsx
  app/editor/src/hooks/api-editor/editor/useApiCategories.ts
  app/editor/src/hooks/api-editor/interfaces/ICategoryModel.ts
  app/editor/src/hooks/api-editor/interfaces/IDataSourceModel.ts
  app/editor/src/hooks/api-editor/interfaces/IMediaTypeModel.ts
  app/editor/src/hooks/api-editor/interfaces/ISeriesModel.ts
  app/editor/src/hooks/api-editor/mocks/mediaTypes.ts
  app/editor/src/hooks/api-editor/mocks/series.ts
  docs/DEVELOPMENT.md
  libs/npm/core/src/hooks/keycloak/createKeycloakInstance.ts
Labels: enhancement

#217 Adding pause and optimistic concurrency on content update code
  services/net/transcription/TranscriptionManager.cs
Labels: enhancement

#225 TNO-458: Combined view layout update
  app/editor/src/features/content/combined-view/CombinedView.tsx
  app/editor/src/features/content/combined-view/ListViewPanel.tsx
  app/editor/src/features/content/combined-view/styled/CombinedView.tsx
  app/editor/src/features/content/combined-view/styled/ListViewPanel.tsx
  app/editor/src/features/content/list-view/ContentFilter.tsx
  app/editor/src/features/content/list-view/styled/ContentFilter.tsx
Labels: enhancement

#226 Fixed a syndication issue
  libs/net/core/Extensions/StringExtensions.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug, enhancement

#228 TNO-425: Fix the add a tag error
  app/editor/src/features/admin/actions/ActionForm.tsx
  app/editor/src/features/admin/categories/CategoryForm.tsx
  app/editor/src/features/admin/tags/TagListFilter.tsx
  app/editor/src/features/admin/tags/TagsForm.tsx
Labels: bug

#229 Content List View Enhancement
  app/editor/.devcontainer/devcontainer.json
  app/editor/.vscode/launch.json
  app/editor/src/App.test.tsx
  app/editor/src/components/form/checkbox/styled/Checkbox.tsx
  app/editor/src/components/form/formpage/FormPage.tsx
  app/editor/src/components/form/formpage/styled/FormPage.tsx
  app/editor/src/features/content/combined-view/CombinedView.tsx
  app/editor/src/features/content/combined-view/ListViewPanel.tsx
  app/editor/src/features/content/combined-view/styled/CombinedView.tsx
  app/editor/src/features/content/combined-view/styled/ListViewPanel.tsx
  app/editor/src/features/content/combined-view/styled/index.ts
  app/editor/src/features/content/form/CondensedContentForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/FormPicker.tsx
  app/editor/src/features/content/form/index.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
  app/editor/src/features/content/list-view/ContentListView.test.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/__snapshots__/ContentListView.test.tsx.snap
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
  app/editor/src/features/router/AppRouter.tsx
  app/editor/src/hooks/api-editor/constants/ContentType.ts
  app/editor/src/hooks/index.ts
  app/editor/src/hooks/lookups/index.ts
  app/editor/src/hooks/lookups/useDataSourceOptions.ts
  app/editor/src/hooks/lookups/useMediaTypeOptions.ts
  app/editor/src/hooks/lookups/useUserLookups.ts
  app/editor/src/hooks/useCombinedView.ts
  app/editor/src/hooks/useTooltips.ts
  app/editor/src/test/utils/testData.ts
  db/elasticsearch/dejavu/Dockerfile
  test/TNO.postman_collection.json
Labels: bug, enhancement

#231 TNO-447: User List Paging Bug Fix
  app/editor/src/features/admin/users/UserFilter.tsx
  app/editor/src/features/admin/users/UserList.tsx
  app/editor/src/features/admin/users/interfaces/IUserListFilter.ts
  app/editor/src/features/content/list-view/utils/makeUserFilter.ts
  app/editor/src/hooks/api-editor/interfaces/IUserFilter.ts
  app/editor/src/store/slices/admin/adminSlice.ts
Labels: bug

#234 TNO-421: Add tooltips to filter checkboxes
  app/editor/src/features/content/list-view/ContentFilter.tsx
Labels: bug, enhancement

#230 add image service
  .gitignore
  app/editor/src/features/admin/sources/connections/Image.tsx
  app/editor/src/hooks/api-editor/constants/DataLocationType.ts
  libs/net/entities/DataLocationType.cs
  services/net/image/Config/ImageOptions.cs
  services/net/image/Dockerfile
  services/net/image/ImageAction.cs
  services/net/image/TNO.Services.Image.csproj
  services/net/image/appsettings.json
Labels: enhancement

#237 TNO-529 Fix add data source
  app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx
  libs/net/dal/Extensions/DataSourceExtensions.cs
  libs/net/dal/Services/DataSourceService.cs
Labels: bug

#238 Remove default user
  libs/net/dal/Migrations/Initial/Up/PostUp/00-User.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/01-UserRole.sql
Labels: enhancement

#235 Fixed an invalid text encoding issue
  libs/net/dal/Services/ContentService.cs
  services/net/syndication/Config/SyndicationOptions.cs
  services/net/syndication/SyndicationAction.cs
  services/net/syndication/appsettings.json
Labels: bug

#239 TNO-523 Fix AV editing
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Areas/Editor/Models/Storage/FolderModel.cs
  api/net/Areas/Editor/Models/Storage/ItemModel.cs
  app/editor/.yarn/cache/tno-core-npm-0.0.164-f994180313-c12a0e9b6f.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.165-043f99583f-2d70e0d546.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/content/form/ClipDirectoryTable.tsx
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentTranscriptForm.tsx
  app/editor/src/features/content/form/constants/clipDirectoryColumns.tsx
  app/editor/src/features/content/form/styled/ClipDirectoryTable.tsx
  app/editor/src/features/content/form/styled/ContentClipForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
  app/editor/src/hooks/api-editor/editor/useApiStorage.ts
  app/editor/src/store/hooks/storage/useStorage.ts
  app/editor/yarn.lock
  libs/net/dal/Helpers/FfmpegHelper.cs
  libs/npm/core/package.json
  libs/npm/core/src/components/grid-table/GridTable.tsx
  libs/npm/core/src/components/tabs/TabContainer.tsx
  libs/npm/core/src/components/tabs/Tabs.tsx
Labels: bug

#233 TNO-377: CHES Integration
  libs/net/ches/ChesService.cs
  libs/net/ches/Configuration/ChesOptions.cs
  libs/net/ches/Exceptions/ChesException.cs
  libs/net/ches/Extensions/ServiceCollectionExtensions.cs
  libs/net/ches/IChesService.cs
  libs/net/ches/Models/AttachmentModel.cs
  libs/net/ches/Models/EmailBodyTypes.cs
  libs/net/ches/Models/EmailContextModel.cs
  libs/net/ches/Models/EmailEncodings.cs
  libs/net/ches/Models/EmailMergeModel.cs
  libs/net/ches/Models/EmailModel.cs
  libs/net/ches/Models/EmailPriorities.cs
  libs/net/ches/Models/EmailResponseModel.cs
  libs/net/ches/Models/ErrorModel.cs
  libs/net/ches/Models/ErrorResponseModel.cs
  libs/net/ches/Models/IAttachment.cs
  libs/net/ches/Models/IEmail.cs
  libs/net/ches/Models/IEmailContext.cs
  libs/net/ches/Models/IEmailMerge.cs
  libs/net/ches/Models/MessageResponseModel.cs
  libs/net/ches/Models/StatusHistoryResponseModel.cs
  libs/net/ches/Models/StatusModel.cs
  libs/net/ches/Models/StatusResponseModel.cs
  libs/net/ches/TNO.Ches.csproj
  libs/net/core/Converters/EnumValueJsonConverter.cs
  libs/net/core/Converters/MicrosecondEpochJsonConverter.cs
  libs/net/core/Extensions/EnumExtensions.cs
  libs/net/core/Json/EnumValueAttribute.cs
Labels: enhancement

#241 TNO-525 Fix AV editing attach
  api/net/.devcontainer/devcontainer.json
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Areas/Editor/Models/Storage/FolderModel.cs
  app/editor/.yarn/install-state.gz
  app/editor/src/features/content/form/ClipDirectoryTable.tsx
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/constants/clipDirectoryColumns.tsx
  app/editor/src/features/content/form/styled/ClipDirectoryTable.tsx
  app/editor/src/hooks/api-editor/editor/useApiContents.ts
  app/editor/src/hooks/api-editor/editor/useApiStorage.ts
  app/editor/src/store/hooks/content/useContent.ts
  app/editor/src/store/hooks/storage/useStorage.ts
  libs/net/.devcontainer/devcontainer.json
  libs/net/dal/Models/ContentFileReference.cs
  libs/net/dal/Services/FileReferenceService.cs
  services/net/.devcontainer/devcontainer.json
  tools/import/.devcontainer/devcontainer.json
Labels: bug

#240 Fixed the TNO-444 issue
  api/net/Areas/Admin/Controllers/UserController.cs
Labels: bug

#242 Fix logging invalid characters
  api/net/appsettings.json
  services/net/capture/appsettings.json
  services/net/clip/appsettings.json
  services/net/content/appsettings.json
  services/net/image/appsettings.json
  services/net/indexing/appsettings.json
  services/net/nlp/appsettings.json
  services/net/syndication/appsettings.json
  services/net/transcription/appsettings.json
Labels: devops
