Repository bcgov/tno, pull requests merged in 2022-10, with the labels that each got.

#305 Fixed TNO-613
  app/editor/src/components/form/radio/RadioGroup.tsx
  app/editor/src/components/form/select/Select.tsx
  app/editor/src/components/form/textarea/TextArea.tsx
  app/editor/src/index.scss
  libs/npm/core/src/components/form/text/Text.tsx
Labels: bug, enhancement

#308 Text area styling
  app/editor/src/components/form/textarea/TextArea.tsx
  app/editor/src/components/form/textarea/styled/TextArea.ts
Labels: bug

#302 TNO-607, 457: Product store not updating correctly & Combined view not updating list
  app/editor/src/features/admin/products/ProductForm.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/hooks/index.ts
  app/editor/src/hooks/useLookupSync.ts
  app/editor/src/store/hooks/content/useContent.ts
  app/editor/src/store/hooks/lookup/utils/filterEnabled.ts
  app/editor/src/store/hooks/lookup/utils/index.ts
  app/editor/src/utils/getSortableOptions.ts
Labels: bug

#311 TNO-618 Update DB Migration
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  openshift/kustomize/README.md
  openshift/kustomize/elastic/overlays/test/kustomization.yaml
Labels: DB Migration, devops

#310 TNO-590: Content list view screen real estate
  .vscode/settings.json
  app/editor/.yarn/cache/tno-core-npm-0.0.173-2a66d7f573-72277cef5f.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.175-96600f0908-06d204a652.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/content/list-view/ContentFilter.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/navbar/NavBar.tsx
  app/editor/yarn.lock
  libs/npm/core/package.json
  libs/npm/core/src/components/cell/Ellipsis.tsx
  libs/npm/core/src/components/grid-table/GridTable.tsx
  libs/npm/core/src/components/grid-table/PagedTable.tsx
  libs/npm/core/src/components/grid-table/styled/GridTable.tsx
Labels: bug, enhancement

#313 Fix GridTable bugs
  app/editor/.yarn/cache/tno-core-npm-0.0.175-96600f0908-06d204a652.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.177-1b8584784d-34bd152f00.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/components/breadcrumb/Breadcrumb.tsx
  app/editor/src/components/breadcrumb/styled/Breadcrumb.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/constants/clipDirectoryColumns.tsx
  app/editor/src/features/content/list-view/ContentFilter.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/__snapshots__/ContentListView.test.tsx.snap
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/list-view/constants/defaultFilter.ts
  app/editor/src/features/content/list-view/interfaces/IContentListFilter.ts
  app/editor/src/store/slices/content/contentSlice.ts
  app/editor/yarn.lock
  libs/npm/core/package.json
  libs/npm/core/src/components/grid-table/GridTable.tsx
Labels: bug

#309 Mapping paper names to source configuration
  services/net/.gitignore
  services/net/filemonitor/Config/FilemonitorOptions.cs
  services/net/filemonitor/FileMonitorIngestActionManager.cs
  services/net/filemonitor/FilemonitorAction.cs
  services/net/filemonitor/TNO.Services.Filemonitor.csproj
  services/net/filemonitor/appsettings.json
  services/net/image/ImageAction.cs
Labels: enhancement

#315 TNO-618 Setup Test environment
  openshift/README.md
  openshift/kustomize/README.md
  openshift/kustomize/api/overlays/dev/kustomization.yaml
  openshift/kustomize/api/overlays/prod/kustomization.yaml
  openshift/kustomize/api/overlays/test/kustomization.yaml
  openshift/kustomize/app/editor/overlays/dev/kustomization.yaml
  openshift/kustomize/app/editor/overlays/prod/kustomization.yaml
  openshift/kustomize/app/editor/overlays/test/kustomization.yaml
  openshift/kustomize/elastic/overlays/dev/kustomization.yaml
  openshift/kustomize/elastic/overlays/prod/kustomization.yaml
  openshift/kustomize/elastic/overlays/test/kustomization.yaml
  openshift/kustomize/kafka/broker/overlays/dev/kustomization.yaml
  openshift/kustomize/kafka/broker/overlays/prod/kustomization.yaml
  openshift/kustomize/kafka/broker/overlays/test/kustomization.yaml
  openshift/kustomize/kafka/kowl/overlays/dev/kustomization.yaml
  openshift/kustomize/kafka/kowl/overlays/prod/kustomization.yaml
  openshift/kustomize/kafka/kowl/overlays/test/kustomization.yaml
  openshift/kustomize/kafka/zookeeper/overlays/dev/kustomization.yaml
  openshift/kustomize/kafka/zookeeper/overlays/prod/kustomization.yaml
  openshift/kustomize/kafka/zookeeper/overlays/test/kustomization.yaml
  openshift/kustomize/nginx/overlays/dev/kustomization.yaml
  openshift/kustomize/nginx/overlays/prod/kustomization.yaml
  openshift/kustomize/nginx/overlays/test/kustomization.yaml
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/services/capture/overlays/dev/kustomization.yaml
  openshift/kustomize/services/capture/overlays/prod/kustomization.yaml
  openshift/kustomize/services/capture/overlays/test/kustomization.yaml
  openshift/kustomize/services/clip/base/deploy.yaml
  openshift/kustomize/services/clip/overlays/dev/kustomization.yaml
  openshift/kustomize/services/clip/overlays/prod/kustomization.yaml
  openshift/kustomize/services/clip/overlays/test/kustomization.yaml
  openshift/kustomize/services/content/base/deploy.yaml
  openshift/kustomize/services/content/overlays/dev/kustomization.yaml
  openshift/kustomize/services/content/overlays/prod/kustomization.yaml
  openshift/kustomize/services/content/overlays/test/kustomization.yaml
  openshift/kustomize/services/image/overlays/dev/kustomization.yaml
  openshift/kustomize/services/image/overlays/prod/kustomization.yaml
  openshift/kustomize/services/image/overlays/test/kustomization.yaml
  openshift/kustomize/services/indexing/overlays/dev/kustomization.yaml
  openshift/kustomize/services/indexing/overlays/prod/kustomization.yaml
  openshift/kustomize/services/indexing/overlays/test/kustomization.yaml
  openshift/kustomize/services/nlp/overlays/dev/kustomization.yaml
  openshift/kustomize/services/nlp/overlays/prod/kustomization.yaml
  openshift/kustomize/services/nlp/overlays/test/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/dev/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/prod/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/test/kustomization.yaml
  openshift/kustomize/services/transcription/overlays/dev/kustomization.yaml
  openshift/kustomize/services/transcription/overlays/prod/kustomization.yaml
  openshift/kustomize/services/transcription/overlays/test/kustomization.yaml
Labels: devops

#316 TNO-657 Rebrand MMIA
  app/editor/.yarn/install-state.gz
  app/editor/public/manifest.json
  app/editor/src/App.tsx
  app/editor/src/features/access-request/AccessRequest.tsx
  app/editor/src/features/access-request/PreapprovedRequest.tsx
  app/editor/src/features/content/list-view/ContentListView.test.tsx
  app/editor/src/features/content/list-view/__snapshots__/ContentListView.test.tsx.snap
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/list-view/constants/condensedColumns.tsx
  app/editor/src/features/home/InfoText.tsx
  app/editor/src/features/login/LoginPanel.tsx
  app/editor/src/hooks/api-editor/constants/UserStatus.ts
Labels: enhancement

#318 Fix content form
  app/editor/.yarn/install-state.gz
  app/editor/src/components/form/datepicker/styled/SelectDate.tsx
  app/editor/src/components/form/timeinput/TimeInput.tsx
  app/editor/src/components/form/timeinput/styled/TimeInput.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/__snapshots__/ContentListView.test.tsx.snap
  app/editor/src/hooks/useCombinedView.ts
Labels: bug

#319 TNO-593 Fix attach clip
  app/editor/src/components/upload/Upload.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#320 Fix content form layout
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
Labels: bug

#322 TNO-661 Fix page title
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/public/index.html
  app/editor/yarn.lock
Labels: bug

#323 Fix DevOps configs
  openshift/kustomize/services/capture/base/config-map.yaml
  openshift/kustomize/services/clip/base/config-map.yaml
  openshift/kustomize/services/image/base/config-map.yaml
  openshift/kustomize/services/image/base/deploy.yaml
Labels: devops

#326 Fix Image/File Services
  app/editor/.yarn/install-state.gz
  app/editor/src/features/admin/ingests/IngestSettings.tsx
  app/editor/src/features/admin/ingests/configurations/FrontPage.tsx
  app/editor/src/features/admin/ingests/configurations/Image.tsx
  app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
  app/editor/src/features/admin/ingests/configurations/constants/FileTypes.ts
  app/editor/src/features/admin/ingests/configurations/constants/index.ts
  libs/net/dal/Migrations/Initial/Up/PostUp/00-Connection.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/03-IngestSchedule.sql
  openshift/kustomize/services/image/base/config-map.yaml
  openshift/kustomize/services/image/base/deploy.yaml
  services/net/filemonitor/FilemonitorAction.cs
  services/net/image/ImageAction.cs
Labels: bug, enhancement, DB Migration

#327 Fix Capture/Clip Service
  app/editor/src/features/admin/ingests/schedules/ScheduleDaily.tsx
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/command/CommandAction`.cs
  services/net/content/ContentManager.cs
  services/net/transcription/TranscriptionManager.cs
Labels: bug

#328 TNO-671: Reset font size in tables
  app/editor/.yarn/cache/tno-core-npm-0.0.178-7c0146ebfb-76c7a3269e.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.179-dfa1209688-5e5d56f548.zip
  app/editor/package.json
  app/editor/yarn.lock
  libs/npm/core/package.json
  libs/npm/core/src/components/grid-table/styled/GridTable.tsx
Labels: bug

#329 TNO-646 Fix published on
  app/editor/src/features/admin/ingests/IngestSettings.tsx
  app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/router/AppRouter.tsx
  libs/net/core/Extensions/DateTimeExtensions.cs
  libs/net/dal/Migrations/Initial/Up/PostUp/00-Connection.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  libs/net/services/Actions/IngestAction.cs
  libs/net/services/Actions/Managers/IngestActionManager`.cs
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/command/CommandAction`.cs
  services/net/filemonitor/FilemonitorAction.cs
  services/net/image/ImageAction.cs
Labels: bug, DB Migration

#331 TNO-139 Fix File Service
  services/net/filemonitor/FilemonitorAction.cs
Labels: bug

#332 TNO-617 Fix UID
  app/editor/.yarn/install-state.gz
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/constants/defaultFormValues.ts
  app/editor/src/features/content/form/interfaces/IContentForm.tsx
  app/editor/src/features/content/form/utils/toForm.ts
  app/editor/src/features/content/form/utils/toModel.ts
  app/editor/src/hooks/api-editor/interfaces/IContentModel.ts
  app/editor/src/hooks/api-editor/mocks/contents.ts
  libs/net/Dockerfile
  libs/net/dal/Extensions/ContentExtensions.cs
  libs/net/dal/Services/ContentService.cs
  services/net/image/ImageAction.cs
Labels: bug, enhancement, devops

#333 TNO-680 Fix Print Content Actions
  app/editor/src/features/content/form/ContentActions.tsx
  app/editor/src/features/content/form/utils/toModel.ts
  openshift/kustomize/tekton/base/deploy.yaml
  openshift/kustomize/tekton/base/pvc.yaml
  openshift/kustomize/tekton/build/base/Dockerfile
  openshift/kustomize/tekton/build/base/build.yaml
  openshift/kustomize/tekton/build/overlays/dev/kustomization.yaml
  openshift/kustomize/tekton/build/overlays/master/kustomization.yaml
  openshift/kustomize/tekton/overlays/tools/kustomization.yaml
Labels: bug

#325 TNO-408: Sitewide file upload
  app/editor/src/App.tsx
  app/editor/src/components/upload/UploadContext.ts
  app/editor/src/components/upload/UploadContextWrapper.tsx
  app/editor/src/components/upload/index.ts
  app/editor/src/components/upload/interfaces/FetchState.ts
  app/editor/src/components/upload/interfaces/IUploadManager.ts
  app/editor/src/components/upload/interfaces/IUploadState.ts
  app/editor/src/components/upload/interfaces/index.ts
  app/editor/src/features/storage/StorageListView.tsx
Labels: enhancement

#334 TNO-533: Data source validation
  app/editor/src/hooks/api-editor/validation/SourceSchema.ts
Labels: bug

#338 Fixed TNO-634
  app/editor/src/features/admin/sources/constants/columns.tsx
Labels: bug, enhancement

#342 Fixed TNO-505
  app/editor/src/features/admin/sources/constants/columns.tsx
Labels: bug, enhancement

#339 TNO-642: Admin Page Consistency
  app/editor/src/components/form/formpage/styled/FormPage.tsx
  app/editor/src/features/admin/connections/ConnectionList.tsx
  app/editor/src/features/admin/connections/styled/ConnectionList.tsx
  app/editor/src/features/admin/ingest-types/IngestTypeList.tsx
  app/editor/src/features/admin/ingest-types/styled/IngestTypeList.tsx
  app/editor/src/features/admin/ingests/IngestList.tsx
  app/editor/src/features/admin/sources/SourceList.tsx
  app/editor/src/features/admin/users/UserList.tsx
  app/editor/src/features/admin/users/styled/UserList.tsx
  app/editor/src/hooks/useCombinedView.ts
Labels: bug

#343 TNO-642: Fix bug introduced on combined view
  app/editor/src/components/form/formpage/FormPage.tsx
  app/editor/src/components/form/formpage/styled/FormPage.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
Labels: bug

#344 TNO-630: Form page expand to children
  app/editor/src/components/form/formpage/styled/FormPage.tsx
Labels: bug

#345 TNO-645: Fix button overlap on full content form
  app/editor/src/features/content/form/styled/ContentForm.tsx
Labels: bug

#347 TNO-606: Ensure validation is run on publish
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/utils/index.ts
  app/editor/src/features/content/form/utils/triggerFormikValidate.ts
Labels: bug, enhancement

#348 Add some docs
  app/editor/src/features/admin/users/utils/makeUserFilter.ts
  app/editor/src/features/content/form/utils/formatTime.ts
  app/editor/src/features/content/form/utils/getTotalTime.ts
  app/editor/src/features/content/list-view/utils/setTimeFrame.ts
  app/editor/src/utils/formatIdir.ts
  app/editor/src/utils/formatUserRoles.ts
  app/editor/src/utils/hasErrors.ts
Labels: documentation

#351 Fixed TNO-651
  app/editor/src/features/content/form/ClipDirectoryTable.tsx
Labels: enhancement

#352 Fixed TNO-652
  app/editor/src/components/form/radio/RadioGroup.tsx
  app/editor/src/components/form/select/Select.tsx
  app/editor/src/components/form/textarea/TextArea.tsx
  libs/npm/core/src/components/form/text/Text.tsx
Labels: bug

#353 Fixed TNO-641
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#350 TNO-355 Add Multithreading to Transcription Service
  libs/net/kafka/Interfaces/IKafkaListener`.cs
  libs/net/kafka/KafkaListener`.cs
  services/net/transcription/Config/TranscriptionOptions.cs
  services/net/transcription/TranscriptionManager.cs
  services/net/transcription/appsettings.json
Labels: enhancement

#340 TNO-658: Button tooltip not disappearing
  app/editor/.yarn/install-state.gz
  libs/npm/core/src/components/button/Button.tsx
  libs/npm/core/src/utils/hideTooltipOnClick.ts
  libs/npm/core/src/utils/index.ts
Labels: bug

#341 Tno 644 - Add Globe and Mail import to the filemonitor service
  libs/net/dal/Migrations/Initial/Up/PostUp/00-Connection.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/01-Schedule.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/03-IngestSchedule.sql
  services/net/filemonitor/FilemonitorAction.cs
Labels: enhancement

#355 TNO-715 Fix keycloak changes
  api/net/Areas/Admin/Models/User/UserModel.cs
  api/net/Keycloak/KeycloakHelper.cs
  api/net/Models/Auth/PrincipalModel.cs
  openshift/kustomize/api/base/config-map.yaml
  openshift/kustomize/api/base/deploy.yaml
  openshift/kustomize/api/overlays/dev/kustomization.yaml
  openshift/kustomize/api/overlays/prod/kustomization.yaml
  openshift/kustomize/api/overlays/test/kustomization.yaml
Labels: bug

#356 TNO-700 Simpify publishing
  api/net/Areas/Editor/Controllers/ContentController.cs
  app/editor/.yarn/install-state.gz
  app/editor/src/features/content/form/ContentForm.tsx
  libs/net/entities/User.cs
Labels: enhancement

#359 TNO-704: Action isEnabled checkbox
  api/net/Areas/Admin/Models/Action/ActionModel.cs
Labels: bug

#361 Filter the content list by published date instead of created date
  app/editor/src/features/content/list-view/ContentFilter.tsx
  app/editor/src/features/content/list-view/utils/makeFilter.ts
Labels: bug

#362 TNO-711: Double scroll bar fix
  app/editor/src/components/form/formpage/styled/FormPage.tsx
  app/editor/src/features/admin/work-orders/WorkOrderList.tsx
  app/editor/src/features/admin/work-orders/styled/WorkOrderList.tsx
Labels: bug

#357 Fixed TNO-677
  app/editor/src/features/admin/users/UserFilter.tsx
Labels: enhancement

#360 TNO-712 - Ingest content with unknown source name
  app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
  services/net/filemonitor/FilemonitorAction.cs
Labels: enhancement

#366 Tweaks to address issues introduced from TNO-711
  app/editor/src/components/form/formpage/styled/FormPage.tsx
  app/editor/src/features/admin/ingests/IngestForm.tsx
  app/editor/src/features/admin/ingests/IngestStatus.tsx
  app/editor/src/features/admin/ingests/styled/IngestForm.tsx
  app/editor/src/features/admin/ingests/styled/IngestStatus.tsx
Labels: bug

#367 TNO-673: Users missing from list
  api/net/Areas/Admin/Controllers/UserController.cs
  libs/net/dal/Services/UserService.cs
Labels: bug

#364 TNO-699: replace p tag with new line in content service
  libs/net/core/Extensions/StringExtensions.cs
  services/net/content/ContentManager.cs
Labels: enhancement

#369 TNO-713: More smarts to tags
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#368 Fixed TNO-696
  app/editor/src/features/content/form/ContentActions.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/utils/index.ts
  app/editor/src/features/content/form/utils/isImageForm.ts
  app/editor/src/features/content/form/utils/isSnippetForm.ts
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/validation/ContentFormSchema.ts
  app/editor/src/features/router/AppRouter.tsx
Labels: enhancement

#371 Fix syndication service
  services/net/syndication/SyndicationAction.cs
  services/net/syndication/SyndicationIngestActionManager.cs
Labels: bug
