Repository bcgov/tno, pull requests merged in 2022-05, with the labels that each got.

#117 Sign In Button
  app/editor/src/features/home/styled/InfoPanelStyled.tsx
Labels: bug

#114 TNO-300, 310, 311: Turn off auto complete on publishedOn, Extend tags field, Reduce summary height
  app/editor/src/features/content/form/PropertiesContentForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
Labels: bug

#113 TNO-316: Hide time from date range filter
  app/editor/src/features/content/list-view/ContentListView.tsx
Labels: bug

#121 TNO-320 Refactor import
  libs/net/entities/FileReference.cs
  tools/import/Import.sln
  tools/import/Makefile
  tools/import/core/Extensions/ModelBuilderExtensions.cs
  tools/import/core/TNO.Core.csproj
  tools/import/destination/Configuration/ActionConfiguration.cs
  tools/import/destination/Configuration/CategoryConfiguration.cs
  tools/import/destination/Configuration/ClaimConfiguration.cs
  tools/import/destination/Configuration/ContentActionConfiguration.cs
  tools/import/destination/Configuration/ContentCategoryConfiguration.cs
  tools/import/destination/Configuration/ContentConfiguration.cs
  tools/import/destination/Configuration/ContentLinkConfiguration.cs
  tools/import/destination/Configuration/ContentTagConfiguration.cs
  tools/import/destination/Configuration/ContentTonePoolConfiguration.cs
  tools/import/destination/Configuration/ContentTypeConfiguration.cs
  tools/import/destination/Configuration/DataSourceConfiguration.cs
  tools/import/destination/Configuration/FileReferenceConfiguration.cs
  tools/import/destination/Configuration/MediaTypeConfiguration.cs
  tools/import/destination/Configuration/RoleConfiguration.cs
  tools/import/destination/Configuration/SeriesConfiguration.cs
  tools/import/destination/Configuration/TagConfiguration.cs
  tools/import/destination/Configuration/TimeTrackingConfiguration.cs
  tools/import/destination/Configuration/TonePoolConfiguration.cs
  tools/import/destination/Configuration/UserConfiguration.cs
  tools/import/destination/ContentStatus.cs
  tools/import/destination/DestinationContext.cs
  tools/import/destination/Entities/Action.cs
  tools/import/destination/Entities/AuditColumns.cs
  tools/import/destination/Entities/BaseType.cs
  tools/import/destination/Entities/Category.cs
  tools/import/destination/Entities/Claim.cs
  tools/import/destination/Entities/Content.cs
  tools/import/destination/Entities/ContentAction.cs
  tools/import/destination/Entities/ContentCategory.cs
  tools/import/destination/Entities/ContentLink.cs
  tools/import/destination/Entities/ContentTag.cs
  tools/import/destination/Entities/ContentTone.cs
  tools/import/destination/Entities/ContentType.cs
  tools/import/destination/Entities/DataLocation.cs
  tools/import/destination/Entities/DataSource.cs
  tools/import/destination/Entities/FileReference.cs
  tools/import/destination/Entities/License.cs
  tools/import/destination/Entities/MediaType.cs
  tools/import/destination/Entities/Role.cs
  tools/import/destination/Entities/Series.cs
  tools/import/destination/Entities/Tag.cs
  tools/import/destination/Entities/TimeTracking.cs
  tools/import/destination/Entities/TonePool.cs
  tools/import/destination/Entities/User.cs
  tools/import/destination/Services/ContentService.cs
  tools/import/destination/TNO.Tools.Import.Destination.csproj
  tools/import/destination/ValueType.cs
  tools/import/destination/WorkflowStatus.cs
  tools/import/etl/Config/ServiceCollectionExtensions.cs
  tools/import/etl/ImportService.cs
  tools/import/etl/TNO.Tools.Import.ETL.csproj
  tools/import/source/TNO.Tools.Import.Source.csproj
Labels: enhancement

#118 TNO-317: Use full source name
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/utils/getDataSourceOptions.ts
Labels: bug

#123 TNO-301
  network/nginx/html/index.html
  openshift/kustomize/api/base/deploy.yaml
Labels: bug, devops

#125 Fix devops templates
  openshift/kustomize/api/base/config-map.yaml
  openshift/kustomize/api/base/deploy.yaml
  openshift/kustomize/api/overlays/dev/deploy.yaml
  openshift/templates/api/deploy.yaml
  openshift/templates/tekton/pipelines/complete.yaml
  openshift/templates/tekton/pipelines/db-migration.yaml
  openshift/templates/tekton/pipelines/deploy.yaml
  openshift/templates/tekton/tasks/db-migration.yaml
Labels: devops

#119 TNO-270: Add ability to delete data source
  app/editor/src/components/form/formpage/styled/FormPage.tsx
  app/editor/src/features/admin/sources/DataSource.tsx
  app/editor/src/features/content/form/ContentForm.tsx
Labels: enhancement

#126 Expand width of Headline column
  app/editor/.yarn/cache/tno-core-npm-0.0.123-65fae51bf9-b1f6e48a89.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.124-c182882a71-7b8319be56.zip
  app/editor/package.json
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/yarn.lock
  libs/npm/core/package.json
  libs/npm/core/src/components/grid-table/GridTable.tsx
Labels: bug

#128 Bug fixes
  app/editor/src/features/content/form/utils/toForm.ts
  app/editor/src/features/content/list-view/constants/columns.tsx
Labels: bug

#129 Fixing content form bugs
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/utils/toForm.ts
Labels: bug, enhancement

#130 Fix upload/download
  app/editor/src/components/upload/Upload.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  libs/net/dal/Extensions/FileReferenceExtensions.cs
  libs/net/dal/Models/ContentFileReference.cs
  libs/net/dal/Services/FileReferenceService.cs
  libs/net/entities/Interfaces/IReadonlyFileReference.cs
  libs/npm/core/src/hooks/summon/useSummon.tsx
Labels: bug

#140 TNO-336 Fix content service devops
  openshift/kustomize/services/content/overlays/dev/kustomization.yaml
  openshift/kustomize/services/content/overlays/prod/kustomization.yaml
  openshift/kustomize/services/content/overlays/test/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/dev/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/prod/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/test/kustomization.yaml
  services/net/content/ContentAction.cs
  services/net/content/ContentActionManager.cs
  services/net/content/Dockerfile
  services/net/content/appsettings.Staging.json
  services/net/content/appsettings.json
  services/net/syndication/appsettings.Staging.json
  services/net/syndication/appsettings.json
Labels: bug, devops

#141 TNO-336 Fix service api
  libs/net/services/Controllers/HealthController.cs
  libs/net/services/Controllers/StatusController.cs
  openshift/kustomize/services/content/base/deploy.yaml
  openshift/kustomize/services/syndication/base/deploy.yaml
  services/net/content/ContentService.cs
  services/net/syndication/SyndicationService.cs
Labels: bug, devops

#143 Fix Service API
  libs/net/services/ServiceState.cs
Labels: bug

#144 Fix Service Build Bug
  libs/net/services/ServiceState.cs
Labels: bug

#145 Fix content search
  libs/net/dal/Services/ContentService.cs
Labels: bug

#146 TNO-361 Handle invalid RSS
  app/editor/.yarn/install-state.gz
  app/editor/src/components/form/datepicker/SelectDate.tsx
  app/editor/src/components/formik/checkbox/FormikCheckbox.tsx
  app/editor/src/components/formik/datepicker/FormikDatePicker.tsx
  app/editor/src/components/formik/radio/FormikRadioGroup.tsx
  app/editor/src/components/formik/select/FormikSelect.tsx
  app/editor/src/components/formik/text/FormikText.tsx
  app/editor/src/components/formik/textarea/FormikTextArea.tsx
  app/editor/src/features/admin/sources/DataSource.tsx
  app/editor/src/features/admin/sources/connections/AVArchive.tsx
  app/editor/src/features/admin/sources/connections/Audio.tsx
  app/editor/src/features/admin/sources/connections/Connection.tsx
  app/editor/src/features/admin/sources/connections/Newspaper.tsx
  app/editor/src/features/admin/sources/connections/Syndication.tsx
  app/editor/src/features/admin/sources/connections/Video.tsx
  app/editor/src/features/admin/sources/connections/index.ts
  app/editor/src/features/admin/sources/connections/styled/Connection.tsx
  app/editor/src/features/admin/sources/connections/styled/MediaType.tsx
  app/editor/src/features/admin/sources/connections/styled/index.ts
  app/editor/src/features/admin/sources/services/ScheduleAdvanced.tsx
  app/editor/src/features/admin/sources/services/ServiceConfig.tsx
  app/editor/src/features/admin/sources/services/validation/ScheduleSchema.ts
  app/editor/src/features/admin/sources/services/validation/index.ts
  app/editor/src/hooks/api-editor/interfaces/IScheduleModel.ts
  app/editor/src/hooks/api-editor/validation/AdvancedScheduleSchema.ts
  app/editor/src/hooks/api-editor/validation/AuditColumnsSchema.ts
  app/editor/src/hooks/api-editor/validation/DataSourceSchema.ts
  app/editor/src/hooks/api-editor/validation/ScheduleSchema.ts
  app/editor/src/hooks/api-editor/validation/index.ts
  libs/net/dal/Configuration/ScheduleConfiguration.cs
  libs/net/dal/Services/DataSourceService.cs
  libs/net/entities/DataSource.cs
  libs/net/entities/Validation/KafkaTopicAttribute.cs
  openshift/kustomize/kafka/broker/base/config-map.yaml
  openshift/kustomize/kafka/broker/base/kustomization.yaml
  openshift/kustomize/kafka/broker/base/statefulset.yaml
  services/net/syndication/SyndicationAction.cs
  services/net/syndication/Xml/Atom/AtomFeed.cs
  services/net/syndication/Xml/Rss/RssCategory.cs
  services/net/syndication/Xml/Rss/RssChannel.cs
  services/net/syndication/Xml/Rss/RssCloud.cs
  services/net/syndication/Xml/Rss/RssDay.cs
  services/net/syndication/Xml/Rss/RssEnclosure.cs
  services/net/syndication/Xml/Rss/RssFeed.cs
  services/net/syndication/Xml/Rss/RssGuid.cs
  services/net/syndication/Xml/Rss/RssHour.cs
  services/net/syndication/Xml/Rss/RssImage.cs
  services/net/syndication/Xml/Rss/RssItem.cs
  services/net/syndication/Xml/Rss/RssRating.cs
  services/net/syndication/Xml/Rss/RssSource.cs
  services/net/syndication/Xml/Rss/RssTextInput.cs
  tools/scripts/gen-env-files.sh
Labels: bug, enhancement

#147 Content service duplicates
  api/net/Areas/Services/Controllers/ContentController.cs
  libs/net/core/Http/HttpRequestClient.cs
  libs/net/dal/Services/ContentService.cs
  libs/net/dal/Services/Interfaces/IContentService.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Interfaces/IApiService.cs
  libs/net/services/Runners/BaseService.cs
  openshift/kustomize/services/content/base/deploy.yaml
  openshift/kustomize/services/content/overlays/dev/kustomization.yaml
  openshift/kustomize/services/content/overlays/prod/kustomization.yaml
  openshift/kustomize/services/content/overlays/test/kustomization.yaml
  services/net/content/ContentManager.cs
  services/net/content/ContentService.cs
Labels: enhancement, devops

#148 TNO-44 Fix token refresh
  libs/net/core/Http/OpenIdConnectRequestClient.cs
  openshift/kustomize/services/syndication/base/deploy.yaml
  openshift/kustomize/services/syndication/overlays/dev/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/prod/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/test/kustomization.yaml
Labels: bug

#137 Content List View Tests
  app/editor/__mocks__/styleMock.ts
  app/editor/package.json
  app/editor/src/features/content/list-view/ContentListView.test.tsx
  app/editor/src/features/content/list-view/__snapshots__/ContentListView.test.tsx.snap
  app/editor/src/test/utils/TestWrapper.tsx
  app/editor/src/test/utils/index.ts
  app/editor/src/test/utils/testData.ts
Labels: unit tests

#151 TNO-331, 334, 328
  app/editor/src/components/form/area/styled/Area.tsx
  app/editor/src/components/form/checkbox/styled/Checkbox.tsx
  app/editor/src/components/form/timeinput/TimeInput.tsx
  app/editor/src/components/form/timeinput/styled/TimeInput.tsx
  app/editor/src/components/formik/textarea/styled/FormikTextArea.ts
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#150 Getting java based capture service working with latest changes
  libs/java/service/src/main/java/ca/bc/gov/tno/services/data/TnoApi.java
  libs/java/service/src/main/java/ca/bc/gov/tno/services/models/DataSource.java
  services/java/capture/.devcontainer/devcontainer.json
  services/java/capture/src/main/resources/application.yml
  services/java/clip/src/main/resources/application.yml
Labels: bug

#153 TNO-302 Fix Clip Service
  app/editor/src/features/admin/AdminRouter.tsx
  app/editor/src/features/admin/sources/ContentReferenceList.tsx
  app/editor/src/features/admin/sources/DataSource.tsx
  app/editor/src/features/admin/sources/ReachEarnedMedia.tsx
  app/editor/src/features/admin/sources/services/ServiceIngestSettings.tsx
  app/editor/src/features/admin/sources/services/ServiceSchedule.tsx
  app/editor/src/features/admin/sources/services/index.ts
  app/editor/src/features/admin/sources/services/styled/ServiceIngestSettings.tsx
  app/editor/src/features/admin/sources/services/styled/index.ts
  app/editor/src/hooks/api-editor/validation/AdvancedScheduleSchema.ts
  libs/net/services/Managers/DataSourceManager`.cs
  openshift/kustomize/services/build/base/capture.yaml
  openshift/kustomize/services/build/base/clip.yaml
  openshift/kustomize/services/capture/base/config-map.yaml
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/services/capture/overlays/dev/kustomization.yaml
  openshift/kustomize/services/capture/overlays/prod/kustomization.yaml
  openshift/kustomize/services/capture/overlays/test/kustomization.yaml
  openshift/kustomize/services/clip/base/config-map.yaml
  openshift/kustomize/services/clip/base/deploy.yaml
  openshift/kustomize/services/clip/overlays/dev/kustomization.yaml
  openshift/kustomize/services/clip/overlays/prod/kustomization.yaml
  openshift/kustomize/services/clip/overlays/test/kustomization.yaml
  openshift/kustomize/services/syndication/base/deploy.yaml
  openshift/kustomize/services/syndication/overlays/dev/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/prod/kustomization.yaml
  openshift/kustomize/services/syndication/overlays/test/kustomization.yaml
  services/net/capture/CaptureDataSourceManager.cs
  services/net/clip/ClipAction.cs
Labels: bug, enhancement
