Repository bcgov/tno, pull requests merged in 2023-03, with the labels that each got.

#583 Fix TNO-1123
  libs/net/entities/Product.cs
  libs/net/models/Areas/Services/Models/Content/ContentModel.cs
  libs/net/models/Areas/Services/Models/Content/ProductModel.cs
Labels: bug

#585 Tag tweak
  app/editor/src/components/form/tags/Tags.tsx
Labels: bug

#586 TNO-1066: New image form
  app/editor/.yarn/cache/react-drag-drop-files-npm-2.3.9-f214d5d04f-7831b91e4a.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/components/form/tags/Tags.tsx
  app/editor/src/components/form/tags/styled/Tags.tsx
  app/editor/src/components/form/toning/ToningGroup.tsx
  app/editor/src/components/form/toning/styled/ToningGroup.tsx
  app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx
  app/editor/src/components/upload/Upload.tsx
  app/editor/src/components/upload/styled/Upload.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/ImageSection.tsx
  app/editor/src/features/content/form/MediaSummary.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
  app/editor/src/features/content/form/styled/ContentSummaryForm.tsx
  app/editor/src/features/content/form/styled/MediaSummary.tsx
  app/editor/src/features/content/form/styled/index.ts
  app/editor/src/features/content/tool-bar/sections/filter/CreateNewSection.tsx
  app/editor/src/features/content/validation/ContentFormSchema.ts
  app/editor/src/features/home/UnauthenticatedHome.tsx
  app/editor/yarn.lock
  app/subscriber/src/components/form/wysiwyg/styled/Wysiwyg.tsx
Labels: enhancement

#590 Fix API
  api/net/appsettings.Development.json
  libs/net/core/Converters/Int32ToStringJsonConverter.cs
  tools/scripts/gen-env-files.sh
Labels: bug

#588 Fix TNO-1018
  services/net/content/ContentManager.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#587 TNO-821: New tag input
  app/editor/.yarn/cache/react-draggable-npm-4.4.5-f5c4c58302-21c3775db0.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/components/form/tags/DraggableTagList.tsx
  app/editor/src/components/form/tags/Tags.tsx
  app/editor/src/components/form/tags/constants/columns.tsx
  app/editor/src/components/form/tags/styled/Tags.tsx
  app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/MediaSummary.tsx
  app/editor/src/features/content/form/styled/MediaSummary.tsx
  app/editor/yarn.lock
Labels: enhancement

#591 Styling tweak for tags
  app/editor/src/components/form/tags/Tags.tsx
Labels: bug

#592 Adjust height for print content
  app/editor/src/components/form/tags/Tags.tsx
Labels: bug

#594 Fix console warning for draggable component
  app/editor/src/components/form/tags/DraggableTagList.tsx
  app/editor/src/features/content/form/MediaSummary.tsx
Labels: bug

#593 Fix TNO-847
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
Labels: enhancement

#595 Remove junk
  app/editor/src/features/testsss/styled/NavBarGroup.tsx
Labels: bug

#596 Fix TNO-1011
  services/net/content/ContentManager.cs
Labels: bug

#599 Fix TNO-1079
  libs/net/services/Managers/IngestManager`.cs
Labels: bug

#603 TNO-843 Fix 1.0.6 elastic migration
  libs/net/dal/Elasticsearch/TNOElasticClient.cs
  libs/net/dal/Services/ContentService.cs
  libs/net/entities/ContentTopic.cs
  libs/net/models/Areas/Editor/Models/Content/ContentTopicModel.cs
  libs/net/models/Areas/Services/Models/Content/ContentTopicModel.cs
  services/net/capture/Dockerfile
  services/net/clip/Dockerfile
  services/net/command/Dockerfile
  services/net/content/Dockerfile
  services/net/filecopy/Dockerfile
  services/net/filemonitor/Dockerfile
  services/net/image/Dockerfile
  services/net/indexing/Dockerfile
  services/net/indexing/IndexingManager.cs
  services/net/indexing/TNO.Services.Indexing.csproj
  services/net/nlp/Dockerfile
  services/net/syndication/Dockerfile
  services/net/transcription/Dockerfile
  tools/elastic/migration/Config/ElasticMigrationOptions.cs
  tools/elastic/migration/Migration.cs
  tools/elastic/migration/MigrationBuilder.cs
  tools/elastic/migration/MigrationService.cs
  tools/elastic/migration/Migrations/1.0.6.cs
  tools/elastic/migration/Migrations/1.0.6/down/pre/00-pipeline-content.json
  tools/elastic/migration/Migrations/1.0.6/down/pre/01-index-unpublished_content.json
  tools/elastic/migration/Migrations/1.0.6/down/pre/02-reindex-unpublished_content.json
  tools/elastic/migration/Migrations/1.0.6/down/pre/03-index-content.json
  tools/elastic/migration/Migrations/1.0.6/down/pre/04-reindex-content.json
  tools/elastic/migration/Migrations/1.0.6/down/pre/05-alias-content.json
  tools/elastic/migration/Migrations/1.0.6/down/pre/05-alias-unpublished_content.json
  tools/elastic/migration/Migrations/1.0.6/down/pre/05-delete-alias-content.json
  tools/elastic/migration/Migrations/1.0.6/down/pre/06-delete-alias-unpublished_content copy.json
  tools/elastic/migration/Migrations/1.0.6/up/pre/00-pipeline-content.json
  tools/elastic/migration/Migrations/1.0.6/up/pre/01-index-unpublished_content.json
  tools/elastic/migration/Migrations/1.0.6/up/pre/02-reindex-unpublished_content.json
  tools/elastic/migration/Migrations/1.0.6/up/pre/03-index-content.json
  tools/elastic/migration/Migrations/1.0.6/up/pre/04-reindex-content.json
  tools/elastic/migration/Migrations/1.0.6/up/pre/05-alias-content.json
  tools/elastic/migration/Migrations/1.0.6/up/pre/05-alias-unpublished_content.json
  tools/elastic/migration/Migrations/1.0.6/up/pre/05-delete-alias-content.json
  tools/elastic/migration/Migrations/1.0.6/up/pre/06-delete-alias-unpublished_content copy.json
  tools/elastic/migration/Models/MigrationAction.cs
  tools/elastic/migration/Program.cs
  tools/elastic/migration/TNO.Elastic.Migration.csproj
  tools/elastic/migration/TNOElasticClient.cs
  tools/elastic/migration/TNOMigration.cs
Labels: bug

#604 Fix TNO-664
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/MediaSummary.tsx
Labels: bug, enhancement

#605 TNO-843 Fix topic admin
  app/editor/src/features/admin/topic-score-rules/TopicScoreRuleList.tsx
  app/editor/src/features/admin/topic-score-rules/validation/TopicScoreRuleSchema.ts
  app/editor/src/features/admin/topic-score-rules/validation/TopicScoreRulesSchema.ts
  app/editor/src/features/admin/topic-score-rules/validation/index.ts
  app/editor/src/features/admin/topics/TopicForm.tsx
  app/editor/src/features/admin/topics/TopicList.tsx
  app/editor/src/features/admin/topics/validation/TopicSchema.ts
  app/editor/src/features/admin/topics/validation/index.ts
Labels: bug

#606 TNO-629 Fix topic score calculation
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/TopicForm.tsx
  app/editor/src/features/content/form/index.tsx
  app/editor/src/features/content/form/styled/ContentStoryForm.tsx
  app/editor/src/features/content/form/styled/index.ts
  app/editor/src/features/content/form/utils/calcTopicScore.ts
  libs/net/models/Areas/Editor/Models/TopicScoreRule/TopicScoreRuleModel.cs
Labels: bug

#607 TNO-1162 Fix transcription service
  libs/net/models/Areas/Services/Models/Content/ContentTagModel.cs
Labels: bug

#608 TNO-1162 Fix Transcript Tab and Tags
  app/editor/src/features/content/form/ContentTranscriptForm.tsx
  app/editor/src/features/content/form/styled/ContentTranscriptForm.tsx
Labels: bug

#602 Fix TNO-1048
  libs/net/ches/ChesService.cs
  libs/net/core/Http/HttpRequestClient.cs
  libs/net/core/Http/IHttpRequestClient.cs
  libs/net/css/CssClient.cs
  libs/net/dal/TNOContext.cs
  libs/net/services/Actions/IngestAction.cs
  libs/net/services/Actions/Managers/IngestActionManager`.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Interfaces/IApiService.cs
  libs/net/services/Managers/ServiceManager`.cs
  services/net/content/ContentManager.cs
  services/net/indexing/IndexingManager.cs
  services/net/nlp/NLPManager.cs
  services/net/transcription/TranscriptionManager.cs
Labels: bug

#609 TNO-1140 Fix content filter state
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/morning-report/AdvancedMorningReport.tsx
  app/editor/src/features/content/tool-bar/ContentToolBar.tsx
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Labels: bug

#611 Fix TNO-1048 #2
  libs/net/core/Http/HttpRequestClient.cs
Labels: bug

#612 Fix TNO-1154
  services/net/filemonitor/FilemonitorAction.cs
Labels: bug

#618 Fix TNO-1152
  services/net/clip/ClipAction.cs
Labels: bug

#621 Fix content filter
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/admin/users/UserList.tsx
  app/editor/src/features/content/tool-bar/sections/filter/ShowOnlySection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/hooks/useShowOnlyContentType.ts
Labels: bug

#617 TNO-931, TNO-1158: Default selected for a.m report
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/morning-report/MorningReportFilter.tsx
  app/editor/src/features/content/morning-report/constants/defaultReportFilter.ts
  app/editor/src/features/content/morning-report/filter-sections/FilteredContentSection.tsx
Labels: bug

#625 Fix services
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Interfaces/IApiService.cs
Labels: bug

#627 Fix TNO-664 #2
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
  app/editor/src/features/content/validation/ContentFormSchema.ts
  libs/npm/core/src/components/flex/col/styled/Col.tsx
  libs/npm/core/src/components/flex/row/styled/Row.tsx
Labels: bug, enhancement

#629 TNO-1117 Add CC script
  tools/scripts/cc.sh
Labels: enhancement

#631 Fix TNO-1048 #3
  libs/net/dal/TNOContext.cs
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/image/ImageAction.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#636 Fix TNO-849
  app/editor/src/features/content/form/ContentForm.tsx
Labels: enhancement

#637 Fix TNO-1075
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/ContentTranscriptForm.tsx
Labels: bug

#639 TNO-1186: Hitting search wipes toggle group state
  app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
Labels: bug

#640 Product filter bugs
  app/editor/src/features/content/tool-bar/sections/filter/InputOption.tsx
  app/editor/src/features/content/tool-bar/sections/filter/styled/SelectLabel.tsx
  app/editor/src/features/content/tool-bar/sections/filter/styled/index.ts
Labels: bug

#641 Restructure Subscriber
  app/subscriber/src/components/footer/SubscriberFooter.tsx
  app/subscriber/src/components/footer/index.ts
  app/subscriber/src/components/footer/styled/SubscriberFooter.tsx
  app/subscriber/src/components/footer/styled/index.ts
  app/subscriber/src/components/layout/DefaultLayout.tsx
  app/subscriber/src/features/home/InfoPanel.tsx
  app/subscriber/src/features/home/InfoText.tsx
  app/subscriber/src/features/home/LogoPanel.tsx
  app/subscriber/src/features/home/index.ts
  app/subscriber/src/features/home/login/styled/index.ts
  app/subscriber/src/features/home/styled/InfoPanel.tsx
  app/subscriber/src/features/home/styled/LogoPanel.tsx
  app/subscriber/src/features/home/styled/index.ts
  app/subscriber/src/features/landing/Landing.tsx
  app/subscriber/src/features/landing/index.ts
  app/subscriber/src/features/landing/styled/Landing.tsx
  app/subscriber/src/features/landing/styled/index.ts
  app/subscriber/src/features/login/BrowserLogin.tsx
  app/subscriber/src/features/login/MobileLogin.tsx
  app/subscriber/src/features/login/UnauthenticatedHome.tsx
  app/subscriber/src/features/login/index.ts
  app/subscriber/src/features/login/styled/BrowserLogin.tsx
  app/subscriber/src/features/login/styled/MobileLogin.tsx
  app/subscriber/src/features/login/styled/UnauthenticatedHome.tsx
  app/subscriber/src/features/login/styled/index.ts
  app/subscriber/src/features/router/AppRouter.tsx
Labels: tech debt

#642 Remove @types/yup from subscriber
  app/subscriber/.yarn/cache/@types-yup-npm-0.32.0-e4c93584ed-5b30f1118b.zip
  app/subscriber/package.json
  app/subscriber/tsconfig.json
  app/subscriber/yarn.lock
Labels: tech debt

#643 Update make pack script
  libs/npm/core/Makefile
  libs/npm/core/scripts/package.sh
Labels: enhancement

#645 Fix advanced source filter
  app/editor/src/features/content/list-view/constants/fieldTypes.ts
  app/editor/src/features/content/morning-reports/components/AdvancedFilter.tsx
  app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
Labels: bug

#646 Fix product filter
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Labels: bug

#647 TNO-1177 Fix paper ingest
  app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
  app/editor/tno-core-0.0.226.tgz
  services/net/filemonitor/FilemonitorAction.cs
Labels: bug

#638 Fix TNO-1053
  libs/npm/core/src/components/grid-table/GridTable.tsx
Labels: bug
