Repository bcgov/tno, pull requests merged in 2023-09, with the labels that each got.

#1028 Fix subscriber report model
  libs/net/core/Extensions/JsonElementExtensions.cs
  libs/net/dal/Migrations/1.0.54/Up/PostUp/02-Ingest.sql
  libs/npm/core/src/components/table/interfaces/TableInternal.ts
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/migrators/ContentMigrator.cs
  services/net/contentmigration/migrators/IContentMigrator.cs
Labels: bug

#1030 fix: #tno-1734 - tweaked bash script portion
  openshift/kustomize/cron/base/config-map.yaml
Labels: bug

#1031 TNO-1502: [QA] Pls increase default pop out Story window size to 90-95% of editor's screen view
  app/editor/package.json
  app/editor/src/components/wysiwyg/Wysiwyg.tsx
  app/editor/src/components/wysiwyg/styled/Wysiwyg.tsx
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/ContentTranscriptForm.tsx
  app/editor/src/index.scss
  app/subscriber/package.json
  libs/npm/core/package.json
  libs/npm/core/src/components/modal/Modal.tsx
  libs/npm/core/src/components/modal/styled/Modal.tsx
  libs/npm/core/src/hooks/useWindowSize.tsx
Labels: enhancement, tno-core update

#1032 TNO-1584 Add services pipeline
  openshift/kustomize/tekton/base/pipelines/buildah-all.yaml
  openshift/kustomize/tekton/base/tasks/build-all.yaml
  openshift/kustomize/tekton/base/tasks/deploy-all.yaml
  openshift/kustomize/tekton/base/tasks/git-conditions.yaml
  openshift/kustomize/tekton/base/triggers/listener.yaml
  openshift/kustomize/tekton/base/triggers/template.yaml
  openshift/monitoring/sysdig/tno-sysdig-access.yaml
  openshift/templates/tekton/service-account/role.yaml
Labels: devops

#1033 TNO-1615 Add master pipeline
  openshift/kustomize/tekton/base/pipelines/buildah-all.yaml
  openshift/kustomize/tekton/base/tasks/git-conditions.yaml
  openshift/kustomize/tekton/base/triggers/dev/binding.yaml
  openshift/kustomize/tekton/base/triggers/dev/ingress.yaml
  openshift/kustomize/tekton/base/triggers/dev/listener.yaml
  openshift/kustomize/tekton/base/triggers/template.yaml
  openshift/kustomize/tekton/base/triggers/test/binding.yaml
  openshift/kustomize/tekton/base/triggers/test/ingress.yaml
  openshift/kustomize/tekton/base/triggers/test/listener.yaml
Labels: devops

#1026 TNO-1705: Advanced search bugs
  app/subscriber/public/constants.json
  app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx
  app/subscriber/src/components/sidebar/advanced-search/components/MoreOptions.tsx
  app/subscriber/src/components/sidebar/advanced-search/constants/DefaultAdvancedSearch.ts
  app/subscriber/src/components/sidebar/advanced-search/interfaces/IAdvancedSearchFilter.ts
  app/subscriber/src/components/sidebar/advanced-search/utils/queryToState.ts
  app/subscriber/src/features/content/list-view/interfaces/IContentListFilter.ts
  app/subscriber/src/features/home/utils/makeFilter.ts
  app/subscriber/src/features/search-page/SearchPage.tsx
Labels: bug

#1037 TNO-1713: In the online form, content is not...
  app/editor/src/features/content/form/ContentStoryForm.tsx
Labels: bug

#1038 TNO-504 Configure Kafka partitions
  app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
  db/kafka/README.md
  openshift/kustomize/kafka/broker/base/config-map.yaml
  tools/scripts/gen-env-files.sh
Labels: devops

#1036 TNO-1707: Link to subscriber
  app/editor/src/features/content/form/components/tool-bar/ContentFormToolBar.tsx
  app/editor/src/features/content/form/components/tool-bar/form/PublishedSection.tsx
  app/editor/src/features/content/form/components/tool-bar/form/index.ts
  app/editor/src/features/content/form/components/tool-bar/form/styled/PublishedSection.tsx
  app/editor/src/features/content/form/components/tool-bar/form/styled/index.ts
Labels: enhancement, editor

#1039 feat: #tno-1769 - added more logging to migration
  libs/net/models/Areas/Services/Models/ContentReference/ContentReferenceModel.cs
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/migrators/ContentMigrator.cs
Labels: enhancement

#1041 TNO-1755: A/V form & Image form: Pop out editor...
  app/editor/src/components/wysiwyg/Wysiwyg.tsx
Labels: bug

#1042 TNO-1722: Remove My Collections Menu
  app/subscriber/src/components/layout/constants/SidebarMenuItems.tsx
Labels: enhancement, subscriber

#1043 TNO-1723 Deploy scheduler
  libs/net/dal/Migrations/1.0.64/Up/PostUp/00-EventSchedule.sql
  openshift/kustomize/services/scheduler/base/config-map.yaml
  openshift/kustomize/services/scheduler/base/deploy.yaml
  openshift/kustomize/services/scheduler/base/kustomization.yaml
  openshift/kustomize/services/scheduler/base/service.yaml
  openshift/kustomize/services/scheduler/overlays/dev/kustomization.yaml
  openshift/kustomize/services/scheduler/overlays/prod/kustomization.yaml
  openshift/kustomize/services/scheduler/overlays/test/kustomization.yaml
  openshift/kustomize/tekton/base/tasks/deploy-all.yaml
  openshift/kustomize/tekton/base/triggers/dev/binding.yaml
  openshift/kustomize/tekton/base/triggers/template.yaml
  openshift/kustomize/tekton/base/triggers/test/binding.yaml
Labels: devops

#1044 TNO-1723 Enable report preview
  api/net/Areas/Editor/Controllers/ReportController.cs
  api/net/Areas/Editor/Controllers/ReportInstanceController.cs
  api/net/Areas/Subscriber/Controllers/ReportController.cs
  app/editor/src/features/admin/reports/ReportForm.tsx
  openshift/kustomize/services/capture/base/kustomization.yaml
  openshift/kustomize/services/clip/base/kustomization.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-all.yaml
  openshift/kustomize/tekton/base/triggers/dev/binding.yaml
  openshift/kustomize/tekton/base/triggers/template.yaml
  openshift/kustomize/tekton/base/triggers/test/binding.yaml
  services/net/scheduler/SchedulerManager.cs
Labels: bug, enhancement, devops, editor

#1045 feat: #tno-1737 - changed keywords search
  app/editor/src/features/admin/filters/FilterFormQuery.tsx
  app/editor/src/features/admin/filters/utils/generateQuery.ts
  app/editor/src/features/admin/filters/utils/generateSimpleQueryString.ts
  app/editor/src/features/admin/filters/utils/index.ts
Labels: enhancement

#1049 TNO-1752 Add Content.PostedOn
  Makefile
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Services/Controllers/ContentController.cs
  app/editor/.yarn/cache/tno-core-file-a74088131b-4d00cd2425.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.312-15ff4660fa-3bf73df989.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/admin/reports/ReportFormSections.tsx
  app/editor/src/features/admin/reports/constants/defaultReport.ts
  app/editor/yarn.lock
  app/subscriber/.yarn/cache/tno-core-npm-0.0.312-15ff4660fa-3bf73df989.zip
  app/subscriber/.yarn/cache/tno-core-npm-0.0.314-45019a47d0-3644368cf1.zip
  app/subscriber/package.json
  app/subscriber/yarn.lock
  libs/net/dal/Configuration/ContentConfiguration.cs
  libs/net/dal/Migrations/1.0.65/Up/PostUp/00-Content.sql
  libs/net/dal/Migrations/20230912211444_1.0.65.Designer.cs
  libs/net/dal/Migrations/20230912211444_1.0.65.cs
  libs/net/dal/Services/ContentService.cs
  libs/net/dal/Services/Interfaces/IReportService.cs
  libs/net/dal/Services/ReportService.cs
  libs/net/entities/Content.cs
  libs/net/models/Areas/Editor/Models/Content/ContentModel.cs
  libs/net/models/Areas/Editor/Models/ReportInstance/ReportInstanceContentModel.cs
  libs/net/models/Areas/Services/Models/Content/ContentModel.cs
  libs/net/models/Areas/Services/Models/ReportInstance/ContentModel.cs
  libs/net/models/Settings/ReportContentSettingsModel.cs
  libs/npm/core/package.json
  libs/npm/core/src/hooks/api-editor/interfaces/IReportContentSettingsModel.ts
  openshift/kustomize/tekton/base/tasks/build-all.yaml
  services/net/indexing/IndexingManager.cs
  services/net/reporting/ReportingManager.cs
  tools/elastic/migration/Migrations/1.0.8.cs
  tools/elastic/migration/Migrations/1.0.8/up/post/00-update-unpublished_content.json
  tools/elastic/migration/Migrations/1.0.8/up/post/01-update-content.json
Labels: bug, enhancement, DB Migration, devops, Elastic Migration, tno-core update, editor

#1048 TNO-1716: Change max commentary returned
  app/subscriber/src/features/commentary/Commentary.tsx
  app/subscriber/src/features/commentary/styled/Commentary.tsx
  app/subscriber/src/features/search-page/SearchPage.tsx
Labels: bug, subscriber

#1047 TNO-1756: if adding square brackets into story...
  app/editor/src/components/wysiwyg/Wysiwyg.tsx
Labels: bug, editor

#1050 feat: #tno-1771 - add new migrator
  app/editor/src/features/admin/ingests/configurations/DbMigration.tsx
  libs/net/dal/Migrations/1.0.66/Down/PostDown/00-IngestDataLocation.sql
  libs/net/dal/Migrations/1.0.66/Down/PostDown/00-Schedule.sql
  libs/net/dal/Migrations/1.0.66/Down/PostDown/01-IngestSchedule.sql
  libs/net/dal/Migrations/1.0.66/Down/PostDown/02-Ingest.sql
  libs/net/dal/Migrations/1.0.66/Up/PostUp/01-Schedule.sql
  libs/net/dal/Migrations/1.0.66/Up/PostUp/02-Ingest.sql
  libs/net/dal/Migrations/1.0.66/Up/PostUp/03-IngestDataLocation.sql
  libs/net/dal/Migrations/1.0.66/Up/PostUp/03-IngestSchedule.sql
  libs/net/dal/Migrations/20230913173415_1.0.66.Designer.cs
  libs/net/dal/Migrations/20230913173415_1.0.66.cs
  libs/net/models/Extensions/IngestModelExtensions.cs
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/migrators/ClipMigrator.cs
  services/net/contentmigration/migrators/ContentMigrator.cs
Labels: enhancement, DB Migration

#1051 TNO-1766: Re-label Evening Overview
  app/editor/src/features/admin/AdminRouter.tsx
  app/editor/src/features/admin/av-overviews/AVOverview.tsx
  app/editor/src/features/navbar/NavBar.tsx
  app/editor/src/features/reports/av-overview/AVOverview.tsx
  app/editor/src/features/reports/av-overview/AVOverviewPreview.tsx
  app/editor/src/features/router/AppRouter.tsx
  test/TNO.postman_collection.json
Labels: enhancement, tno-core update, editor

#1052 TNO-1727: Create new Folder Validation
  app/subscriber/src/features/my-folders/MyFolders.tsx
Labels: enhancement, subscriber

#1054 feat: #tno-1773 - modified PerformActionAsync
  libs/net/services/Actions/IngestAction.cs
  libs/net/services/Actions/Managers/ServiceActionManager`.cs
  libs/net/services/Actions/ServiceAction.cs
  libs/net/services/Actions/ServiceActionResult.cs
  libs/net/services/Interfaces/IIngestAction`.cs
  libs/net/services/Interfaces/IServiceAction`.cs
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/clip/ClipIngestActionManager.cs
  services/net/command/CommandAction`.cs
  services/net/command/CommandIngestActionManager`.cs
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/filemonitor/FilemonitorAction.cs
  services/net/image/ImageAction.cs
  services/net/syndication/SyndicationAction.cs
Labels: enhancement

#1056 TNO-1726: Confirm Deleting Folder
  app/subscriber/src/features/my-folders/MyFolders.tsx
Labels: enhancement, subscriber

#1057 Fix bug for published link
  app/editor/src/features/content/form/components/tool-bar/ContentFormToolBar.tsx
Labels: bug

#1058 AV Overview - Date filter bugs
  app/editor/src/features/reports/av-overview/OverviewGrid.tsx
Labels: bug

#1062 Quick fix
  app/editor/src/features/reports/av-overview/OverviewGrid.tsx
Labels: bug

#1059 TNO-1742: Move the Generate Elasticsearch Query...
  app/editor/package.json
  app/editor/src/features/admin/filters/FilterFormQuery.tsx
  app/editor/src/features/admin/filters/utils/index.ts
  app/subscriber/package.json
  libs/npm/core/package.json
  libs/npm/core/src/components/index.ts
  libs/npm/core/src/hooks/api-subscriber/index.ts
  libs/npm/core/src/hooks/api-subscriber/useApiSubscriberReports.ts
  libs/npm/core/src/utils/generateQuery.ts
  libs/npm/core/src/utils/generateQueryForAction.ts
  libs/npm/core/src/utils/generateQueryForActions.ts
  libs/npm/core/src/utils/generateRangeForArrayField.ts
  libs/npm/core/src/utils/generateRangeForDateOffset.ts
  libs/npm/core/src/utils/generateRangeForDates.ts
  libs/npm/core/src/utils/generateSimpleQueryString.ts
  libs/npm/core/src/utils/generateTerm.ts
  libs/npm/core/src/utils/generateTerms.ts
  libs/npm/core/src/utils/generateTermsForArrayField.ts
  libs/npm/core/src/utils/index.ts
Labels: enhancement, tno-core update, editor

#1064 Reduce memory usage - redux
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/list-view/constants/defaultPage.ts
  app/editor/src/features/content/papers/Papers.tsx
  app/editor/src/features/content/papers/components/ReportActions.tsx
  app/editor/src/features/content/papers/constants/columns.tsx
  app/editor/src/store/slices/content/contentSlice.ts
  app/editor/src/store/slices/content/interfaces/IContentSearchResult.ts
  app/editor/src/store/slices/content/interfaces/IContentState.ts
  app/editor/src/store/slices/content/interfaces/index.ts
  app/editor/src/store/slices/content/utils/castContentToSearchResult.ts
  app/editor/src/store/slices/content/utils/index.ts
Labels: enhancement, editor

#1065 Add cron backup
  openshift/kustomize/cron/backup/base/config-map.yaml
  openshift/kustomize/cron/backup/base/cron-job.yaml
  openshift/kustomize/cron/backup/base/kustomization.yaml
  openshift/kustomize/cron/backup/base/pvc.yaml
  openshift/kustomize/cron/backup/overlays/dev/kustomization.yaml
  openshift/kustomize/cron/backup/overlays/prod/kustomization.yaml
  openshift/kustomize/cron/backup/overlays/test/kustomization.yaml
  openshift/kustomize/cron/purge/base/config-map.yaml
  openshift/kustomize/cron/purge/base/cron-job.yaml
  openshift/kustomize/cron/purge/base/kustomization.yaml
  openshift/kustomize/cron/purge/overlays/dev/kustomization.yaml
  openshift/kustomize/cron/purge/overlays/prod/kustomization.yaml
  openshift/kustomize/cron/purge/overlays/test/kustomization.yaml
Labels: devops

#1067 TNO-1135 Fix my folders
  app/subscriber/src/features/content/view-content/FolderMenu.tsx
  libs/net/dal/Services/FolderService.cs
Labels: bug

#1066 Remove tooltip from list view
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/papers/constants/columns.tsx
Labels: enhancement

#1069 TNO-1743: Add content from list view
  app/subscriber/src/components/date-filter/DateFilter.tsx
  app/subscriber/src/features/content/view-content/FolderMenu.tsx
  app/subscriber/src/features/content/view-content/ViewContent.tsx
  app/subscriber/src/features/content/view-content/ViewContentToolbar.tsx
  app/subscriber/src/features/home/Home.tsx
  app/subscriber/src/features/home/constants/columns.tsx
  app/subscriber/src/features/home/styled/Home.tsx
  app/subscriber/src/features/my-minister/MyMinister.tsx
  app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
  app/subscriber/src/features/top-stories/TopStories.tsx
Labels: enhancement

#1070 TNO-1744, 1745, 1746: Add content to folder from Today's Commentary, Top Stories, and My Ministers
  app/subscriber/src/components/folder-sub-menu/FolderSubMenu.tsx
  app/subscriber/src/components/folder-sub-menu/index.ts
  app/subscriber/src/components/folder-sub-menu/styled/FolderSubMenu.tsx
  app/subscriber/src/components/folder-sub-menu/styled/index.ts
  app/subscriber/src/features/content/view-content/ViewContentToolbar.tsx
  app/subscriber/src/features/home/Home.tsx
  app/subscriber/src/features/home/styled/Home.tsx
  app/subscriber/src/features/my-minister/MyMinister.tsx
  app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
  app/subscriber/src/features/top-stories/TopStories.tsx
Labels: enhancement, subscriber

#1068 TNO-1740: Extend Filter Keywords Text Input...
  app/editor/src/features/admin/filters/FilterFormQuery.tsx
  libs/npm/core/src/utils/generateQuery.ts
  libs/npm/core/src/utils/generateSimpleQueryString.ts
Labels: enhancement, tno-core update

#1071 TNO-1748: Add content to folder from search
  app/subscriber/src/components/folder-sub-menu/FolderSubMenu.tsx
  app/subscriber/src/features/home/utils/DetermineToneIcon.tsx
  app/subscriber/src/features/search-page/SearchPage.tsx
  app/subscriber/src/features/search-page/styled/SearchPage.tsx
Labels: enhancement

#1075 Toast error when no content selected
  app/subscriber/src/features/content/view-content/FolderMenu.tsx
Labels: bug, subscriber

#1076 Bugs from Sprint Review
  app/editor/.yarn/install-state.gz
  app/subscriber/src/components/layout/styled/Layout.tsx
  app/subscriber/src/features/my-folders/constants/columns.tsx
  app/subscriber/src/features/my-folders/styled/MyFolders.tsx
  app/subscriber/src/features/search-page/styled/SearchPage.tsx
Labels: bug, subscriber

#1077 TNO-1724 Update My Reports
  app/editor/src/features/admin/reports/ReportFormDetails.tsx
  app/subscriber/src/features/my-reports/admin/ReportAdminSettings.tsx
  app/subscriber/src/features/my-reports/hooks/useColumns.tsx
  app/subscriber/src/features/my-reports/styled/MyReports.tsx
Labels: enhancement, subscriber

#1074 TNO-1717: Add isPress and Aliases to the Contributor
  api/net/Areas/Subscriber/Controllers/LookupController.cs
  app/editor/.yarn/cache/tno-core-npm-0.0.320-260509195e-122f55da5d.zip
  app/editor/.yarn/cache/tno-core-npm-0.0.321-f9c2e36a88-9b7ea6d603.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/admin/contributors/ContributorForm.tsx
  app/editor/src/features/admin/contributors/constants/columns.tsx
  app/editor/src/features/admin/contributors/constants/defaultContributor.ts
  app/editor/src/features/admin/contributors/styled/ContributorForm.tsx
  app/editor/tno-core-0.0.317.tgz
  app/editor/yarn.lock
  app/subscriber/.yarn/cache/tno-core-npm-0.0.320-260509195e-122f55da5d.zip
  app/subscriber/.yarn/cache/tno-core-npm-0.0.321-f9c2e36a88-9b7ea6d603.zip
  app/subscriber/package.json
  app/subscriber/src/features/landing/Landing.tsx
  app/subscriber/src/features/press-gallery/PressGallery.tsx
  app/subscriber/src/features/press-gallery/index.ts
  app/subscriber/src/features/press-gallery/styled/PressGallery.tsx
  app/subscriber/src/features/press-gallery/styled/index.ts
  app/subscriber/src/store/hooks/lookup/useLookup.ts
  app/subscriber/yarn.lock
  libs/net/dal/Configuration/ContributorConfiguration.cs
  libs/net/dal/Migrations/20230921224306_1.0.69.Designer.cs
  libs/net/dal/Migrations/20230921224306_1.0.69.cs
  libs/net/entities/Contributor.cs
  libs/net/models/Areas/Admin/Contributor/ContributorModel.cs
  libs/net/models/Areas/Subscriber/Models/Content/ContributorModel.cs
  libs/net/models/Areas/Subscriber/Models/Lookup/LookupModel.cs
  libs/npm/core/package.json
  libs/npm/core/src/hooks/api-editor/interfaces/IContributorModel.ts
Labels: DB Migration, tno-core update, editor

#1080 TNO-1790: Top Story checkbox
  app/editor/src/features/content/form/components/tool-bar/form/ActionSection.tsx
  libs/net/dal/Migrations/1.0.70/Up/PostUp/00-ContentTypeAction.sql
  libs/net/dal/Migrations/20230923003357_1.0.70.Designer.cs
  libs/net/dal/Migrations/20230923003357_1.0.70.cs
  libs/net/dal/Migrations/Initial/Up/PostUp/01-ContentTypeAction.sql
Labels: enhancement, DB Migration, editor

#1078 TNO-1800: Filter keyword search should default...
  app/editor/package.json
  app/subscriber/package.json
  libs/npm/core/package.json
  libs/npm/core/src/utils/generateSimpleQueryString.ts
Labels: bug, tno-core update

#1082 feat: #tno-1825 - uncommented code to fix
  services/net/contentmigration/Config/ContentMigrationOptions.cs
  services/net/contentmigration/migrators/ContentMigrator.cs
Labels: enhancement

#1081 feat: #tno-1780 - added missing mappings
  services/net/contentmigration/appsettings.json
Labels: enhancement

#1083 TNO-1452: [QA] 1) remove mandatory field from...
  app/editor/src/features/content/form/components/topic/Topic.tsx
Labels: enhancement, editor

#1085 TNO-1793: Transcript Request button - client side
  app/subscriber/src/features/content/view-content/styled/ViewContent.tsx
Labels: enhancement, subscriber

#1087 fix: #tno-1550 - moved options for easier control
  libs/net/template/Config/ReportingOptions.cs
  openshift/kustomize/services/notification/base/deploy.yaml
  openshift/kustomize/services/reporting/base/deploy.yaml
  openshift/kustomize/services/reporting/overlays/dev/config-map.yaml
  openshift/kustomize/services/reporting/overlays/prod/config-map.yaml
  openshift/kustomize/services/reporting/overlays/test/config-map.yaml
  services/net/notification/Config/NotificationOptions.cs
  services/net/notification/NotificationManager.cs
  services/net/notification/NotificationService.cs
  services/net/notification/appsettings.Development.json
  services/net/notification/appsettings.Staging.json
Labels: bug

#1090 Fix multi-tab
  app/editor/src/components/tab-control/TabControl.tsx
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug

#1092 fix: #tno-1828 - fixed logic update preventing Status from getting set
  services/net/content/ContentManager.cs
  services/net/contentmigration/ContentMigrationAction.cs
Labels: bug

#1096 TNO-1437 Fix Page Sort
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/AdvancedSearchSection.tsx
  app/editor/src/features/content/list-view/constants/AdvancedSearchKeys_.ts
  app/editor/src/features/content/list-view/constants/advancedSearchOptions.ts
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/list-view/constants/index.ts
  app/editor/src/features/content/list-view/hooks/index.ts
  app/editor/src/features/content/list-view/hooks/useColumns.tsx
  app/editor/src/features/content/list-view/interfaces/IContentListAdvancedFilter.ts
  app/editor/src/features/content/list-view/utils/applySortBy.ts
  app/editor/src/features/content/papers/PaperFilter.tsx
  app/editor/src/features/content/papers/Papers.tsx
  app/editor/src/features/content/papers/components/AdvancedFilter.tsx
  app/editor/src/features/content/papers/constants/PublishedStatuses.ts
  app/editor/src/features/content/papers/constants/columns.tsx
  app/editor/src/features/content/papers/constants/index.ts
  app/editor/src/features/content/papers/hooks/index.ts
  app/editor/src/features/content/papers/hooks/useColumns.tsx
  app/editor/src/features/content/papers/utils/changeStatus.ts
  app/editor/src/features/content/papers/utils/index.ts
  app/editor/src/store/slices/content/contentSlice.ts
  app/editor/src/store/slices/content/useContentStore.ts
  libs/net/dal/Services/ContentService.cs
Labels: bug, enhancement, editor

#1098 feat: #tno-1828 - updated ContentManager
  services/net/content/ContentManager.cs
Labels: bug

#1099 TNO-1788 Change Publish Flow
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/MediaSummary.tsx
  app/editor/src/features/content/form/components/time-log/TimeLogSection.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
  libs/npm/core/src/components/form/area/Area.tsx
Labels: enhancement, editor

#1100 TNO-1739 Fix MOV Format
  api/net/.devcontainer/devcontainer.json
  app/editor/.devcontainer/devcontainer.json
  app/editor/src/components/status/Status.tsx
  app/editor/src/components/status/index.ts
  app/editor/src/css/_colors.scss
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/components/tool-bar/form/StatusSection.tsx
  app/editor/src/features/content/list-view/hooks/useColumns.tsx
  app/editor/src/features/content/papers/Papers.tsx
  app/editor/src/features/content/papers/hooks/useColumns.tsx
  app/editor/src/index.scss
  app/subscriber/.devcontainer/devcontainer.json
  libs/net/.devcontainer/devcontainer.json
  services/net/.devcontainer/Dockerfile
  services/net/.devcontainer/devcontainer.json
  services/net/transcription/Config/TranscriptionOptions.cs
  services/net/transcription/TranscriptionManager.cs
  services/net/transcription/appsettings.json
  tools/import/.devcontainer/devcontainer.json
Labels: bug, enhancement, editor

#1101 TNO-1785 Fix m4a transcription
  services/net/transcription/appsettings.json
Labels: bug

#1104 fix: #tno-1828 - fix missing properties
  services/net/content/ContentManager.cs
Labels: bug

#1102 TNO-1493: The A/V player on the Content Form...
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/MediaSummary.tsx
  app/editor/src/features/content/form/components/upload/Upload.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
Labels: enhancement, editor

#1103 TNO-1797: Colour code Subscriber environments...
  app/subscriber/src/components/sidebar/styled/CustomSidebar.tsx
  app/subscriber/src/css/_colors.scss
  app/subscriber/src/css/_variables.module.scss
  app/subscriber/src/env.json
Labels: enhancement, subscriber

#1106 fix: #tno-1836 - save settings as json document
  libs/net/models/Areas/Admin/Filter/FilterModel.cs
Labels: bug

#1107 feat: #tno-1837 - updated reports sections display
  app/editor/src/features/admin/reports/ReportFormSections.tsx
  app/editor/src/features/admin/reports/styled/ReportSections.tsx
Labels: enhancement
