Repository bcgov/tno, pull requests merged in 2023-04, with the labels that each got.

#649 TNO-1188 Refersh DEV env
  api/net/Middleware/ErrorHandlingMiddleware.cs
  app/editor/src/features/content/morning-reports/MorningReports.tsx
  db/elasticsearch/Dockerfile
  libs/net/dal/Services/ContentService.cs
  openshift/kustomize/api/base/config-map.yaml
  openshift/kustomize/api/base/deploy.yaml
  openshift/kustomize/api/base/pvc.yaml
  openshift/kustomize/api/base/statefulset.yaml
  openshift/kustomize/api/build/overlays/jmf/kustomization.yaml
  openshift/kustomize/api/overlays/dev/kustomization.yaml
  openshift/kustomize/api/overlays/prod/kustomization.yaml
  openshift/kustomize/api/overlays/test/kustomization.yaml
  openshift/kustomize/cron/base/config-map.yaml
  openshift/kustomize/cron/base/cron-job.yaml
  openshift/kustomize/elastic/base/statefulset.yaml
  openshift/kustomize/elastic/overlays/dev/kustomization.yaml
  openshift/kustomize/elastic/overlays/prod/kustomization.yaml
  openshift/kustomize/elastic/overlays/test/kustomization.yaml
  openshift/kustomize/kafka/broker/base/statefulset.yaml
  openshift/kustomize/kafka/broker/overlays/dev/kustomization.yaml
  openshift/kustomize/kafka/broker/overlays/prod/kustomization.yaml
  openshift/kustomize/kafka/broker/overlays/test/kustomization.yaml
  openshift/kustomize/kafka/zookeeper/base/statefulset.yaml
  openshift/kustomize/kafka/zookeeper/overlays/dev/kustomization.yaml
  openshift/kustomize/kafka/zookeeper/overlays/prod/kustomization.yaml
  openshift/kustomize/kafka/zookeeper/overlays/test/kustomization.yaml
  openshift/kustomize/postgres/crunchy/base/deploy.yaml
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/services/capture/base/pvc.yaml
  openshift/kustomize/services/capture/overlays/dev/kustomization.yaml
  openshift/kustomize/services/capture/overlays/prod/kustomization.yaml
  openshift/kustomize/services/capture/overlays/test/kustomization.yaml
  openshift/kustomize/services/clip/base/deploy.yaml
  openshift/kustomize/services/content/base/deploy.yaml
  openshift/kustomize/services/filecopy/base/deploy.yaml
  openshift/kustomize/services/filemonitor/base/deploy.yaml
  openshift/kustomize/services/image/base/deploy.yaml
  openshift/kustomize/services/indexing/base/deploy.yaml
  openshift/kustomize/services/nlp/base/deploy.yaml
  openshift/kustomize/services/syndication/base/deploy.yaml
  openshift/kustomize/services/transcription/base/deploy.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-elastic-migration.yaml
  openshift/kustomize/tekton/base/tasks/build-component.yaml
  openshift/kustomize/tekton/base/tasks/git-conditions.yaml
  openshift/scripts/database-connect.sh
  openshift/scripts/port-forward.sh
  tools/elastic/migration/TNOElasticClient.cs
  tools/elastic/migration/TNOMigration.cs
Labels: devops

#652 Fix TNO-1075
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/components/wysiwyg/styled/Wysiwyg.tsx
Labels: bug

#653 Fix TNO-1075 (a minor css update)
  app/editor/src/features/content/form/components/wysiwyg/styled/Wysiwyg.tsx
Labels: bug

#656 Fix TNO-849 #2
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug, enhancement

#658 TNO-394 (fix an url related issue)
  app/editor/src/features/content/tool-bar/ContentToolBar.tsx
Labels: bug, enhancement

#654 Fix TNO-1048
  libs/net/services/Actions/IngestAction.cs
Labels: bug

#660 Fix TNO-892
  libs/npm/core/src/components/header/Header.tsx
Labels: enhancement

#661 Fix TNO-1190
  app/editor/src/features/content/form/components/topic/Topic.tsx
Labels: bug

#662 Bug for undefined tone
  app/subscriber/src/features/content/view-content/ViewContent.tsx
Labels: bug

#664 TNO-1193 Fix morning paper table
  app/editor/src/features/content/morning-reports/styled/MorningReports.tsx
Labels: bug

#665 Fix TNO-1191
  libs/net/core/Extensions/StringExtensions.cs
Labels: bug, enhancement

#667 TNO-1048 updates
  libs/net/dal/Services/ContentReferenceService.cs
  libs/net/dal/Services/ContentService.cs
Labels: bug

#668 Fix filter bugs
  app/editor/src/features/content/list-view/utils/makeFilter.ts
  app/editor/src/features/content/morning-reports/utils/makeFilter.ts
Labels: bug

#671 TNO-1251 Fix transcription service
  services/net/transcription/Dockerfile
Labels: bug

#670 Fix TNO-1198
  services/net/filemonitor/FilemonitorAction.cs
Labels: bug

#674 Fix TNO-1071
  app/editor/src/features/admin/ingests/configurations/FrontPage.tsx
  libs/net/kafka/Models/ContentBase.cs
  libs/net/kafka/Models/SourceContent.cs
  services/net/content/ContentManager.cs
  services/net/image/ImageAction.cs
Labels: enhancement

#675 Commentary box
  app/subscriber/src/features/commentary/Commentary.tsx
  app/subscriber/src/features/commentary/index.ts
  app/subscriber/src/features/commentary/styled/Commentary.tsx
  app/subscriber/src/features/commentary/styled/index.ts
  app/subscriber/src/features/commentary/utils/DetermineContentIcon.tsx
  app/subscriber/src/features/commentary/utils/index.ts
  app/subscriber/src/features/commentary/utils/isWeekday.ts
  app/subscriber/src/features/commentary/utils/styled/DetermineContentIcon.tsx
  app/subscriber/src/features/commentary/utils/styled/index.ts
  app/subscriber/src/features/home/Home.tsx
  app/subscriber/src/features/home/utils/DetermineToneIcon.tsx
  app/subscriber/src/features/landing/Landing.tsx
  app/subscriber/src/features/landing/styled/Landing.tsx
Labels: enhancement, subscriber

#676 TNO-1048 (content related updates)
  api/net/Areas/Editor/Controllers/ContentController.cs
Labels: bug

#677 TNO-1191 updates
  libs/net/core/Extensions/StringExtensions.cs
Labels: bug, enhancement

#678 TNO-1191 updates #2
  libs/net/core/Extensions/StringExtensions.cs
Labels: enhancement

#681 Fix advanced search
  .vscode/settings.json
  app/editor/src/features/content/list-view/constants/advancedSearchKeys.ts
  app/editor/src/features/content/list-view/constants/advancedSearchOptions.ts
  app/editor/src/features/content/list-view/constants/fieldTypes.ts
  app/editor/src/features/content/list-view/constants/index.ts
  app/editor/src/features/content/list-view/interfaces/IContentListAdvancedFilter.ts
  app/editor/src/features/content/list-view/utils/makeFilter.ts
  app/editor/src/features/content/list-view/utils/queryToFilterAdvanced.ts
  app/editor/src/features/content/morning-reports/MorningReportsFilter.tsx
  app/editor/src/features/content/morning-reports/components/AdvancedFilter.tsx
  app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
  app/editor/src/store/slices/content/contentSlice.ts
Labels: bug

#682 Fix morning papers filter
  app/editor/src/features/content/morning-reports/MorningReports.tsx
  app/editor/src/features/content/morning-reports/MorningReportsFilter.tsx
  app/editor/src/features/content/morning-reports/components/AdvancedFilter.tsx
  app/editor/src/features/content/morning-reports/utils/makeFilter.ts
  app/editor/src/store/hooks/editor/useContent.ts
  app/editor/src/store/slices/content/contentSlice.ts
  app/editor/src/store/slices/content/interfaces/IContentState.ts
  app/editor/src/store/slices/content/useContentStore.ts
Labels: bug

#679 View A/V
  app/subscriber/src/features/commentary/Commentary.tsx
  app/subscriber/src/features/commentary/styled/Commentary.tsx
  app/subscriber/src/features/commentary/utils/DetermineContentIcon.tsx
  app/subscriber/src/features/content/view-content/ViewContent.tsx
  app/subscriber/src/features/content/view-content/styled/ViewContent.tsx
  app/subscriber/src/store/hooks/subscriber/useContent.ts
Labels: enhancement, subscriber

#680 TNO-1048 updates
  api/net/Areas/Editor/Controllers/ContentController.cs
  libs/net/services/Actions/IngestAction.cs
Labels: bug

#684 Fix TNO-1172
  app/editor/src/components/layout/styled/Layout.tsx
  app/editor/src/css/_colors.scss
  app/editor/src/css/_variables.module.scss
Labels: enhancement

#683 Fix TNO-1234
  api/net/Areas/Editor/Controllers/LookupController.cs
  libs/net/dal/Services/Interfaces/IUserService.cs
  libs/net/dal/Services/UserService.cs
  libs/net/dal/TNO.DAL.csproj
Labels: bug

#689 TNO-1180
  .github/workflows/react-editor.yml
  .github/workflows/react-subscriber.yml
  app/editor/.yarn/cache/caniuse-lite-npm-1.0.30001431-6d607db8ef-bc8ab55cd1.zip
  app/editor/.yarn/cache/caniuse-lite-npm-1.0.30001481-cd8272ecaa-8200a043c1.zip
  app/editor/.yarn/install-state.gz
  app/editor/src/features/admin/topic-score-rules/TopicScoreRuleList.tsx
  app/editor/src/features/admin/topic-score-rules/styled/TopicScoreRuleList.tsx
  app/editor/src/features/content/index.ts
  app/editor/src/features/content/morning-papers/MorningReports.tsx
  app/editor/src/features/content/morning-papers/MorningReportsFilter.tsx
  app/editor/src/features/content/morning-papers/components/AdvancedFilter.tsx
  app/editor/src/features/content/morning-papers/components/ContentFilter.tsx
  app/editor/src/features/content/morning-papers/components/ReportActions.tsx
  app/editor/src/features/content/morning-papers/components/index.ts
  app/editor/src/features/content/morning-papers/components/styled/ContentFilter.tsx
  app/editor/src/features/content/morning-papers/components/styled/ReportActions.tsx
  app/editor/src/features/content/morning-papers/components/styled/index.ts
  app/editor/src/features/content/morning-papers/constants/columns.tsx
  app/editor/src/features/content/morning-papers/constants/defaultMorningReportsFilter.ts
  app/editor/src/features/content/morning-papers/constants/defaultSources.ts
  app/editor/src/features/content/morning-papers/constants/index.ts
  app/editor/src/features/content/morning-papers/index.ts
  app/editor/src/features/content/morning-papers/interfaces/IMorningReportsFilter.ts
  app/editor/src/features/content/morning-papers/interfaces/index.ts
  app/editor/src/features/content/morning-papers/styled/MorningReports.tsx
  app/editor/src/features/content/morning-papers/styled/MorningReportsFilter.tsx
  app/editor/src/features/content/morning-papers/styled/index.ts
  app/editor/src/features/content/morning-papers/utils/index.ts
  app/editor/src/features/content/morning-papers/utils/makeFilter.ts
  app/editor/src/store/hooks/editor/useContent.ts
  app/editor/src/store/slices/content/contentSlice.ts
  app/editor/src/store/slices/content/interfaces/IContentState.ts
  app/editor/src/store/slices/content/useContentStore.ts
  app/editor/yarn.lock
  app/subscriber/src/features/content/morning-papers/interfaces/IMorningReportFilter.ts
  app/subscriber/src/features/content/morning-papers/interfaces/index.ts
  app/subscriber/src/store/slices/content/contentSlice.ts
  app/subscriber/src/store/slices/content/interfaces/IContentState.ts
  app/subscriber/src/store/slices/content/useContentStore.ts
Labels: bug

#687 Add subscriber pipeline
  openshift/kustomize/tekton/base/triggers/listener.yaml
Labels: devops

#691 Fix TNO-1240
  services/net/notification/ITnoRazorLightEngine.cs
  services/net/notification/Models/TemplateModel.cs
  services/net/notification/NotificationManager.cs
  services/net/notification/NotificationService.cs
  services/net/notification/TNO.Services.Notification.csproj
  services/net/notification/TnoRazorLightEngine.cs
Labels: enhancement

#692 TNO-1238: Fix byline
  app/subscriber/src/features/content/view-content/ViewContent.tsx
  app/subscriber/src/features/home/Home.tsx
Labels: bug

#693 Hover color
  app/subscriber/src/components/sidebar/styled/CustomSidebar.tsx
Labels: bug
