Repository bcgov/tno, pull requests merged in 2023-01, with the labels that each got.

#463 TNO-784: Status section
  app/editor/src/components/tool-bar/ToolBarSection.tsx
  app/editor/src/components/tool-bar/styled/ToolBarSection.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/tool-bar/ContentFormToolBar.tsx
  app/editor/src/features/content/tool-bar/sections/form/StatusSection.tsx
  app/editor/src/features/content/tool-bar/sections/form/index.ts
Labels: enhancement

#465 TNO-775: Date range
  app/editor/src/components/form/datepicker/styled/SelectDate.tsx
  app/editor/src/components/tool-bar/styled/ToolBar.tsx
  app/editor/src/components/tool-bar/styled/ToolBarSection.tsx
  app/editor/src/features/content/tool-bar/ContentToolBar.tsx
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Labels: enhancement

#466 TNO-726: Persist filter from query params
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Labels: enhancement

#462 Fixed TNO-825
  libs/npm/core/src/components/grid-table/styled/GridTable.tsx
  libs/npm/core/src/components/loading/LoadingStyled.tsx
Labels: bug

#460 Fixed TNO-828
  libs/npm/core/src/components/grid-table/GridTable.tsx
Labels: bug

#453 Fixed TNO-653
  app/editor/src/features/content/form/ClipDirectoryTable.tsx
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/constants/clipDirectoryColumns.tsx
  app/editor/src/features/storage/StorageListView.tsx
  app/editor/src/utils/index.ts
  app/editor/src/utils/isImage.ts
  app/editor/src/utils/isNotVideoOrAudio.ts
Labels: enhancement

#467 TNO-276 Fix list content search
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Labels: bug

#468 TNO-736 Add remote storage access
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/DataLocationController.cs
  api/net/Areas/Editor/Controllers/LookupController.cs
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Areas/Editor/Models/Storage/FolderModel.cs
  api/net/Areas/Editor/Models/Storage/ItemModel.cs
  api/net/Areas/Helpers/ConnectionHelper.cs
  api/net/Areas/Helpers/IConnectionHelper.cs
  api/net/Areas/Services/Controllers/ContentController.cs
  api/net/Program.cs
  api/net/TNO.API.csproj
  app/editor/src/components/breadcrumb/Breadcrumb.tsx
  app/editor/src/components/breadcrumb/styled/Breadcrumb.tsx
  app/editor/src/components/toggle-group/ToggleGroup.tsx
  app/editor/src/components/toggle-group/styled/ToggleGroup.tsx
  app/editor/src/components/upload/UploadContextWrapper.tsx
  app/editor/src/components/upload/interfaces/IUploadManager.ts
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/storage/StorageListView.tsx
  app/editor/src/hooks/api-editor/editor/index.ts
  app/editor/src/hooks/api-editor/editor/useApiContents.ts
  app/editor/src/hooks/api-editor/editor/useApiDataLocations.ts
  app/editor/src/hooks/api-editor/editor/useApiStorage.ts
  app/editor/src/hooks/api-editor/interfaces/ILookupModel.ts
  app/editor/src/store/hooks/editor/useContent.ts
  app/editor/src/store/hooks/lookup/useLookup.ts
  app/editor/src/store/hooks/storage/useStorage.ts
  app/editor/src/store/slices/lookup/interfaces/ILookupState.ts
  app/editor/src/store/slices/lookup/lookupSlice.ts
  app/editor/src/store/slices/lookup/useLookupStore.ts
  docker-compose.yml
  libs/net/core/Extensions/StringExtensions.cs
  libs/net/dal/Config/StorageOptions.cs
  libs/net/dal/Extensions/FileReferenceExtensions.cs
  libs/net/dal/Services/DataLocationService.cs
  libs/net/dal/Services/FileReferenceService.cs
  libs/net/dal/Services/Interfaces/IFileReferenceService.cs
  libs/net/entities/DataLocation.cs
  libs/net/models/Areas/Editor/Models/DataLocation/DataLocationModel.cs
  libs/net/models/Areas/Editor/Models/Lookup/LookupModel.cs
  openshift/kustomize/tekton/base/pipelines/owasp-scanner.yaml
  services/net/clip/ClipAction.cs
Labels: enhancement

#464 TNO-866: Add wysiwig for transcript
  app/editor/src/features/content/form/ContentTranscriptForm.tsx
Labels: enhancement

#473 TNO-859 Fix templates
  api/net/Program.cs
  app/subscriber/src/features/admin/users/interfaces/IUserListFilter.ts
  app/subscriber/src/features/admin/users/interfaces/index.ts
  app/subscriber/src/features/admin/work-orders/interfaces/IWorkOrderListFilter.ts
  app/subscriber/src/features/admin/work-orders/interfaces/index.ts
  libs/net/Makefile
  openshift/kustomize/api/base/deploy.yaml
  openshift/kustomize/app/subscriber/base/config-map.yaml
  openshift/kustomize/app/subscriber/base/deploy.yaml
  openshift/kustomize/app/subscriber/base/kustomization.yaml
  openshift/kustomize/app/subscriber/base/network-policy.yaml
  openshift/kustomize/app/subscriber/base/route.yaml
  openshift/kustomize/app/subscriber/base/service.yaml
  openshift/kustomize/app/subscriber/build/base/build.yaml
  openshift/kustomize/app/subscriber/build/base/kustomization.yaml
  openshift/kustomize/app/subscriber/build/overlays/dev/kustomization.yaml
  openshift/kustomize/app/subscriber/build/overlays/jmf/kustomization.yaml
  openshift/kustomize/app/subscriber/overlays/dev/kustomization.yaml
  openshift/kustomize/app/subscriber/overlays/prod/kustomization.yaml
  openshift/kustomize/app/subscriber/overlays/test/kustomization.yaml
  openshift/kustomize/services/capture/base/deploy.yaml
  openshift/kustomize/services/config-map.yaml
  openshift/kustomize/services/content/base/deploy.yaml
  openshift/kustomize/services/filemonitor/base/deploy.yaml
  openshift/kustomize/services/image/base/deploy.yaml
  openshift/kustomize/services/indexing/base/deploy.yaml
  openshift/kustomize/services/nlp/base/deploy.yaml
  openshift/kustomize/services/syndication/base/deploy.yaml
  openshift/kustomize/services/transcription/base/deploy.yaml
Labels: bug, enhancement

#475 TNO-840: Only show print content on morning report
  app/editor/src/features/content/morning-report/MorningReportFilter.tsx
Labels: enhancement

#476 TNO-850 Subscriber DevOps
  openshift/kustomize/api/base/route.yaml
  openshift/kustomize/api/overlays/dev/kustomization.yaml
  openshift/kustomize/api/overlays/prod/kustomization.yaml
  openshift/kustomize/api/overlays/test/kustomization.yaml
  openshift/kustomize/app/subscriber/base/route.yaml
  openshift/kustomize/app/subscriber/overlays/dev/kustomization.yaml
  openshift/kustomize/app/subscriber/overlays/prod/kustomization.yaml
  openshift/kustomize/app/subscriber/overlays/test/kustomization.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-main.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-subscriber.yaml
  openshift/kustomize/tekton/base/tasks/git-conditions.yaml
Labels: devops

#470 TNO-781: New toning group
  app/editor/public/assets/face-frown-open.svg
  app/editor/public/assets/face-grin-wide.svg
  app/editor/public/assets/face-meh.svg
  app/editor/src/components/form/toning/ToningGroup.tsx
  app/editor/src/components/form/toning/styled/ToningGroup.tsx
  app/editor/src/components/form/toning/styled/index.ts
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/styled/ContentSummaryForm.tsx
Labels: enhancement

#469 Fixed TNO-797
  .github/workflows/net-libs.yml
  .vscode/launch.json
  api/net/.devcontainer/Dockerfile
  api/net/.devcontainer/devcontainer.json
  api/net/.vscode/launch.json
  api/net/Dockerfile
  api/net/Dockerfile.aspnet
  api/net/Dockerfile.openshift
  api/net/TNO.API.csproj
  libs/net/.devcontainer/Dockerfile
  libs/net/.devcontainer/devcontainer.json
  libs/net/.vscode/launch.json
  libs/net/Dockerfile
  libs/net/ches/TNO.Ches.csproj
  libs/net/core/TNO.Core.csproj
  libs/net/css/TNO.CSS.csproj
  libs/net/dal/TNO.DAL.csproj
  libs/net/entities/TNO.Entities.csproj
  libs/net/kafka/TNO.Kafka.csproj
  libs/net/keycloak/TNO.Keycloak.csproj
  libs/net/models/TNO.Models.csproj
  libs/net/reports/TNO.Reports.csproj
  libs/net/services/TNO.Services.csproj
  libs/net/tests/README.md
  libs/net/tests/core/TNO.Test.Core.csproj
  libs/net/tests/dal/TNO.Test.DAL.csproj
  libs/net/tests/entities/TNO.Test.Entities.csproj
  libs/net/tests/services/TNO.Test.Services.csproj
  services/net/.devcontainer/Dockerfile
  services/net/.devcontainer/devcontainer.json
  services/net/.vscode/launch.json
  services/net/capture/Dockerfile
  services/net/capture/TNO.Services.Capture.csproj
  services/net/clip/Dockerfile
  services/net/clip/TNO.Services.Clip.csproj
  services/net/command/Dockerfile
  services/net/command/TNO.Services.Command.csproj
  services/net/content/Dockerfile
  services/net/content/TNO.Services.Content.csproj
  services/net/filemonitor/Dockerfile
  services/net/filemonitor/TNO.Services.FileMonitor.csproj
  services/net/image/Dockerfile
  services/net/image/TNO.Services.Image.csproj
  services/net/indexing/Dockerfile
  services/net/indexing/TNO.Services.Indexing.csproj
  services/net/nlp/Dockerfile
  services/net/nlp/TNO.Services.NLP.csproj
  services/net/syndication/Dockerfile
  services/net/syndication/TNO.Services.Syndication.csproj
  services/net/transcription/Dockerfile
  services/net/transcription/TNO.Services.Transcription.csproj
  tools/css-api/.vscode/launch.json
  tools/css-api/Dockerfile
  tools/css-api/TNO.CSS.API.csproj
  tools/import/.devcontainer/Dockerfile
  tools/import/.devcontainer/devcontainer.json
  tools/import/.vscode/launch.json
  tools/import/etl/TNO.Tools.Import.ETL.csproj
  tools/import/source/TNO.Tools.Import.Source.csproj
Labels: enhancement

#478 TNO-835: Morning report filters
  app/editor/src/features/content/morning-report/MorningReportFilter.tsx
Labels: enhancement

#482 TNO-883: Move edition to same row
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug

#486 TNO-908: Default to Source not Headline
  app/editor/src/store/slices/content/contentSlice.ts
Labels: bug

#487 Clean up report filters
  app/editor/src/features/content/morning-report/MorningReportFilter.tsx
Labels: bug

#489 TNO-906 Fix File Service Source, Syndication Feed Request
  .vscode/tasks.json
  app/editor/src/features/admin/ingests/IngestDetails.tsx
  libs/net/services/Managers/IngestManager`.cs
  services/net/filemonitor/FileMonitorIngestActionManager.cs
  services/net/filemonitor/FilemonitorAction.cs
  services/net/filemonitor/FilemonitorManager.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#490 TNO-906 Fix timezone
  api/net/Config/Swagger/SwaggerDocumentFilter.cs
  api/net/Program.cs
  services/net/filemonitor/FilemonitorAction.cs
Labels: bug

#491 TNO-907: Default to all content
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
  app/editor/src/store/slices/content/contentSlice.ts
Labels: bug

#493 TNO-906 Fix duplicates
  services/net/filemonitor/FilemonitorAction.cs
Labels: bug

#494 Fix tno-core build/pack
  libs/npm/core/package.json
  libs/npm/core/webpack.config.js
Labels: bug, devops

#496 TNO-882: Expand WYSIWYG for Print Content
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#497 TNO-888, 887: Date range trigger and clear
  app/editor/src/components/form/toning/styled/ToningGroup.tsx
  app/editor/src/features/content/tool-bar/ContentToolBar.tsx
  app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/index.ts
  app/editor/src/features/content/tool-bar/sections/filter/styled/DateRangeSection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/styled/index.ts
Labels: bug

#498 TNO-906 Improve ingest admin
  api/net/Areas/Admin/Controllers/ContentReferenceController.cs
  app/editor/src/features/admin/ingests/ContentReferenceList.tsx
  app/editor/src/features/admin/ingests/constants/contentReferenceColumns.tsx
  app/editor/src/features/admin/ingests/constants/defaultContentReferenceFilter.ts
  app/editor/src/features/admin/ingests/interfaces/IContentReferenceListFilter.ts
  app/editor/src/hooks/api-editor/admin/useApiAdminContentReferences.ts
  app/editor/src/hooks/api-editor/interfaces/IContentReferenceFilter.ts
  app/editor/src/store/hooks/admin/useContentReferences.ts
  libs/net/dal/Models/ContentReferenceFilter.cs
  libs/net/dal/Services/ContentReferenceService.cs
  libs/net/dal/Services/Interfaces/IContentReferenceService.cs
  libs/net/entities/ContentReference.cs
Labels: enhancement

#499 TNO-909: If using date range widget, the Today 24 HR 48 HR ALL panel should be greyed out
  app/editor/src/components/toggle-group/ToggleGroup.tsx
  app/editor/src/components/toggle-group/styled/ToggleGroup.tsx
  app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Labels: enhancement

#500 TNO-910: Styling date range
  app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/styled/DateRangeSection.tsx
Labels: bug

#501 TNO-874 Fix streams
  api/net/Areas/Editor/Controllers/StorageController.cs
  app/editor/src/features/admin/ingests/configurations/AudioClip.tsx
  app/editor/src/features/admin/ingests/configurations/AudioStream.tsx
  app/editor/src/features/admin/ingests/configurations/AudioTuner.tsx
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
Labels: bug

#502 TNO-874 Fix storage locations
  api/net/Areas/Editor/Controllers/StorageController.cs
Labels: bug

#503 TNO-1004: Can't clear source
  app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
Labels: bug

#504 Designation Override Bug
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug

#505 Fix content list columns
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/list-view/constants/columns.tsx
Labels: enhancement

#506 Pagination bug
  app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx
Labels: bug

#507 TNO-1008 Fix video, Update columns
  app/editor/src/features/admin/ingests/IngestSettings.tsx
  app/editor/src/features/admin/ingests/configurations/Audio.tsx
  app/editor/src/features/admin/ingests/configurations/Video.tsx
  app/editor/src/features/admin/ingests/constants/defaultIngest.ts
  app/editor/src/features/content/form/ContentClipForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/interfaces/IContentForm.ts
  app/editor/src/features/content/form/interfaces/IStream.ts
  app/editor/src/features/content/form/interfaces/index.ts
  app/editor/src/features/content/morning-report/constants/columns.tsx
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  services/net/clip/ClipAction.cs
Labels: bug, enhancement

#508 TNO-874 Fix Clip service
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  services/net/clip/ClipAction.cs
Labels: bug

#492 Fixed TNO-816
  app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
  app/editor/src/features/admin/sources/SourceDetails.tsx
  app/editor/src/features/admin/users/UserFilter.tsx
  app/editor/src/features/admin/users/UserForm.tsx
  app/editor/src/features/admin/work-orders/WorkOrderForm.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/list-view/ContentFilter.tsx
  app/editor/src/features/content/morning-report/MorningReportFilter.tsx
  app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/InputOption.tsx
  app/editor/src/store/hooks/lookup/utils/filterEnabled.ts
  app/editor/src/utils/getSourceOptions.ts
  app/editor/src/utils/getUserOptions.ts
  app/subscriber/src/features/navbar/NavBar.tsx
  app/subscriber/src/utils/getUserOptions.ts
Labels: bug, enhancement

#509 TNO-939 Fix cron job
  openshift/kustomize/cron/Dockerfile
  openshift/kustomize/cron/base/config-map.yaml
  openshift/kustomize/cron/base/cron-job.yaml
  openshift/kustomize/cron/build/base/build.yaml
  openshift/kustomize/cron/build/base/kustomization.yaml
  openshift/kustomize/cron/build/overlays/dev/kustomization.yaml
  openshift/kustomize/cron/build/overlays/jmf/kustomization.yaml
  tools/scripts/purge-folders.sh
Labels: bug, devops

#510 TNO-996 Fix CrunchyDB template
  openshift/kustomize/postgres/crunchy/base/deploy.yaml
Labels: devops
