Repository bcgov/tno, pull requests merged in 2023-02, with the labels that each got.

#513 Fixed TNO-1003
  libs/net/services/Managers/IngestManager`.cs
Labels: bug

#512 TNO-818: Toolbar Responsiveness
  app/editor/src/components/tool-bar/styled/ToolBarSection.tsx
  app/editor/src/features/content/form/constants/ShowOnlyValues.ts
  app/editor/src/features/content/form/constants/showOnlyOptions.ts
  app/editor/src/features/content/list-view/interfaces/IContentListFilter.ts
  app/editor/src/features/content/tool-bar/ContentFormToolBar.tsx
  app/editor/src/features/content/tool-bar/sections/filter/ShowOnlySection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/utils/checkLatestShowOnlyEntry.ts
  app/editor/src/features/content/tool-bar/sections/filter/utils/getSelectedOptions.ts
  app/editor/src/features/content/tool-bar/sections/filter/utils/index.ts
Labels: enhancement

#514 Fix toolbar z-index
  app/editor/src/components/tool-bar/styled/ToolBarSection.tsx
Labels: bug

#516 TNO-1015: Time overwritten bug
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#517 TNO-736 Fix API build
  api/net/Areas/Admin/Models/Connection/ConnectionModel.cs
  api/net/Areas/Admin/Models/DataLocation/ConnectionModel.cs
  api/net/Areas/Admin/Models/Ingest/ConnectionModel.cs
  api/net/Areas/Admin/Models/Ingest/IngestModel.cs
  api/net/Areas/Admin/Models/Source/SourceModel.cs
Labels: bug

#518 TNO-736 Add FFmpeg to API
  api/net/Dockerfile.openshift
  libs/net/kafka/KafkaListener`.cs
  openshift/kustomize/api/build/overlays/jmf/kustomization.yaml
  openshift/kustomize/api/overlays/dev/kustomization.yaml
  openshift/kustomize/api/overlays/prod/kustomization.yaml
  openshift/kustomize/api/overlays/test/kustomization.yaml
  openshift/kustomize/services/capture/overlays/dev/kustomization.yaml
  openshift/kustomize/services/capture/overlays/prod/kustomization.yaml
  openshift/kustomize/services/capture/overlays/test/kustomization.yaml
  services/net/filecopy/FileCopyManager.cs
Labels: bug, devops

#524 Fix services
  libs/net/dal/TNO.DAL.csproj
  libs/net/services/Runners/BaseService.cs
  openshift/kustomize/tekton/base/pipeline-runs/buildah-service.yaml
  openshift/kustomize/tekton/base/tasks/build-component.yaml
  openshift/kustomize/tekton/base/tasks/buildah.yaml
  openshift/kustomize/tekton/base/triggers/template.yaml
  services/net/capture/Dockerfile
  services/net/clip/Dockerfile
  services/net/command/Dockerfile
  services/net/content/Dockerfile
  services/net/filecopy/Dockerfile
  services/net/filemonitor/Dockerfile
  services/net/image/Dockerfile
  services/net/indexing/Dockerfile
  services/net/nlp/Dockerfile
  services/net/syndication/Dockerfile
  services/net/transcription/Dockerfile
  tools/import/etl/TNO.Tools.Import.ETL.csproj
Labels: bug

#520 Fixed TNO-921
  libs/net/services/Managers/IngestManager`.cs
Labels: bug

#522 TNO-995, 1023: Source required bug, and time style
  app/editor/src/components/form/time-log/TimeLogSection.tsx
  app/editor/src/components/form/time-log/styled/TimeLogSection.tsx
  app/editor/src/components/form/time-log/styled/index.ts
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/index.scss
Labels: bug

#526 TNO-1039: Only show time log entry for snippets
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#525 TNO-1036: Rename series for snippets
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#527 TNO-1065: Hide NLP options for editors
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#528 TNO-1059 Add byline
  api/net/TNO.API.csproj
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/utils/getContentPath.ts
  app/editor/src/features/content/form/utils/index.ts
  app/editor/src/features/content/form/utils/isImageForm.ts
  app/editor/src/features/content/form/utils/isSnippetForm.ts
  app/editor/src/features/content/form/utils/toForm.ts
  app/editor/src/features/content/form/utils/toModel.ts
  app/editor/src/features/content/list-view/constants/columns.tsx
  app/editor/src/features/content/morning-report/constants/columns.tsx
  app/editor/src/features/content/tool-bar/sections/filter/CreateNewSection.tsx
  app/editor/src/features/router/AppRouter.tsx
  app/editor/src/hooks/api-editor/interfaces/IContentModel.ts
  app/editor/src/hooks/api-editor/interfaces/IPrintContentModel.ts
  app/editor/src/hooks/api-editor/interfaces/index.ts
  app/editor/src/hooks/api-editor/mocks/contents.ts
  libs/net/dal/Configuration/ActionConfiguration.cs
  libs/net/dal/Configuration/BaseTypeConfiguration`.cs
  libs/net/dal/Configuration/CacheConfiguration.cs
  libs/net/dal/Configuration/ContentActionConfiguration.cs
  libs/net/dal/Configuration/ContentConfiguration.cs
  libs/net/dal/Configuration/ContentLabelConfiguration.cs
  libs/net/dal/Configuration/ContentReferenceConfiguration.cs
  libs/net/dal/Configuration/IngestConfiguration.cs
  libs/net/dal/Configuration/PrintContentConfiguration.cs
  libs/net/dal/Configuration/ScheduleConfiguration.cs
  libs/net/dal/Configuration/SeriesConfiguration.cs
  libs/net/dal/Configuration/SourceConfiguration.cs
  libs/net/dal/Configuration/UserConfiguration.cs
  libs/net/dal/Configuration/WorkOrderConfiguration.cs
  libs/net/dal/Extensions/ContentExtensions.cs
  libs/net/dal/Migrations/1.0.2/Down/PostDown/00-PrintContent.sql
  libs/net/dal/Migrations/1.0.2/Down/PreDown/00-PrintContent.sql
  libs/net/dal/Migrations/1.0.2/Up/PostUp/00-PrintContent.sql
  libs/net/dal/Migrations/1.0.2/Up/PreUp/00-PrintContent.sql
  libs/net/dal/Migrations/20230213160809_1.0.2.Designer.cs
  libs/net/dal/Migrations/20230213160809_1.0.2.cs
  libs/net/dal/Services/ContentService.cs
  libs/net/dal/TNOContext.cs
  libs/net/entities/Content.cs
  libs/net/entities/PrintContent.cs
  libs/net/models/Areas/Editor/Models/Content/ContentModel.cs
  libs/net/models/Areas/Editor/Models/Content/PrintContentModel.cs
  libs/net/models/Areas/Services/Models/Content/ContentModel.cs
  libs/net/models/Areas/Services/Models/Content/PrintContentModel.cs
  openshift/kustomize/tekton/base/pipeline-runs/buildah-main.yaml
  openshift/kustomize/tekton/base/pipeline-runs/buildah-service.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-main.yaml
  openshift/kustomize/tekton/base/triggers/template.yaml
Labels: enhancement, DB Migration

#530 Fix DevOps builds
  openshift/kustomize/services/build/base/capture.yaml
  openshift/kustomize/services/build/base/clip.yaml
  openshift/kustomize/services/build/base/content.yaml
  openshift/kustomize/services/build/base/filecopy.yaml
  openshift/kustomize/services/build/base/filemonitor.yaml
  openshift/kustomize/services/build/base/image.yaml
  openshift/kustomize/services/build/base/indexing.yaml
  openshift/kustomize/services/build/base/nlp.yaml
  openshift/kustomize/services/build/base/syndication.yaml
  openshift/kustomize/services/build/base/transcription.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-service.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-services.yaml
  services/net/capture/Dockerfile.openshift
  services/net/clip/Dockerfile.openshift
  services/net/command/Dockerfile.openshift
  services/net/content/Dockerfile.openshift
  services/net/filecopy/Dockerfile.openshift
  services/net/filemonitor/Dockerfile.openshift
  services/net/image/Dockerfile.openshift
  services/net/indexing/Dockerfile.openshift
  services/net/nlp/Dockerfile.openshift
  services/net/syndication/Dockerfile.openshift
  services/net/transcription/Dockerfile.openshift
Labels: devops

#532 TNO-927 Improve error message
  api/net/Middleware/ErrorHandlingMiddleware.cs
  app/editor/src/store/hooks/app/useToastError.tsx
  app/editor/src/store/hooks/useAjaxWrapper.ts
  app/editor/src/store/slices/app/interfaces/IErrorModel.ts
  app/subscriber/src/store/hooks/app/useToastError.tsx
  app/subscriber/src/store/hooks/useAjaxWrapper.ts
  app/subscriber/src/store/slices/app/interfaces/IErrorModel.ts
  libs/net/Dockerfile
Labels: enhancement, devops

#533 TNO-1067: Rename buttons
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: enhancement

#535 Rest of tno-893: Add tags and wysiwyg for image
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: enhancement

#536 TNO-1036 changes
  app/editor/src/features/admin/series/SeriesList.tsx
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#523 TNO-899: Persist filter on refresh
  app/editor/src/features/content/list-view/ContentFilter.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/constants/defaultFilter.ts
  app/editor/src/features/content/list-view/index.ts
  app/editor/src/features/content/list-view/interfaces/IContentListFilter.ts
  app/editor/src/features/content/list-view/styled/ContentFilter.tsx
  app/editor/src/features/content/list-view/styled/index.ts
  app/editor/src/features/content/list-view/utils/makeFilter.ts
  app/editor/src/features/content/list-view/utils/queryToFilter.ts
  app/editor/src/features/content/morning-report/MorningReportFilter.tsx
  app/editor/src/features/content/morning-report/interfaces/IMorningReportFilter.ts
  app/editor/src/features/content/morning-report/utils/makeFilter.ts
  app/editor/src/features/content/tool-bar/ContentToolBar.tsx
  app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
  app/editor/src/hooks/api-editor/interfaces/IContentFilter.ts
  app/editor/src/store/slices/content/contentSlice.ts
Labels: bug

#539 series -> programs
  app/editor/src/features/admin/AdminRouter.tsx
  app/editor/src/features/admin/actions/ActionForm.tsx
  app/editor/src/features/admin/series/SeriesForm.tsx
  app/editor/src/features/admin/series/SeriesList.tsx
  app/editor/src/features/navbar/NavBar.tsx
Labels: bug

#540 Fix for persisting user filter selected
  app/editor/src/features/content/tool-bar/sections/filter/FilterContentSection.tsx
Labels: bug

#538 TNO-928
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Elasticsearch/TNOElasticClient.cs
  api/net/Program.cs
  api/net/appsettings.json
  libs/net/dal/Services/ContentService.cs
  libs/net/dal/Services/Interfaces/IContentService.cs
  libs/net/dal/TNO.DAL.csproj
  libs/net/entities/Content.cs
  libs/net/entities/TonePool.cs
Labels: enhancement

#542 TNO-928 (a minor fix for deployment)
  api/net/appsettings.Development.json
  api/net/appsettings.json
Labels: bug

#544 TNO-928 (a few more deployment related updates)
  libs/net/entities/ContentAction.cs
  libs/net/entities/ContentCategory.cs
  libs/net/entities/ContentLabel.cs
  libs/net/entities/ContentLink.cs
  libs/net/entities/ContentTag.cs
  libs/net/entities/ContentTonePool.cs
  libs/net/entities/ContentTypeAction.cs
  libs/net/entities/FileReference.cs
  libs/net/entities/Ingest.cs
  libs/net/entities/IngestDataLocation.cs
  libs/net/entities/IngestSchedule.cs
  libs/net/entities/IngestState.cs
  libs/net/entities/Source.cs
  libs/net/entities/SourceMetric.cs
  libs/net/entities/SourceSourceAction.cs
  libs/net/entities/TimeTracking.cs
Labels: bug, enhancement

#541 Fixed TNO-1063
  app/editor/src/features/content/form/ContentActions.tsx
Labels: bug

#550 TNO-1041 Update DevOps for Statefulsets
  openshift/README.md
  openshift/kustomize/api/base/statefulset.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-api.yaml
  openshift/kustomize/tekton/base/pipelines/buildah-main.yaml
  openshift/kustomize/tekton/base/tasks/oc-deploy-with-tag.yaml
  openshift/templates/tekton/service-account/role.yaml
Labels: devops

#551 Fix Indexing Service
  api/net/Areas/Editor/Controllers/ContentController.cs
  openshift/kustomize/elastic/base/config-map.yaml
  services/net/indexing/IndexingManager.cs
Labels: bug

#552 Fix indexing content from service
  api/net/Areas/Services/Controllers/ContentController.cs
Labels: bug

#553 Add reindex endpoint
  api/net/Areas/Services/Controllers/ContentController.cs
Labels: enhancement

#554 Add filter to reindex
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/MorningReportController.cs
  api/net/Areas/Services/Controllers/ContentController.cs
  api/net/Program.cs
  libs/net/dal/Services/ContentService.cs
  libs/net/dal/Services/Interfaces/IContentService.cs
  libs/net/reports/CBRAReport.cs
  openshift/kustomize/tekton/base/pipelines/buildah-main.yaml
Labels: enhancement

#555 928 deployment updates for paging
  libs/net/dal/Services/ContentService.cs
Labels: bug

#557 TNO-928 (a few more updates for dev)
  libs/net/dal/Services/ContentService.cs
Labels: bug, enhancement

#556 WYSIWYG font size consistency
  app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx
Labels: bug

#558 TNO-897: Rearrange media
  app/editor/src/features/content/form/ContentSummaryForm.tsx
  app/editor/src/features/content/form/styled/ContentSummaryForm.tsx
Labels: enhancement

#559 Enhance Elasticsearch migration
  .mailmap
  Makefile
  db/elasticsearch/elasticsearch.yml
  db/elasticsearch/migrations/1.0.0/down/01-d-index-content.json
  db/elasticsearch/migrations/1.0.0/down/02-d-index-unpublished_content.json
  db/elasticsearch/migrations/1.0.0/up/01-c-index-content.json
  db/elasticsearch/migrations/1.0.0/up/02-c-index-unpublished_content.json
  db/elasticsearch/migrations/1.0.1/down/01-d-alias-content_v1.0.1-content.json
  db/elasticsearch/migrations/1.0.1/down/02-d-alias-unpublished_content_v1.0.1-unpublished_content.json
  db/elasticsearch/migrations/1.0.1/down/03-c-index-content.json
  db/elasticsearch/migrations/1.0.1/down/04-r-index-content.json
  db/elasticsearch/migrations/1.0.1/down/05-c-index-unpublished_content.json
  db/elasticsearch/migrations/1.0.1/down/06-r-index-unpublished_content.json
  db/elasticsearch/migrations/1.0.1/down/07-d-index-content_v1.0.1.json
  db/elasticsearch/migrations/1.0.1/down/08-d-index-unpublished_content_v1.0.1.json
  db/elasticsearch/migrations/1.0.1/up/01-c-index-content_v1.0.1.json
  db/elasticsearch/migrations/1.0.1/up/02-r-index-content.json
  db/elasticsearch/migrations/1.0.1/up/03-d-index-content.json
  db/elasticsearch/migrations/1.0.1/up/04-c-alias-content_v1.0.1-content.json
  db/elasticsearch/migrations/1.0.1/up/05-c-index-unpublished_content_v1.0.1.json
  db/elasticsearch/migrations/1.0.1/up/06-r-index-unpublished_content.json
  db/elasticsearch/migrations/1.0.1/up/07-d-index-unpublished_content.json
  db/elasticsearch/migrations/1.0.1/up/08-c-alias-unpublished_content_v1.0.1-unpublished_content.json
  db/elasticsearch/scripts/migration.sh
  tools/scripts/fix-authors.sh
Labels: enhancement

#560 Ensure toning validation is fired
  app/editor/src/components/form/toning/ToningGroup.tsx
  app/editor/src/features/content/validation/ContentFormSchema.ts
Labels: bug

#562 Add unpublish button
  app/editor/src/features/content/form/ContentForm.tsx
Labels: enhancement

#564 TNO-982 (Fixed the IncludedInEod issue)
  libs/net/dal/Services/ContentService.cs
Labels: bug

#565 Decouple tags
  app/editor/src/features/content/form/ContentTranscriptForm.tsx
Labels: bug

#567 TNO-1056: Remove clear button from fieldType
  app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
Labels: bug

#566 Toning validation hotfix
  app/editor/src/components/form/toning/ToningGroup.tsx
  app/editor/src/features/content/validation/ContentFormSchema.ts
Labels: bug

#570 Topics -> Topic
  app/editor/src/features/content/form/ContentSummaryForm.tsx
Labels: bug

#569 TNO-928 (source related updates)
  app/editor/src/features/content/list-view/constants/fieldTypes.ts
  app/editor/src/features/content/list-view/utils/makeFilter.ts
  app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
  db/elasticsearch/migrations/1.0.1/up/01-c-index-content_v1.0.1.json
  db/elasticsearch/migrations/1.0.1/up/05-c-index-unpublished_content_v1.0.1.json
  libs/net/dal/Services/ContentService.cs
Labels: bug, DB Migration

#572 TNO-1115 Fix 204 no content
  app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
  app/editor/src/components/layout/DefaultLayout.tsx
  app/editor/src/components/layout/LayoutErrorBoundary.tsx
  app/editor/src/components/layout/styled/Layout.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/hooks/api-editor/editor/useApiContents.ts
  app/editor/src/store/hooks/editor/useContent.ts
Labels: bug

#573 TNO-1113 Fix delete content
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/store/hooks/useAjaxWrapper.ts
  services/net/indexing/IndexingManager.cs
Labels: bug

#571 Fixed TNO-1082
  app/editor/src/features/content/form/ContentForm.tsx
Labels: enhancement

#575 TNO-902 Fix paper ingest
  app/editor/src/components/form/wysiwyg/styled/Wysiwyg.tsx
  app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
  libs/net/core/Extensions/StringExtensions.cs
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  services/net/filemonitor/FilemonitorAction.cs
  services/net/filemonitor/models/Fields.cs
Labels: bug

#576 TNO-1128 Fix indexing concurrency issue
  api/net/Areas/Admin/Controllers/WorkOrderController.cs
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/WorkOrderController.cs
  api/net/Areas/Services/Controllers/ContentController.cs
  api/net/Areas/Services/Controllers/WorkOrderController.cs
  api/net/Program.cs
  api/net/SignalR/MessageHub.cs
  api/net/SignalR/WorkOrderHub.cs
  app/editor/src/features/content/form/ContentForm.tsx
  libs/net/services/Helpers/ApiService.cs
Labels: bug

#578 TNO-1128 Fix signalR
  api/net/Areas/Admin/Controllers/WorkOrderController.cs
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/WorkOrderController.cs
  api/net/Areas/Services/Controllers/ContentController.cs
  api/net/Areas/Services/Controllers/WorkOrderController.cs
  api/net/Program.cs
  api/net/SignalR/MessageHub.cs
Labels: bug

#577 TNO-1058: Content scrolling
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/constants/columns.tsx
Labels: enhancement

#581 TNO-694 Fix DB migration
  libs/net/dal/Configuration/TagConfiguration.cs
  libs/net/dal/Migrations/1.0.5/Down/PreDown/00-Tag.sql
  libs/net/dal/Migrations/1.0.5/Up/PostUp/00-Tag.sql
  libs/net/dal/Migrations/1.0.5/Up/PreUp/00-Tag.sql
  libs/net/dal/Migrations/20230228191725_1.0.5.Designer.cs
  libs/net/dal/Migrations/20230228191725_1.0.5.cs
  libs/net/dal/Migrations/TNOContextModelSnapshot.cs
Labels: bug, DB Migration

#579 Content Scroll - Bug Fix
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/hooks/useCombinedView.ts
Labels: bug

#580 TNO-1122: Validation
  app/editor/src/components/form/toning/ToningGroup.tsx
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/constants/defaultFormValues.ts
  app/editor/src/features/content/form/interfaces/IContentForm.ts
  app/editor/src/features/content/form/utils/toForm.ts
  app/editor/src/features/content/validation/ContentFormSchema.ts
Labels: bug

#584 TNO-804 Add service account authorization
  Makefile
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/LookupController.cs
  api/net/Areas/Kafka/Controllers/ProducerController.cs
  api/net/Areas/Services/Controllers/ConnectionController.cs
  api/net/Areas/Services/Controllers/ContentController.cs
  api/net/Areas/Services/Controllers/ContentReferenceController.cs
  api/net/Areas/Services/Controllers/DataLocationController.cs
  api/net/Areas/Services/Controllers/IngestController.cs
  api/net/Areas/Services/Controllers/SourceController.cs
  api/net/Areas/Services/Controllers/WorkOrderController.cs
  auth/keycloak/config/realm-export.json
  services/net/filemonitor/FilemonitorAction.cs
  tools/scripts/refresh-keycloak.sh
Labels: enhancement
