Repository bcgov/tno, pull requests merged in 2023-08, with the labels that each got.

#936 TNO-1472 updates based on the latest prototype
  app/editor/src/features/admin/topics/TopicFilter.tsx
  app/editor/src/features/admin/topics/TopicList.tsx
  app/editor/src/features/admin/topics/styled/TopicList.tsx
  app/editor/src/features/admin/topics/useColumns.tsx
  libs/npm/core/src/components/table/FlexboxTable.tsx
Labels: enhancement, tno-core update

#925 fix: #tno-1524 - only update content status
  api/net/Areas/Services/Controllers/ContentController.cs
  libs/net/dal/Services/ContentService.cs
  libs/net/dal/Services/Interfaces/IContentService.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Interfaces/IApiService.cs
  services/net/indexing/IndexingManager.cs
Labels: enhancement

#938 fix: #tno-1588 - fixed search on name and alias
  app/editor/package.json
  app/editor/src/features/admin/ministers/MinisterForm.tsx
  app/editor/src/features/admin/ministers/constants/columns.tsx
  app/subscriber/package.json
  app/subscriber/src/features/content/list-view/interfaces/IContentListFilter.ts
  app/subscriber/src/features/content/view-content/ViewContent.tsx
  app/subscriber/src/features/home/utils/makeFilter.ts
  app/subscriber/src/features/my-minister/MyMinister.tsx
  libs/net/dal/Models/ContentFilter.cs
  libs/net/dal/Services/ContentService.cs
  libs/npm/core/.yarn/install-state.gz
  libs/npm/core/package.json
  libs/npm/core/src/hooks/api-subscriber/interfaces/ISubscriberContentFilter.ts
Labels: bug

#944 Fix JsonDocument extension method and elastic migration tool
  libs/net/core/Extensions/JsonElementExtensions.cs
Labels: bug

#941 TNO-1587, 1508: Bugs
  app/editor/src/features/admin/evening-overview/overview-section/OverviewSection.tsx
  app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx
  app/subscriber/src/components/sidebar/advanced-search/components/MediaSection.tsx
  app/subscriber/src/components/sidebar/advanced-search/components/SentimentSection.tsx
  app/subscriber/src/components/sidebar/advanced-search/constants/ToggleOptions.ts
  app/subscriber/src/components/sidebar/advanced-search/constants/index.ts
  app/subscriber/src/components/sidebar/advanced-search/utils/queryToState.ts
Labels: bug

#942 TNO-1496: File Upload and Streaming Out of Memory
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Areas/Subscriber/Controllers/ContentController.cs
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/components/upload/Upload.tsx
  app/editor/src/features/content/form/components/upload/styled/Upload.tsx
  app/editor/src/features/storage/FileManager.tsx
  app/editor/src/store/hooks/storage/useStorage.ts
  app/subscriber/src/features/content/view-content/ViewContent.tsx
  app/subscriber/src/features/front-pages/FrontPages.tsx
  app/subscriber/src/features/search-page/player/Player.tsx
  libs/npm/core/src/hooks/api-editor/editor/useApiContents.ts
  libs/npm/core/src/hooks/api-editor/editor/useApiStorage.ts
  libs/npm/core/src/hooks/api-subscriber/useApiSubscriberContents.ts
Labels: bug, subscriber, tno-core update, editor

#946 feat: #tno-1558 - connect to PROD oracle instance
  docker-compose.yml
  services/net/contentmigration/Config/OracleConnectionSettings.cs
  services/net/contentmigration/appsettings.Development.json
  services/net/contentmigration/appsettings.json
  services/net/contentmigration/sources/oracle/Configuration/NewsItemConfiguration.cs
  services/net/contentmigration/sources/oracle/MigrationSourceContext.cs
  tools/oracle-instantclient/Dockerfile
Labels: enhancement

#945 Add reset button to advanced search
  app/subscriber/src/App.tsx
  app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx
  app/subscriber/src/components/sidebar/advanced-search/constants/DefaultAdvancedSearch.ts
  app/subscriber/src/components/sidebar/advanced-search/constants/ToggleOptions.ts
  app/subscriber/src/components/sidebar/advanced-search/constants/index.ts
  app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx
  app/subscriber/src/components/sidebar/advanced-search/utils/queryToState.ts
Labels: subscriber

#947 feat: #tno-1558 - connect to PROD oracle instance
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/sources/oracle/MigrationSourceContext.cs
Labels: bug

#939 TNO-1472 (double scroll bars related updates)
  app/editor/src/components/layout/DefaultLayout.tsx
  libs/npm/core/src/components/form/formpage/styled/FormPage.tsx
Labels: bug, enhancement

#949 TNO-1451: [UX/QA] Fine Tuning workflow for...
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/components/upload/Upload.tsx
Labels: enhancement

#951 TNO-1451 updates
  app/editor/src/features/content/form/ContentForm.tsx
Labels: enhancement

#952 feat: #tno-1629 - split tno ingest
  libs/net/dal/Migrations/1.0.53/Down/PostDown/00-IngestDataLocation.sql
  libs/net/dal/Migrations/1.0.53/Down/PostDown/00-Schedule.sql
  libs/net/dal/Migrations/1.0.53/Down/PostDown/01-IngestSchedule.sql
  libs/net/dal/Migrations/1.0.53/Down/PostDown/02-Ingest.sql
  libs/net/dal/Migrations/1.0.53/Down/PostDown/03-Ingest-Update.sql
  libs/net/dal/Migrations/1.0.54/Down/PostDown/00-IngestDataLocation.sql
  libs/net/dal/Migrations/1.0.54/Down/PostDown/00-Schedule.sql
  libs/net/dal/Migrations/1.0.54/Down/PostDown/01-IngestSchedule.sql
  libs/net/dal/Migrations/1.0.54/Down/PostDown/02-Ingest.sql
  libs/net/dal/Migrations/1.0.54/Down/PostDown/03-Ingest-Update.sql
  libs/net/dal/Migrations/1.0.54/Up/PostUp/01-Schedule.sql
  libs/net/dal/Migrations/1.0.54/Up/PostUp/02-Ingest-Update.sql
  libs/net/dal/Migrations/1.0.54/Up/PostUp/02-Ingest.sql
  libs/net/dal/Migrations/1.0.54/Up/PostUp/03-IngestDataLocation.sql
  libs/net/dal/Migrations/1.0.54/Up/PostUp/03-IngestSchedule.sql
  libs/net/dal/Migrations/20230809170141_1.0.54.Designer.cs
  libs/net/dal/Migrations/20230809170141_1.0.54.cs
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/appsettings.json
Labels: enhancement

#956 fix: #tno-1655 - fixed path on migrated file
  app/editor/src/features/admin/ingests/configurations/DbMigration.tsx
  services/net/contentmigration/ContentMigrationAction.cs
Labels: bug

#954 TNO-1494: Prep Time Validation on subsequent...
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/components/time-log/TimeLogSection.tsx
  app/editor/src/features/content/validation/ContentFormSchema.ts
Labels: bug

#955 TNO-1472 (a few more updates)
  app/editor/src/features/admin/topics/TopicList.tsx
  app/editor/src/features/admin/topics/styled/TopicList.tsx
  app/editor/src/features/admin/topics/useColumns.tsx
Labels: enhancement, editor

#957 TNO-1496 (updates for larger files)
  api/net/appsettings.json
  app/editor/nginx/default.conf
  network/nginx/config/default.conf
Labels: bug

#959 TNO-1315 Fix test env domain
  app/editor/src/features/admin/charts/ChartTemplateFormOptions.tsx
  app/editor/src/features/admin/ingests/IngestSettings.tsx
  app/editor/src/features/admin/ingests/configurations/FrontPage.tsx
  docker-compose.yml
  libs/net/dal/Migrations/Initial/Up/PostUp/00-Connection.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  libs/net/template/ReportEngine.cs
  openshift/kustomize/api/base/route-editor.yaml
  openshift/kustomize/api/base/route-subscriber.yaml
  openshift/kustomize/api/overlays/dev/kustomization.yaml
  openshift/kustomize/api/overlays/prod/kustomization.yaml
  openshift/kustomize/api/overlays/test/kustomization.yaml
  openshift/kustomize/app/editor/base/route.yaml
  openshift/kustomize/app/editor/overlays/dev/kustomization.yaml
  openshift/kustomize/app/editor/overlays/prod/kustomization.yaml
  openshift/kustomize/app/editor/overlays/test/kustomization.yaml
  openshift/kustomize/app/subscriber/base/route.yaml
  openshift/kustomize/app/subscriber/overlays/dev/kustomization.yaml
  openshift/kustomize/app/subscriber/overlays/prod/kustomization.yaml
  openshift/kustomize/app/subscriber/overlays/test/kustomization.yaml
  services/net/image/ImageAction.cs
Labels: bug, enhancement, devops

#960 TNO-1177 Fix Image Service
  app/editor/src/features/admin/ingests/configurations/FrontPage.tsx
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
  services/net/image/ImageAction.cs
Labels: bug

#963 TNO-1603: Pls Hide File Explorer and Request...
  app/editor/src/features/navbar/NavBar.tsx
Labels: enhancement

#964 TNO-1601: Hide Clips and Labels tabs from A/V...
  app/editor/src/features/content/form/ContentForm.tsx
Labels: enhancement

#966 fix: #tno-1662 - replace pipe with p tags
  services/net/contentmigration/migrators/PaperMigrator.cs
Labels: bug

#970 fix: #tno-1662 - fixed code touched at last second
  services/net/contentmigration/migrators/PaperMigrator.cs
Labels: bug

#968 fix: #TNO-1657 - fixed timestamp and program/show
  libs/net/kafka/Models/ContentBase.cs
  services/net/content/ContentManager.cs
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/Extensions/NewsItemExtensions.cs
  services/net/contentmigration/migrators/ClipMigrator.cs
  services/net/contentmigration/sources/oracle/Entities/NewsItem.cs
Labels: bug

#965 TNO-1639: Don't Highlight Selected Folder
  app/editor/package.json
  app/subscriber/package.json
  app/subscriber/src/features/my-folders/MyFolders.tsx
  app/subscriber/src/features/my-folders/styled/MyFolders.tsx
  libs/npm/core/src/components/table/FlexboxTable.tsx
  libs/npm/core/src/components/table/interfaces/ITableProps.ts
Labels: enhancement, subscriber, tno-core update

#971 fix: #tno-1657 - fixed bug in default tonepool use
  services/net/contentmigration/migrators/ClipMigrator.cs
  services/net/contentmigration/migrators/PaperMigrator.cs
Labels: bug

#972 fix: #tno-1657 - fixed incorrect timezone issue
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/migrators/ClipMigrator.cs
  services/net/contentmigration/migrators/ContentMigrator.cs
  services/net/contentmigration/migrators/IContentMigrator.cs
  services/net/contentmigration/migrators/ImageMigrator.cs
  services/net/contentmigration/migrators/PaperMigrator.cs
Labels: bug

#967 TNO-1604: Can't Search by Date Range and Source...
  app/editor/src/features/content/list-view/components/tool-bar/filter/AdvancedSearchSection.tsx
Labels: bug

#973 TNO-1630: Create New Error/Validation
  app/subscriber/src/features/my-folders/MyFolders.tsx
Labels: bug, subscriber

#975 fix: #tno-1657 - added logging for time conversion
  services/net/contentmigration/migrators/ClipMigrator.cs
  services/net/contentmigration/migrators/ImageMigrator.cs
  services/net/contentmigration/migrators/PaperMigrator.cs
Labels: bug

#976 Purge Job: Added api-storage cleanup
  openshift/kustomize/cron/base/config-map.yaml
  openshift/kustomize/cron/base/cron-job.yaml
Labels: devops

#977 TNO-1502: [QA] Pls increase default pop out...
  app/editor/src/index.scss
  libs/npm/core/src/components/modal/styled/Modal.tsx
Labels: enhancement, editor

#978 fix: #tno-1633 - fix schedule type disconnect
  libs/net/dal/Migrations/1.0.56/Up/PostUp/00-Ingest.sql
  libs/net/dal/Migrations/20230816221918_1.0.56.Designer.cs
  libs/net/dal/Migrations/20230816221918_1.0.56.cs
Labels: bug

#979 fix: #tno-1682 - updated filters
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/migrators/ClipMigrator.cs
  services/net/contentmigration/migrators/ContentMigrator.cs
  services/net/contentmigration/migrators/IContentMigrator.cs
  services/net/contentmigration/migrators/ImageMigrator.cs
  services/net/contentmigration/migrators/PaperMigrator.cs
Labels: bug

#984 feat: #tno-1684 - added additional mappings
  services/net/contentmigration/appsettings.json
Labels: enhancement

#985 feat: #tno-1590 - updated Series labels
  app/editor/src/features/admin/av-overviews/EditBroadcastDetails.tsx
  app/editor/src/features/admin/series/SeriesForm.tsx
  app/editor/src/features/reports/av-overview/EditBroadcastDetails.tsx
Labels: enhancement

#981 TNO-1626: Improve Ingest Paper Source Mapping Form
  app/editor/src/features/admin/ingests/configurations/Newspaper.tsx
  app/editor/src/features/admin/ingests/configurations/constants/columns.tsx
Labels: enhancement

#988 feat: #tno-1625 - created new kustomize config
  openshift/kustomize/services/contentmigration/base/deploy.yaml
Labels: enhancement

#989 fix: #tno-1686 - fixed incorrect value setter
  app/editor/src/features/admin/ingests/configurations/DbMigration.tsx
Labels: bug

#992 TNO-1369: Database script: Add latest Event...
  libs/net/dal/Migrations/1.0.60/Up/PostUp/00-Topic.sql
  libs/net/dal/Migrations/20230821215054_1.0.60.Designer.cs
  libs/net/dal/Migrations/20230821215054_1.0.60.cs
Labels: enhancement, DB Migration

#994 TNO-1408 Fix MOV keyframe
  app/editor/src/features/content/form/components/upload/Upload.tsx
Labels: bug

#997 TNO-1599: Unauthorized Users should be sent to...
  app/subscriber/src/features/access-request/AccessRequest.tsx
  app/subscriber/src/features/router/AppRouter.tsx
Labels: enhancement, subscriber

#998 TNO-1677: 1) Re-label Products on advanced...
  app/subscriber/src/components/sidebar/advanced-search/components/MediaSection.tsx
  app/subscriber/src/components/sidebar/advanced-search/constants/SubMediaGroups.ts
  app/subscriber/src/components/sidebar/advanced-search/interfaces/ExpansionTracker.ts
  app/subscriber/src/components/sidebar/hooks/useFilterOptions.ts
Labels: enhancement, subscriber

#999 feat: #tno-1550 - updated template and kustomize
  libs/net/dal/Migrations/1.0.61/Up/PostUp/00-Notification.sql
  libs/net/dal/Migrations/20230823192048_1.0.61.Designer.cs
  libs/net/dal/Migrations/20230823192048_1.0.61.cs
  openshift/kustomize/services/notification/base/config-map.yaml
  openshift/kustomize/services/notification/base/deploy.yaml
  openshift/kustomize/services/notification/overlays/dev/config-map.yaml
  openshift/kustomize/services/notification/overlays/prod/config-map.yaml
  openshift/kustomize/services/notification/overlays/test/config-map.yaml
  services/net/notification/NotificationManager.cs
Labels: bug, enhancement

#1000 TNO-1679: Display more content and provide way...
  api/net/Areas/Subscriber/Controllers/ContentController.cs
Labels: enhancement, subscriber

#1001 Advanced search
  app/subscriber/src/features/search-page/SearchPage.tsx
Labels: bug

#1005 TNO-1599 updates
  app/subscriber/src/components/layout/DefaultLayout.tsx
Labels: enhancement, subscriber

#1004 fix: #tno-1697 - updated db migration tasks
  openshift/kustomize/tekton/base/tasks/db-migration-conditional.yaml
  openshift/kustomize/tekton/base/tasks/db-migration.yaml
Labels: bug

#1007 fix: #tno-1709 - fixed issues in content migration
  services/net/contentmigration/ContentMigrationAction.cs
Labels: bug

#1009 TNO-1622: Add grip bars to av overview
  app/editor/src/features/admin/av-overviews/OverviewGrid.tsx
  app/editor/src/features/admin/av-overviews/styled/OverviewGrid.tsx
  app/editor/src/features/reports/av-overview/OverviewGrid.tsx
  app/editor/src/features/reports/av-overview/styled/OverviewGrid.tsx
Labels: enhancement, subscriber

#1010 TNO-1700 Add actions to filters
  app/editor/src/features/admin/filters/FilterFormQuery.tsx
  app/editor/src/features/admin/filters/utils/generateMultiMatch.ts
  app/editor/src/features/admin/filters/utils/generateQuery.ts
  app/editor/src/features/admin/filters/utils/generateQueryForAction.ts
  app/editor/src/features/admin/filters/utils/generateQueryForActions.ts
  app/editor/src/features/admin/filters/utils/generateRangeForArrayField.ts
  app/editor/src/features/admin/filters/utils/generateRangeForDateOffset.ts
  app/editor/src/features/admin/filters/utils/generateRangeForDates.ts
  app/editor/src/features/admin/filters/utils/generateTerms.ts
  app/editor/src/features/admin/filters/utils/getActionOptions.ts
  app/editor/src/features/admin/filters/utils/index.ts
Labels: enhancement, editor

#1012 fix: #tno-1711 - renamed service in yaml
  openshift/kustomize/services/contentmigration-historic/base/config-map.yaml
  openshift/kustomize/services/contentmigration-historic/base/deploy.yaml
  openshift/kustomize/services/contentmigration-historic/base/service.yaml
  openshift/kustomize/services/contentmigration-historic/overlays/dev/kustomization.yaml
  openshift/kustomize/services/contentmigration-historic/overlays/prod/kustomization.yaml
  openshift/kustomize/services/contentmigration-historic/overlays/test/kustomization.yaml
Labels: bug, devops

#1014 TNO-1681 Friendly error messages
  api/net/Areas/Editor/Controllers/AVOverviewController.cs
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Editor/Controllers/IngestController.cs
  api/net/Areas/Editor/Controllers/ReportController.cs
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Areas/Editor/Controllers/SystemMessageController.cs
  api/net/Areas/Editor/Controllers/UserController.cs
  api/net/Areas/Editor/Controllers/WorkOrderController.cs
  api/net/Middleware/ErrorHandlingMiddleware.cs
  app/editor/src/features/admin/filters/utils/generateTermsForArrayField.ts
  app/editor/src/store/hooks/useAjaxWrapper.ts
  app/subscriber/src/store/hooks/useAjaxWrapper.ts
  libs/net/core/Exceptions/NoContentException.cs
  libs/net/dal/Services/ActionService.cs
  libs/net/dal/Services/ContentReferenceService.cs
  libs/net/dal/Services/ContentService.cs
  libs/net/dal/Services/IngestService.cs
  libs/net/dal/Services/NotificationService.cs
  libs/net/dal/Services/ReportService.cs
  libs/net/dal/Services/ReportTemplateService.cs
  libs/net/dal/Services/SourceService.cs
  libs/net/dal/Services/UserService.cs
Labels: bug, enhancement, subscriber, editor

#1015 fix: #tno-1712 - added lookup for contenttype
  services/net/contentmigration/ContentMigrationAction.cs
Labels: bug

#1013 TNO-1628: Remove formatting tool in WYSIWYG...
  app/editor/src/components/wysiwyg/Wysiwyg.tsx
  app/subscriber/src/components/form/wysiwyg/Wysiwyg.tsx
Labels: enhancement, subscriber, editor

#1020 fix: #tno-1714 - applied filter logic
  api/net/Areas/Services/Controllers/ContentController.cs
Labels: bug

#995 feat: #Tno-1526 - Handle Updating Edited Content
  api/net/Areas/Services/Controllers/ContentReferenceController.cs
  libs/net/dal/Migrations/20230828190039_1.0.63.Designer.cs
  libs/net/dal/Migrations/20230828190039_1.0.63.cs
  libs/net/entities/ContentReference.cs
  libs/net/models/Areas/Services/Models/ContentReference/ContentReferenceModel.cs
  libs/net/tests/dal/TnoTestContext.cs
  services/net/capture/CaptureAction.cs
  services/net/clip/ClipAction.cs
  services/net/content/Config/ContentMigrationOptions.cs
  services/net/content/ContentManager.cs
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/migrators/ContentMigrator.cs
  services/net/filemonitor/FilemonitorAction.cs
  services/net/image/ImageAction.cs
  services/net/syndication/SyndicationAction.cs
Labels: enhancement

#1021 TNO-1618 updates
  libs/net/elastic/ITNOElasticClient.cs
  libs/net/elastic/TNOElasticClient.cs
Labels: enhancement

#1022 fix: #tno-1715 - exclude data with NULL Source
  services/net/contentmigration/ContentMigrationAction.cs
Labels: bug

#1025 Fixing Elasticsearch sort bug
  libs/net/elastic/Models/HitModel.cs
  libs/net/elastic/TNOElasticClient.cs
Labels: bug

#1019 TNO-1658 updates
  libs/net/core/Http/HttpRequestClient.cs
  libs/net/core/Http/IHttpRequestClient.cs
  libs/net/services/Helpers/ApiService.cs
Labels: bug
