Repository bcgov/tno, pull requests merged in 2023-07, with the labels that each got.

#880 TNO-1471: [QA] Thumbnails are missing from front page images editors screen
  app/editor/src/features/content/form/components/upload/Upload.tsx
Labels: bug

#874 feat: #tno-1404 - time and effort now migrated
  libs/net/kafka/Models/ContentBase.cs
  libs/net/kafka/Models/TimeTrackingModel.cs
  libs/net/models/Areas/Admin/TimeTracking/TimeTrackingModel.cs
  libs/net/models/Areas/Services/Models/Content/ContentModel.cs
  libs/net/models/Areas/Services/Models/Content/ContentTimeTrackingModel.cs
  services/net/content/ContentManager.cs
  services/net/contentmigration/Config/ContentMigrationOptions.cs
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/Extensions/NewsItemExtensions.cs
  services/net/contentmigration/migrators/ClipMigrator.cs
  services/net/contentmigration/migrators/ContentMigrator.cs
  services/net/contentmigration/migrators/ImageMigrator.cs
  services/net/contentmigration/migrators/PaperMigrator.cs
Labels: enhancement

#876 TNO-1476: [QA] Pls check timestamp for report...
  libs/net/dal/Migrations/1.0.37/Up/PostUp/00-Report.sql
  libs/net/dal/Migrations/20230704172733_1.0.37.Designer.cs
  libs/net/dal/Migrations/20230704172733_1.0.37.cs
Labels: bug, DB Migration

#877 TNO-1442: (Database script) Add South Okanagan...
  libs/net/dal/Migrations/1.0.38/Up/PostUp/00-Ingest.sql
  libs/net/dal/Migrations/20230704182340_1.0.38.Designer.cs
  libs/net/dal/Migrations/20230704182340_1.0.38.cs
Labels: enhancement, DB Migration

#878 TNO-1440: (Database Script) 1. Add Columbia Valley
  libs/net/dal/Migrations/1.0.39/Up/PostUp/00-Ingest.sql
  libs/net/dal/Migrations/20230704192737_1.0.39.Designer.cs
  libs/net/dal/Migrations/20230704192737_1.0.39.cs
Labels: enhancement, DB Migration

#879 TNO-1347: (Database Script) Update Product List...
  libs/net/dal/Migrations/1.0.40/Up/PostUp/00-Product.sql
  libs/net/dal/Migrations/20230704200657_1.0.40.Designer.cs
  libs/net/dal/Migrations/20230704200657_1.0.40.cs
Labels: enhancement, DB Migration

#881 TNO-1476 (Fix a compile issue)
  libs/net/dal/Migrations/1.0.37/Up/PostUp/00-Report.sql
Labels: bug, DB Migration

#882 fix: #tno-1404 - fixed label-tag mismatch
  services/net/filemonitor/FilemonitorAction.cs
Labels: bug

#889 TNO-1534: Missing image in Reports
  api/net/Areas/Admin/Controllers/ReportController.cs
  libs/net/template/Models/Reports/ReportSectionModel.cs
  libs/net/template/Models/Reports/TemplateModel.cs
  services/net/reporting/ReportingManager.cs
Labels: bug

#891 Small bug
  app/subscriber/src/features/my-minister/MyMinister.tsx
Labels: bug

#893 Bug fix - My Minister
  app/subscriber/src/features/my-minister/MyMinister.tsx
Labels: bug

#894 Fix Image/Syndication/Content Services
  libs/net/kafka/Models/ContentBase.cs
  libs/net/kafka/Models/SourceContent.cs
  libs/net/services/Actions/IngestAction.cs
  libs/net/services/Managers/IngestManager`.cs
  openshift/kustomize/api/base/deploy.yaml
  openshift/kustomize/api/base/statefulset.yaml
  services/net/image/ImageAction.cs
  services/net/syndication/SyndicationAction.cs
  services/net/syndication/Xml/Rss/RssItem.cs
Labels: bug

#899 My Minister bug
  app/subscriber/src/features/my-minister/MyMinister.tsx
Labels: bug

#900 TNO-1476 updates
  libs/net/dal/Migrations/1.0.45/Up/PostUp/00-Report.sql
  libs/net/dal/Migrations/20230712165628_1.0.45.Designer.cs
  libs/net/dal/Migrations/20230712165628_1.0.45.cs
Labels: bug, DB Migration

#895 TNO-1462: [QA] stories published from the AM...
  app/subscriber/src/features/content/view-content/ViewContent.tsx
Labels: bug, subscriber

#902 TNO-1476 updates
  libs/net/dal/Migrations/1.0.45/Up/PostUp/00-Report.sql
Labels: bug

#904 fix: #tno-1538 - switch Label and Name
  services/net/syndication/SyndicationAction.cs
Labels: bug

#901 feat: #tno-1490 - first pass at openshift config
  openshift/kustomize/services/build/base/contentmigration.yaml
  openshift/kustomize/services/build/base/kustomization.yaml
  openshift/kustomize/services/contentmigration/base/config-map.yaml
  openshift/kustomize/services/contentmigration/base/deploy.yaml
  openshift/kustomize/services/contentmigration/base/kustomization.yaml
  openshift/kustomize/services/contentmigration/base/service.yaml
  openshift/kustomize/services/contentmigration/overlays/dev/kustomization.yaml
  openshift/kustomize/services/contentmigration/overlays/prod/kustomization.yaml
  openshift/kustomize/services/contentmigration/overlays/test/kustomization.yaml
  services/net/contentmigration/Config/ContentMigrationOptions.cs
  services/net/contentmigration/Config/OracleConnectionSettings.cs
  services/net/contentmigration/ContentMigrationAction.cs
  services/net/contentmigration/appsettings.json
  services/net/contentmigration/migrators/ContentMigrator.cs
  services/net/contentmigration/sources/oracle/MigrationSourceContext.cs
  services/net/contentmigration/sources/oracle/Services/OracleConnectionStringHelper.cs
  services/net/contentmigration/sources/oracle/Services/ServiceCollectionExtensions.cs
Labels: enhancement

#905 TNO-1507: UI for advanced search
  app/subscriber/src/components/sidebar/CustomSidebar.tsx
  app/subscriber/src/components/sidebar/advanced-search/AdvancedSearch.tsx
  app/subscriber/src/components/sidebar/advanced-search/constants/SubMediaGroups.ts
  app/subscriber/src/components/sidebar/advanced-search/constants/index.ts
  app/subscriber/src/components/sidebar/advanced-search/index.ts
  app/subscriber/src/components/sidebar/advanced-search/styled/AdvancedSearch.tsx
  app/subscriber/src/components/sidebar/advanced-search/styled/index.ts
  app/subscriber/src/features/landing/styled/Landing.tsx
Labels: enhancement, subscriber

#908 TNO-1536: Update Templates to exclude Sort...
  libs/net/dal/Migrations/1.0.48/Up/PostUp/00-MorningReport.sql
  libs/net/dal/Migrations/20230717170924_1.0.48.Designer.cs
  libs/net/dal/Migrations/20230717170924_1.0.48.cs
Labels: enhancement, DB Migration

#909 Tno-636 - create my ministers Admin view
  api/net/Areas/Admin/Controllers/MinisterController.cs
  api/net/Areas/Subscriber/Controllers/MinisterController.cs
  app/editor/.yarn/cache/tno-core-npm-0.0.276-6611d1f101-8ffa9aadf1.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/admin/AdminRouter.tsx
  app/editor/src/features/admin/index.ts
  app/editor/src/features/admin/ministers/MinisterFilter.tsx
  app/editor/src/features/admin/ministers/MinisterForm.tsx
  app/editor/src/features/admin/ministers/MinisterList.tsx
  app/editor/src/features/admin/ministers/constants/columns.tsx
  app/editor/src/features/admin/ministers/constants/defaultMinister.ts
  app/editor/src/features/admin/ministers/constants/index.ts
  app/editor/src/features/admin/ministers/index.ts
  app/editor/src/features/admin/ministers/styled/MinisterForm.tsx
  app/editor/src/features/admin/ministers/styled/MinisterList.tsx
  app/editor/src/features/admin/ministers/styled/MinisterListFilter.tsx
  app/editor/src/features/admin/ministers/styled/index.ts
  app/editor/src/features/navbar/NavBar.tsx
  app/editor/src/store/hooks/admin/index.ts
  app/editor/src/store/slices/admin/adminSlice.ts
  app/editor/src/store/slices/admin/interfaces/IAdminState.ts
  app/editor/src/store/slices/admin/useAdminStore.ts
  app/editor/yarn.lock
  app/subscriber/.yarn/cache/tno-core-npm-0.0.276-6611d1f101-8ffa9aadf1.zip
  app/subscriber/package.json
  app/subscriber/src/store/hooks/admin/useMinisters.ts
  app/subscriber/src/store/slices/admin/useAdminStore.ts
  app/subscriber/yarn.lock
  libs/net/models/Areas/Admin/Minister/MinisterModel.cs
  libs/npm/README.md
  libs/npm/core/.yarn/install-state.gz
  libs/npm/core/package.json
  libs/npm/core/yarn.lock
Labels: enhancement

#910 TNO-1543: Content Image Does Not Display Correctly
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/MediaSummary.tsx
Labels: bug

#911 TNO-1535: Ensure Top Stories, Commentary pages...
  app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
  app/subscriber/src/features/top-stories/TopStories.tsx
  libs/net/dal/Models/ContentFilter.cs
Labels: enhancement

#912 TNO-1551: Add folders navigation
  app/subscriber/src/components/layout/constants/SidebarMenuItems.tsx
Labels: enhancement, subscriber

#913 feat: #1562 - add configurable delay for migration
  app/editor/src/features/admin/ingests/configurations/DbMigration.tsx
  services/net/contentmigration/ContentMigrationAction.cs
Labels: enhancement

#914 TNO-1444: Troubleshoot why Daily Hive keeps failing
  libs/net/dal/Migrations/1.0.49/Up/PostUp/00-Ingest.sql
  libs/net/dal/Migrations/20230718214004_1.0.49.Designer.cs
  libs/net/dal/Migrations/20230718214004_1.0.49.cs
Labels: bug, DB Migration

#915 feat: #tno-1489 - no re-alerting on migration
  services/net/contentmigration/migrators/ContentMigrator.cs
Labels: enhancement

#916 TNO-1537: Error Occurring With TimeTracking...
  libs/net/models/Areas/Services/Models/Content/TimeTrackingModel.cs
Labels: bug

#918 fix: #tno-1459 - channel was not being updated
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/admin/ministers/MinisterList.tsx
  app/editor/src/features/content/papers/Papers.tsx
Labels: bug

#917 TNO-1334: Basics of AV Overview
  api/net/Areas/Editor/Controllers/AVOverviewSectionItemController.cs
  app/editor/.yarn/cache/@babel-runtime-npm-7.22.6-493f6b7ad0-e585338287.zip
  app/editor/.yarn/cache/@types-react-beautiful-dnd-npm-13.1.4-5fc92fb3be-76220f1031.zip
  app/editor/.yarn/cache/css-box-model-npm-1.2.1-d4e0001730-4d113f26fe.zip
  app/editor/.yarn/cache/memoize-one-npm-5.2.1-ee0f8be979-a3cba7b824.zip
  app/editor/.yarn/cache/raf-schd-npm-4.0.3-18f72af738-45514041c5.zip
  app/editor/.yarn/cache/react-beautiful-dnd-npm-13.1.1-ddc8adf565-5f90f7c0ab.zip
  app/editor/.yarn/cache/react-redux-npm-7.2.9-612aa35519-369a2bdcf8.zip
  app/editor/.yarn/cache/redux-npm-4.2.1-e7e2cf2e37-f63b9060c3.zip
  app/editor/.yarn/cache/tiny-invariant-npm-1.3.1-a8ca214e49-872dbd1ff2.zip
  app/editor/.yarn/cache/use-memo-one-npm-1.1.3-b9dc77468a-8f08eba26d.zip
  app/editor/.yarn/install-state.gz
  app/editor/package.json
  app/editor/src/features/admin/AdminRouter.tsx
  app/editor/src/features/admin/evening-overview/EveningOverview.tsx
  app/editor/src/features/admin/evening-overview/constants/EveningOverviewItemType.ts
  app/editor/src/features/admin/evening-overview/constants/EveningOverviewItemTypeName.ts
  app/editor/src/features/admin/evening-overview/constants/defaultSection.ts
  app/editor/src/features/admin/evening-overview/constants/index.ts
  app/editor/src/features/admin/evening-overview/index.ts
  app/editor/src/features/admin/evening-overview/interfaces/IEveningOverviewItem.ts
  app/editor/src/features/admin/evening-overview/interfaces/IEveningOverviewSection.ts
  app/editor/src/features/admin/evening-overview/interfaces/index.ts
  app/editor/src/features/admin/evening-overview/overview-grid/OverviewGrid.tsx
  app/editor/src/features/admin/evening-overview/overview-grid/index.ts
  app/editor/src/features/admin/evening-overview/overview-grid/styled/OverviewGrid.tsx
  app/editor/src/features/admin/evening-overview/overview-grid/styled/index.ts
  app/editor/src/features/admin/evening-overview/overview-section/EditBroadcastDetails.tsx
  app/editor/src/features/admin/evening-overview/overview-section/OverviewSection.tsx
  app/editor/src/features/admin/evening-overview/overview-section/index.ts
  app/editor/src/features/admin/evening-overview/overview-section/styled/EditBroadcastDetails.tsx
  app/editor/src/features/admin/evening-overview/overview-section/styled/OverviewSection.tsx
  app/editor/src/features/admin/evening-overview/overview-section/styled/index.ts
  app/editor/src/features/admin/evening-overview/styled/EveningOverview.tsx
  app/editor/src/features/admin/evening-overview/styled/index.ts
  app/editor/src/features/navbar/NavBar.tsx
  app/editor/src/store/hooks/admin/useEveningOverviews.ts
  app/editor/src/store/hooks/api/index.ts
  app/editor/src/store/hooks/api/useApiEveningOverview.ts
  app/editor/src/store/slices/admin/adminSlice.ts
  app/editor/src/store/slices/admin/interfaces/IAdminState.ts
  app/editor/src/store/slices/admin/useAdminStore.ts
  app/editor/yarn.lock
  app/subscriber/src/store/hooks/subscriber/interfaces/IMinisterModel.ts
  libs/net/dal/Models/EveningOverviewItemFilter.cs
  libs/net/dal/Services/AVOverviewSectionItemService.cs
  libs/net/dal/Services/Interfaces/IAVOverviewSectionItemService.cs
  libs/net/entities/AVOverviewSection.cs
  libs/net/entities/AVOverviewSectionItem.cs
  libs/net/models/Areas/Editor/Models/AVOverview/AVOverviewSectionItemModel.cs
  libs/net/models/Areas/Editor/Models/AVOverview/AvOverviewSectionModel.cs
Labels: enhancement, tno-core update, editor

#921 fix: #tno-1565 - fix lint error
  api/net/Areas/Admin/Controllers/MinisterController.cs
Labels: bug

#924 fix: #tno-1130 - fix audo clip layout in Editor
  app/editor/src/features/content/form/components/upload/Upload.tsx
  app/editor/src/features/content/form/components/upload/styled/Upload.tsx
Labels: bug

#927 feat: #tno-1533 - change layout of subscriber page
  app/subscriber/src/features/commentary/styled/Commentary.tsx
  app/subscriber/src/features/front-pages/styled/FrontPages.tsx
  app/subscriber/src/features/landing/styled/Landing.tsx
Labels: enhancement

#926 fix: #tno-1576 - hide aliases on my ministers page
  app/subscriber/src/features/settings/MyMinisterSettings.tsx
  app/subscriber/src/features/settings/styled/MyMinisterSettings.tsx
Labels: bug

#931 fix: #tno-1582 - aliases not showing up
  app/subscriber/src/features/content/view-content/ViewContent.tsx
Labels: bug

#930 fix: #tno-1130 - fix audo clip layout in Editor
  app/subscriber/src/features/content/view-content/ViewContent.tsx
  app/subscriber/src/features/search-page/player/Player.tsx
Labels: bug

#934 fix: #tno-1565 - fix disabled ministers message
  app/subscriber/src/features/settings/MyMinisterSettings.tsx
Labels: bug

#929 TNO-1472: [QA] saving new Topics/Event of the...
  app/editor/src/components/layout/DefaultLayout.tsx
  app/editor/src/features/admin/topics/TopicList.tsx
  app/editor/src/features/admin/topics/constants/columns.tsx
  app/editor/src/features/admin/topics/constants/index.ts
  app/editor/src/features/admin/topics/index.ts
  app/editor/src/features/admin/topics/styled/TopicList.tsx
  app/editor/src/features/admin/topics/useColumns.tsx
  libs/npm/core/src/components/form/select/Select.tsx
  libs/npm/core/src/components/formik/select/FormikSelect.tsx
  libs/npm/core/src/components/table/FlexboxTable.tsx
  libs/npm/core/src/components/table/styled/FlexboxTable.tsx
Labels: enhancement, tno-core update, editor
