Repository bcgov/tno, pull requests merged in 2023-05, with the labels that each got.

#694 TNO-1221 Add Commentary Default Expiry Value
  app/editor/src/features/content/form/ContentActions.tsx
Labels: enhancement

#695 TNO-1078 Replace work order table
  api/net/Areas/Admin/Controllers/WorkOrderController.cs
  app/editor/src/features/admin/topics/styled/TopicList.tsx
  app/editor/src/features/admin/work-orders/WorkOrderForm.tsx
  app/editor/src/features/admin/work-orders/WorkOrderList.tsx
  app/editor/src/features/admin/work-orders/constants/columns.tsx
  app/editor/src/features/admin/work-orders/constants/defaultWorkOrder.ts
  libs/net/dal/Services/TopicService.cs
Labels: bug

#688 TNO-1048 updates
  libs/net/dal/Services/IngestService.cs
  libs/net/dal/Services/SourceService.cs
Labels: bug

#697 TNO-1077 Add headline to work order
  app/editor/src/features/admin/work-orders/WorkOrderForm.tsx
  app/editor/src/features/admin/work-orders/WorkOrderList.tsx
  app/editor/src/features/admin/work-orders/constants/columns.tsx
  app/editor/src/features/admin/work-orders/styled/WorkOrderList.tsx
  app/editor/src/features/content/form/utils/getDefaultCommentaryExpiryValue.ts
  libs/net/dal/Services/WorkOrderService.cs
  libs/net/entities/WorkOrder.cs
Labels: enhancement

#698 Fix workorder table column
  app/editor/src/features/admin/work-orders/styled/WorkOrderList.tsx
Labels: bug

#701 Fix reporting service image
  services/net/reporting/Dockerfile
Labels: bug

#703 TNO-1252 Fix indexing published content
  services/net/indexing/IndexingManager.cs
Labels: bug

#705 Fix editor permission
  app/editor/src/features/router/AppRouter.tsx
Labels: bug

#709 Fix TNO-1191
  libs/net/core/Extensions/StringExtensions.cs
Labels: bug, enhancement

#699 TNO-1199
  libs/net/dal/Migrations/1.0.12/Up/PostUp/00-NotificationRazorTemplate.sql
  libs/net/dal/Migrations/20230502192947_1.0.12.Designer.cs
  libs/net/dal/Migrations/20230502192947_1.0.12.cs
  libs/net/models/Areas/Services/Models/Content/ContentModel.cs
  services/net/notification/Config/NotificationOptions.cs
  services/net/notification/Models/TemplateModel.cs
  services/net/notification/NotificationManager.cs
  services/net/notification/appsettings.Development.json
  services/net/notification/appsettings.Staging.json
  services/net/notification/appsettings.json
Labels: enhancement, DB Migration

#713 Fix alert message
  app/editor/src/features/home/InfoText.tsx
  app/editor/src/features/home/styled/InfoPanel.tsx
Labels: bug

#710 Fix TNO-1048
  api/net/Middleware/ErrorHandlingMiddleware.cs
  libs/net/css/CssClient.cs
  libs/net/models/Areas/Admin/ContentReference/ContentReferenceModel.cs
  libs/net/services/Actions/IngestAction.cs
  libs/net/services/Actions/Managers/IngestActionManager`.cs
  libs/net/services/Managers/ServiceManager`.cs
Labels: bug

#716 TNO-1239 Init topic score rules
  libs/net/dal/Migrations/1.0.14/Down/PostDown/00-TopicScoreRule.sql
  libs/net/dal/Migrations/1.0.14/Up/PostUp/00-TopicScoreRule.sql
  libs/net/dal/Migrations/1.0.14/Up/PostUp/02-Source.sql
  libs/net/dal/Migrations/20230508183557_1.0.14.Designer.cs
  libs/net/dal/Migrations/20230508183557_1.0.14.cs
Labels: enhancement, DB Migration

#715 Fix TNO-1267
  app/editor/src/features/content/form/ImageSection.tsx
Labels: bug

#717 TNO-1161 Fix date filter icon
  app/editor/src/features/content/tool-bar/sections/filter/DateRangeSection.tsx
  app/editor/src/features/content/tool-bar/sections/filter/styled/DateRangeSection.tsx
Labels: bug

#711 Fix TNO-1175
  app/editor/src/env.json
  app/editor/src/features/admin/topic-score-rules/validation/TopicScoreRuleSchema.ts
  app/editor/src/index.scss
  libs/npm/core/package.json
  libs/npm/core/src/components/button/Button.tsx
  libs/npm/core/src/components/button/index.ts
  libs/npm/core/src/components/button/styled/Button.tsx
  libs/npm/core/src/components/dialog/dialog.scss
  libs/npm/core/src/components/tabs/Tab.tsx
  libs/npm/core/src/hooks/api-editor/validation/AdvancedScheduleSchema.ts
  libs/npm/core/src/hooks/api-editor/validation/AuditColumnsSchema.ts
  libs/npm/core/src/hooks/api-editor/validation/ScheduleSchema.ts
  libs/npm/core/src/hooks/api-subscriber/useApiSubscriberContents.ts
  libs/npm/core/src/hooks/index.ts
Labels: enhancement

#719 Fix TNO-1265
  app/editor/src/features/content/morning-papers/components/ReportActions.tsx
Labels: enhancement

#720 Fix TNO-1264
  app/editor/src/features/content/morning-papers/MorningReports.tsx
  app/editor/src/features/content/morning-papers/constants/columns.tsx
Labels: enhancement

#718 Fix TNO-1270
  libs/net/core/Extensions/StringExtensions.cs
Labels: bug

#721 Fix TNO-1080
  libs/npm/core/src/components/toggle-group/ToggleGroup.tsx
Labels: bug

#723 Update action buttons
  app/subscriber/src/App.tsx
  app/subscriber/src/features/content/view-content/ViewContentToolbar.tsx
  app/subscriber/src/features/content/view-content/constants/ActionNames.ts
  app/subscriber/src/features/content/view-content/constants/index.ts
  app/subscriber/src/features/content/view-content/styled/ViewContentToolbar.tsx
  app/subscriber/src/features/home/Home.tsx
Labels: enhancement, subscriber

#727 TNO-1237: Source name not code
  app/subscriber/src/features/home/Home.tsx
  libs/net/models/Areas/Services/Models/Content/ContentModel.cs
Labels: bug, subscriber

#724 TNO-1048 updates
  libs/net/core/TNO.Core.csproj
  libs/net/dal/Services/BaseService`.cs
  libs/net/dal/TNO.DAL.csproj
  libs/net/entities/TNO.Entities.csproj
  libs/net/models/Areas/Services/Models/WorkOrder/WorkOrderModel.cs
  services/net/content/ContentManager.cs
Labels: bug

#729 TNO-1175 updates
  app/editor/src/features/admin/topic-score-rules/validation/TopicScoreRuleSchema.ts
  app/editor/src/features/content/validation/ContentFormSchema.ts
  libs/npm/core/src/hooks/api-editor/editor/index.ts
  libs/npm/core/src/hooks/api-editor/editor/useApiAnonAlerts.ts
  libs/npm/core/src/hooks/api-editor/validation/AdvancedScheduleSchema.ts
  libs/npm/core/src/hooks/api-editor/validation/AuditColumnsSchema.ts
  libs/npm/core/src/hooks/api-editor/validation/ScheduleSchema.ts
  libs/npm/core/src/hooks/api-subscriber/index.ts
  libs/npm/core/src/hooks/api-subscriber/useApiAlerts.ts
  libs/npm/core/src/hooks/index.ts
Labels: enhancement

#733 TNO-474 Debug Content Service Issue
  api/net/Areas/Services/Controllers/ContentController.cs
  api/net/Program.cs
  libs/net/services/Helpers/ApiService.cs
Labels: bug

#735 Fix Content Service
  services/net/content/ContentManager.cs
Labels: bug

#736 TNO-474 Update report cache
  api/net/Areas/Admin/Controllers/NotificationController.cs
  api/net/Areas/Admin/Controllers/ReportController.cs
  services/net/content/ContentManager.cs
Labels: enhancement

#737 TNO-474 Fix Report/Notification Template
  services/net/notification/NotificationManager.cs
  services/net/reporting/ReportingManager.cs
  services/net/reporting/ReportingService.cs
Labels: bug

#739 Fix TNO-1201
  libs/net/entities/Models/NotificationFilter.cs
  libs/net/entities/Validation/NotificationValidator.cs
Labels: enhancement

#741 TNO-1208 Use elastic filter in reporting service
  api/net/Areas/Services/Controllers/ReportController.cs
  app/editor/src/features/admin/reports/ReportForm.tsx
  libs/net/TNO.sln
  libs/net/dal/Elasticsearch/TNOElasticClient.cs
  libs/net/dal/Extensions/ServiceCollectionExtensions.cs
  libs/net/dal/Services/ContentService.cs
  libs/net/dal/Services/Interfaces/IContentService.cs
  libs/net/dal/Services/Interfaces/IReportService.cs
  libs/net/dal/Services/ReportService.cs
  libs/net/dal/TNO.DAL.csproj
  libs/net/elastic/Config/ElasticOptions.cs
  libs/net/elastic/Extensions/ServiceCollectionExtensions.cs
  libs/net/elastic/ITNOElasticClient.cs
  libs/net/elastic/Models/HitModel.cs
  libs/net/elastic/Models/HitsModel.cs
  libs/net/elastic/Models/SearchResultModel.cs
  libs/net/elastic/Models/ShardsModel.cs
  libs/net/elastic/Models/TotalModel.cs
  libs/net/elastic/TNO.Elastic.csproj
  libs/net/elastic/TNOElasticClient.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Interfaces/IApiService.cs
  libs/net/services/TNO.Services.csproj
  services/net/reporting/ReportingManager.cs
Labels: enhancement

#732 TNO-1048 (publish related updates)
  api/net/Areas/Editor/Controllers/ContentController.cs
  libs/net/services/Actions/IngestAction.cs
  services/net/content/ContentManager.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#744 TNO-474 Enhance report admin form
  app/editor/.yarn/cache/@types-prismjs-npm-1.26.0-e89ec94ae4-cd5e7a6214.zip
  app/editor/.yarn/cache/babel-plugin-prismjs-npm-2.1.0-487daf4f78-8bc59ca46b.zip
  app/editor/.yarn/cache/prismjs-npm-1.29.0-6faa5b04b8-007a8869d4.zip
  app/editor/.yarn/cache/react-simple-code-editor-npm-0.13.1-75bf152696-1d223e34cc.zip
  app/editor/.yarn/install-state.gz
  app/editor/config-overrides.js
  app/editor/package.json
  app/editor/src/@types/prism.d.ts
  app/editor/src/App.tsx
  app/editor/src/components/wysiwyg/CustomToolbar.tsx
  app/editor/src/components/wysiwyg/Wysiwyg.tsx
  app/editor/src/components/wysiwyg/index.ts
  app/editor/src/components/wysiwyg/styled/Wysiwyg.tsx
  app/editor/src/components/wysiwyg/styled/index.ts
  app/editor/src/features/admin/ingests/constants/columns.tsx
  app/editor/src/features/admin/reports/ReportForm.tsx
  app/editor/src/features/admin/reports/styled/ReportForm.tsx
  app/editor/yarn.lock
  libs/net/elastic/Models/HitsModel.cs
  libs/net/elastic/TNOElasticClient.cs
Labels: enhancement

#740 Published Index
  api/net/Areas/Editor/Controllers/ContentController.cs
  api/net/Areas/Subscriber/Controllers/ContentController.cs
  libs/net/dal/Services/ContentService.cs
  libs/net/dal/Services/Interfaces/IContentService.cs
Labels: bug

#745 feat(Monitoring): Added Sysdig & Kibana Dashboard.
  openshift/monitoring/Kibana/TNO_Kibana_Dashboard_Visualization.json
  openshift/monitoring/Kibana/TNO_Kibana_Dashoard.json
  openshift/monitoring/Kibana/filter_apps_index.json
  openshift/monitoring/sysdig/Monitoring.md
  openshift/monitoring/sysdig/images/my_teams.png
  openshift/monitoring/sysdig/tno-sysdig-access.yaml
Labels: devops

#748 Fix TNO-1287
  app/editor/src/features/content/morning-papers/components/ContentFilter.tsx
Labels: bug

#752 TNO-1300 Fix content tab buttons
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/components/index.ts
  app/editor/src/features/content/form/components/tool-bar/ContentFormToolBar.tsx
  app/editor/src/features/content/form/components/tool-bar/form/ActionSection.tsx
  app/editor/src/features/content/form/components/tool-bar/form/AlertSection.tsx
  app/editor/src/features/content/form/components/tool-bar/form/StatusSection.tsx
  app/editor/src/features/content/form/components/tool-bar/form/index.ts
  app/editor/src/features/content/form/components/tool-bar/index.ts
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/components/index.ts
  app/editor/src/features/content/list-view/components/tool-bar/ContentToolBar.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/AdvancedSearchSection.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/CreateNewSection.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/DateRangeSection.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/FilterContentSection.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/InputOption.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/ShowOnlySection.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/index.ts
  app/editor/src/features/content/list-view/components/tool-bar/filter/styled/CreateNewSection.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/styled/DateRangeSection.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/styled/SelectLabel.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/styled/index.ts
  app/editor/src/features/content/list-view/components/tool-bar/index.ts
  app/editor/src/features/content/morning-papers/MorningReportsFilter.tsx
  app/editor/src/features/content/morning-papers/components/ContentFilter.tsx
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
Labels: bug

#753 Tno crunchy fix
  openshift/kustomize/postgres/crunchy/README.md
  openshift/kustomize/postgres/crunchy/base/deploy.yaml
  openshift/kustomize/tekton/base/tasks/buildah.yaml
  openshift/kustomize/tekton/base/tasks/db-migration-conditional.yaml
  openshift/kustomize/tekton/base/tasks/db-migration.yaml
  openshift/kustomize/tekton/base/tasks/elastic-migration.yaml
  openshift/kustomize/tekton/base/tasks/pipeline-wait.yaml
Labels: bug, documentation, devops

#755 Fix TNO-1306
  app/editor/src/features/content/list-view/components/tool-bar/filter/ShowOnlySection.tsx
Labels: bug

#756 TNO-1299 Publish will reset form
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/components/time-log/TimeLogSection.tsx
  app/editor/src/features/content/form/components/upload/styled/Upload.tsx
  app/editor/src/features/content/form/styled/ContentForm.tsx
  app/editor/src/features/content/form/styled/MediaSummary.tsx
  app/editor/src/features/content/hooks/index.ts
  app/editor/src/features/content/hooks/useTab.tsx
  app/editor/src/features/content/index.ts
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/list-view/components/tool-bar/filter/CreateNewSection.tsx
  app/editor/src/features/content/list-view/constants/columns.tsx
Labels: enhancement

#751 Fix TNO-1302
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/ImageSection.tsx
  app/editor/src/features/content/form/MediaSummary.tsx
Labels: enhancement

#763 Fix TNO-1298
  app/editor/src/features/content/list-view/styled/ContentListView.tsx
Labels: bug, enhancement

#758 TNO-1295: New icon for A/V content
  app/subscriber/src/features/commentary/utils/DetermineContentIcon.tsx
Labels: subscriber

#760 TNO-1320: Add space between column and page
  app/subscriber/src/features/home/constants/columns.tsx
Labels: bug

#762 Fix TNO-1344
  libs/net/dal/Migrations/1.0.18/Up/PostUp/00-ProductListCleanUp.sql
  libs/net/dal/Migrations/20230529170651_1.0.18.Designer.cs
  libs/net/dal/Migrations/20230529170651_1.0.18.cs
  libs/net/dal/Migrations/Initial/Up/PostUp/00-Product.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/01-Source.sql
  libs/net/dal/Migrations/Initial/Up/PostUp/02-Ingest.sql
Labels: enhancement, DB Migration

#765 TNO-1217 - Add admin report subscribers
  api/net/Areas/Admin/Controllers/ReportController.cs
  app/editor/src/components/formik/form/FormikForm.tsx
  app/editor/src/features/admin/reports/ReportFilter.tsx
  app/editor/src/features/admin/reports/ReportForm.tsx
  app/editor/src/features/admin/reports/constants/index.ts
  app/editor/src/features/admin/reports/constants/subscriberColumns.tsx
  app/editor/src/features/admin/reports/styled/ReportForm.tsx
  libs/net/dal/Services/ReportService.cs
  libs/net/entities/UserReport.cs
  libs/net/models/Areas/Admin/Report/ReportModel.cs
Labels: enhancement

#764 TNO-1302 updates
  app/editor/src/features/content/validation/ContentFormSchema.ts
Labels: bug, enhancement

#766 TNO-1293: Adjust font size for table header
  app/subscriber/src/features/home/styled/Home.tsx
Labels: subscriber

#768 TNO-1297: Can now scroll unauthenticated home on mobile
  app/subscriber/src/features/login/styled/UnauthenticatedHome.tsx
Labels: bug, subscriber

#769 TNO-1289: Page/section should only show on print
  app/subscriber/src/features/home/Home.tsx
  app/subscriber/src/features/home/constants/columns.tsx
Labels: bug, subscriber

#767 Fix TNO-1303
  libs/net/dal/Migrations/1.0.17/Up/PostUp/01-Source.sql
  libs/net/dal/Migrations/1.0.19/Up/PostUp/00-SourceSortOrder.sql
  libs/net/dal/Migrations/20230529233959_1.0.19.Designer.cs
  libs/net/dal/Migrations/20230529233959_1.0.19.cs
  libs/npm/core/src/utils/getSourceOptions.ts
Labels: enhancement, DB Migration

#773 My Minister adjustment
  app/subscriber/src/features/my-minister/MyMinister.tsx
  libs/net/dal/Services/ContentService.cs
Labels: bug

#775 TNO-1286: Format time w/ 2 digits
  app/subscriber/src/features/content/view-content/ViewContent.tsx
  app/subscriber/src/features/content/view-content/utils/formatTime.ts
  app/subscriber/src/features/content/view-content/utils/index.ts
Labels: bug, subscriber

#772 TNO-1290: Display tags on subscriber site
  app/subscriber/src/components/form/tags/Tags.tsx
  app/subscriber/src/features/content/view-content/ViewContent.tsx
  app/subscriber/src/features/content/view-content/ViewContentToolbar.tsx
Labels: subscriber

#779 fix: missed creation of oracle .env
  tools/scripts/gen-env-files.sh
  tools/scripts/variables.sh
Labels: bug

#776 TNO-1317: CP News content not appearing
  app/subscriber/src/features/content/view-content/ViewContent.tsx
Labels: bug, subscriber

#780 Fix TNO-1291
  services/net/notification/NotificationManager.cs
Labels: bug

#777 TNO-1279: A/V Content not displaying
  libs/net/models/Areas/Subscriber/Models/Content/ContentModel.cs
  libs/net/models/Areas/Subscriber/Models/Content/FileReferenceModel.cs
Labels: bug, subscriber

#781 Tweak for my-minister
  libs/net/dal/Services/ContentService.cs
Labels: bug, subscriber
