Repository bcgov/tno, pull requests merged in 2024-11, with the labels that each got.

#2319 Config sticky sessions
  network/reverse-proxy/editor/Dockerfile
  network/reverse-proxy/editor/config/default.conf
  network/reverse-proxy/editor/nginx.conf
  network/reverse-proxy/subscriber/Dockerfile
  network/reverse-proxy/subscriber/config/default.conf
  network/reverse-proxy/subscriber/nginx.conf
  openshift/kustomize/api/base/route-editor.yaml
  openshift/kustomize/api/base/route-subscriber.yaml
  openshift/kustomize/app/editor/base/route.yaml
  openshift/kustomize/app/subscriber/base/route.yaml
Labels: devops

#2320 Fix advanced search
  app/subscriber/src/features/search-page/SearchPage.tsx
Labels: bug, subscriber

#2321 Fix advanced search
  app/subscriber/src/features/search-page/PreviousResults.tsx
  app/subscriber/src/features/search-page/SearchPage.tsx
  app/subscriber/src/features/search-page/interfaces/IPreviousDate.ts
Labels: bug, subscriber

#2322 Rollback add to report
  app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
Labels: bug, subscriber

#2323 Tno 3027 commentary box headline
  app/subscriber/src/features/commentary/styled/Commentary.tsx
  app/subscriber/src/features/landing/styled/Landing.tsx
Labels: subscriber

#2325 Update transcript logging
  services/net/transcription/TranscriptionManager.cs
Labels: enhancement

#2327 update Env file
  tools/scripts/gen-env-files.sh
Labels: bug

#2328 Fix tab navigation
  app/editor/src/features/content/form/ContentNavigation.tsx
  app/editor/src/features/content/list-view/ContentListView.tsx
  app/editor/src/features/content/papers/Papers.tsx
  app/editor/src/store/hooks/editor/usehooks-ts/useLocalStorage.ts
  app/subscriber/src/features/search-page/SearchPage.tsx
  tools/mov-converter/README.md
Labels: bug, editor

#2331 Add date navigation
  app/subscriber/src/components/date-filter/DateFilter.tsx
  app/subscriber/src/features/daily-overview/AVOverviewPreview.tsx
  app/subscriber/src/features/event-of-the-day/EventOfTheDayPreview.tsx
  app/subscriber/src/features/filter-media/FilterMedia.tsx
  app/subscriber/src/features/home/Home.tsx
  app/subscriber/src/features/my-minister/MyMinister.tsx
  app/subscriber/src/features/router/AppRouter.tsx
  app/subscriber/src/features/search-page/SearchPage.tsx
  app/subscriber/src/features/todays-commentary/TodaysCommentary.tsx
  app/subscriber/src/features/todays-front-pages/TodaysFrontPages.tsx
  app/subscriber/src/features/top-stories/TopStories.tsx
Labels: enhancement, subscriber

#2333 MMI-3071 Improve import data
  api/net/Areas/Editor/Controllers/SettingController.cs
  api/net/Areas/Services/Controllers/IngestController.cs
  api/net/Areas/Services/Controllers/SettingController.cs
  api/net/Areas/Services/Controllers/SourceController.cs
  libs/net/core/Http/HttpRequestClient.cs
  libs/net/core/Http/IHttpRequestClient.cs
  libs/net/core/Http/OpenIdConnectRequestClient.cs
  libs/net/css/CssClient.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Helpers/IApiService.cs
  services/net/content/ContentManager.cs
  services/net/content/ContentService.cs
Labels: enhancement

#2334 Add CRON job to restart pods
  openshift/kustomize/cron/restart/base/cron-job.yaml
  openshift/kustomize/cron/restart/base/kustomization.yaml
  openshift/kustomize/cron/restart/overlays/dev/kustomization.yaml
  openshift/kustomize/cron/restart/overlays/prod/kustomization.yaml
  openshift/kustomize/cron/restart/overlays/test/kustomization.yaml
  openshift/kustomize/services/reporting/base/config-map.yaml
  openshift/kustomize/services/reporting/base/deploy.yaml
Labels: devops

#2338 Enable local nuget packages
  NuGet.Config
  libs/net/ches/TNO.Ches.csproj
  libs/net/core/TNO.Core.csproj
  libs/net/dal/TNO.DAL.csproj
  libs/net/elastic/TNO.Elastic.csproj
  libs/net/entities/TNO.Entities.csproj
  libs/net/kafka/TNO.Kafka.csproj
  libs/net/models/TNO.Models.csproj
  libs/net/packages/TNO.Ches.1.0.0.nupkg
  libs/net/packages/TNO.Core.1.0.0.nupkg
  libs/net/packages/TNO.DAL.1.0.0.nupkg
  libs/net/packages/TNO.Elastic.1.0.0.nupkg
  libs/net/packages/TNO.Entities.1.0.0.nupkg
  libs/net/packages/TNO.Kafka.1.0.0.nupkg
  libs/net/packages/TNO.Models.1.0.0.nupkg
  libs/net/packages/TNO.Services.1.0.0.nupkg
  libs/net/services/TNO.Services.csproj
  services/net/contentmigration/TNO.Services.ContentMigration.csproj
  services/net/nlp/TNO.Services.NLP.csproj
  tools/import/etl/TNO.Tools.Import.ETL.csproj
  tools/import/source/TNO.Tools.Import.Source.csproj
Labels: bug

#2339 Add local nuget to docker
  services/net/contentmigration/Dockerfile
  services/net/contentmigration/NuGet.Config
  services/net/nlp/Dockerfile
  services/net/nlp/NuGet.Config
Labels: bug

#2340 Fix oracle reference
  services/net/contentmigration/Dockerfile
  services/net/contentmigration/TNO.Services.ContentMigration.csproj
  services/net/nlp/Dockerfile
Labels: bug

#2341 Fix select content
  app/subscriber/src/components/content-list/ContentList.tsx
  openshift/kustomize/api/base/statefulset.yaml
Labels: bug, subscriber

#2342 Fix select content
  app/subscriber/src/components/content-list/ContentList.tsx
  app/subscriber/src/components/tool-bar/ContentActionBar.tsx
  app/subscriber/src/components/tool-bar/styled/ContentActionBar.tsx
  app/subscriber/src/features/manage-folder/ManageFolder.tsx
  app/subscriber/src/features/my-minister/MyMinister.tsx
  app/subscriber/src/features/press-gallery/PressGallery.tsx
  app/subscriber/src/features/search-page/SearchPage.tsx
  app/subscriber/src/features/search-page/styled/SearchPage.tsx
  app/subscriber/src/features/search-page/utils/filterFormat.ts
  app/subscriber/src/features/top-stories/TopStories.tsx
  app/subscriber/src/store/slices/profile/interfaces/IProfileState.ts
  app/subscriber/src/store/slices/profile/profileSlice.ts
  app/subscriber/src/store/slices/profile/useProfileStore.ts
Labels: bug, enhancement, subscriber

#2345 Update indexing process
  api/net/Areas/Kafka/Controllers/ProducerController.cs
  api/net/Config/KafkaOptions.cs
  api/net/appsettings.json
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Helpers/IApiService.cs
  openshift/kustomize/services/folder-collection/base/config-map.yaml
  services/net/folder-collection/FolderCollectionManager.cs
  services/net/folder-collection/appsettings.json
  services/net/indexing/IndexingManager.cs
Labels: bug

#2347 MMI 1815 option omit BCupdates
  app/editor/src/features/admin/reports/components/ReportContentOptions.tsx
  app/subscriber/src/features/my-reports/edit/settings/ReportEditPreferencesForm.tsx
  libs/net/dal/Extensions/JsonDocumentExtensions.cs
  libs/net/dal/Services/ReportService.cs
  libs/net/models/Settings/ReportContentSettingsModel.cs
  libs/net/models/Settings/ReportSettingsModel.cs
Labels: enhancement

#2350 Downgrade elastic lib
  services/net/indexing/TNO.Services.Indexing.csproj
Labels: bug

#2349 Fix image URL
  app/editor/src/features/home/LogoPanel.tsx
  app/subscriber/src/components/content-list/ContentReportPin.tsx
  app/subscriber/src/components/content-list/ContentRow.tsx
  app/subscriber/src/components/header/Header.tsx
  app/subscriber/src/features/content/view-content/ViewContent.tsx
  app/subscriber/src/features/help/Help.tsx
  app/subscriber/src/features/my-reports/components/ReportContentInlineText.tsx
  app/subscriber/src/features/my-reports/edit/content/stories/ToneSelector.tsx
  libs/npm/core/src/components/form/iconbutton/IconButton.tsx
  libs/npm/core/src/components/header/Header.tsx
Labels: bug

#2351 Fix highlight keywords
  libs/net/elastic/Extensions/StringExtensions.cs
Labels: bug

#2353 Fix highlight keywords
  libs/net/elastic/Extensions/StringExtensions.cs
  libs/net/template/ReportExtensions.cs
Labels: bug
