Repository bcgov/tno, pull requests merged in 2024-12, with the labels that each got.

#2356 TNO-3017 auto complete search field
  app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
  app/subscriber/src/components/tool-bar/styled/AddToMenu.tsx
Labels: subscriber

#2361 Hide CBRA unqualified
  app/editor/src/features/content/form/ContentForm.tsx
Labels: editor

#2364 Fix message alignment
  app/subscriber/src/features/login/styled/SystemMessage.tsx
Labels: bug

#2363 TNO-3017 auto complete search field
  app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
  app/subscriber/src/components/tool-bar/styled/AddToMenu.tsx
Labels: subscriber

#2366 fix: handle case when file not found and not synced to S3
  api/net/Areas/Editor/Controllers/StorageController.cs
Labels: bug

#2365 MMI-3118 updated running time
  api/net/Areas/Editor/Controllers/StorageController.cs
  libs/net/core/Storage/IS3StorageService.cs
  libs/net/core/Storage/S3StorageService.cs
  libs/net/dal/Helpers/FfmpegHelper.cs
Labels: enhancement

#2369 update running time in the endpoint
  api/net/Areas/Editor/Controllers/ContentController.cs
Labels: enhancement

#2372 Fix chart options
  libs/net/template/Models/Charts/Options/ChartOptionsModel.cs
  libs/net/template/Models/Charts/Options/ChartOptionsPluginModel.cs
Labels: bug

#2373 Fix chart labels
  libs/net/template/ReportEngine.cs
Labels: bug

#2374 Fix chart labels
  api/node/src/utils/applyChartJsOptions.ts
  api/node/src/utils/data.ts
  app/editor/src/features/admin/charts/ChartTemplateForm.tsx
  app/editor/src/features/admin/charts/components/ChartTemplatePreviewConfig.tsx
  app/editor/src/features/admin/charts/constants/chartTemplateColumns.tsx
  app/editor/src/features/admin/charts/constants/defaultChartJSOptions.ts
  app/editor/src/features/admin/charts/styled/ChartList.tsx
  app/editor/src/features/admin/notifications/styled/NotificationList.tsx
  app/editor/src/features/admin/products/styled/ProductList.tsx
  app/editor/src/features/admin/reports/styled/ReportAdmin.tsx
  app/editor/src/features/admin/reports/styled/ReportList.tsx
  libs/npm/core/src/hooks/api/utils/mergeChartSettings.ts
Labels: bug
