Repository bcgov/tno, pull requests merged in 2024-10, with the labels that each got.

#2303 Report fix - use prod tempalte
  app/editor/src/features/admin/report-templates/templates/body/CustomReport.cshtml
  libs/net/dal/Migrations/1.3.5/Up/PostUp/00-ReportTemplate.sql
Labels: enhancement, DB Migration

#2308 TNO-2808 Alert for transcription fail
  services/net/transcription/Exceptions.cs
  services/net/transcription/TranscriptionManager.cs
Labels: enhancement

#2311 Update pipeline tooling
  openshift/kustomize/tekton/base/tasks/git-conditions.yaml
  tools/git/DeploymentConfig.yaml
  tools/git/Dockerfile
  tools/git/README.md
  tools/git/entrypoint.sh
Labels: devops

#2309 TNO-3017 auto complete search field
  app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
Labels: subscriber

#2313 MMI-3095 cleanup junk upload files and prevent stream old file in editor
  api/net/Areas/Editor/Controllers/ContentController.cs
  app/editor/src/features/content/form/hooks/useContentForm.ts
  libs/net/dal/Services/FileReferenceService.cs
  libs/net/dal/Services/Interfaces/IFileReferenceService.cs
Labels: bug, enhancement, editor

#2317 Fix reporting service
  libs/net/ches/ChesService.cs
  openshift/kustomize/tekton/base/triggers/template.yaml
Labels: bug

#2318 MMI 3061 service to move s3 file, locally implement.
  TNO.sln
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Helpers/IApiService.cs
  services/docker-compose.yml
  services/net/fileupload/Dockerfile
  services/net/fileupload/FileUploadManager.cs
  services/net/fileupload/FileUploadService .cs
  services/net/fileupload/Program.cs
  services/net/fileupload/TNO.Services.FileUpload.csproj
  services/net/fileupload/appsettings.Development.json
  services/net/fileupload/appsettings.Staging.json
  services/net/fileupload/appsettings.json
  services/net/fileupload/config/FileUploadOptions.cs
Labels: enhancement
