Repository bcgov/tno, pull requests merged in 2025-01, with the labels that each got.

#2379 Replace CrunchyDB
  db/postgres/docker/Dockerfile.prod
  openshift/kustomize/api-services/base/deploy.yaml
  openshift/kustomize/api/base/deploy.yaml
  openshift/kustomize/api/base/statefulset.yaml
  openshift/kustomize/elastic/base/statefulset.yaml
  openshift/kustomize/kafka/broker/base/statefulset.yaml
  openshift/kustomize/postgres/crunchy/README.md
  openshift/kustomize/postgres/crunchy/base/deploy.yaml
  openshift/kustomize/postgres/crunchy/base/upgrade.yaml
  openshift/kustomize/postgres/crunchy/overlays/prod/kustomization.yaml
  openshift/kustomize/postgres/standalone/README.md
  openshift/kustomize/postgres/standalone/base/kustomization.yaml
  openshift/kustomize/postgres/standalone/base/service.yaml
  openshift/kustomize/postgres/standalone/base/statefulset.yaml
  openshift/kustomize/postgres/standalone/overlays/dev/kustomization.yaml
  openshift/kustomize/postgres/standalone/overlays/prod/kustomization.yaml
  openshift/kustomize/postgres/standalone/overlays/test/kustomization.yaml
  openshift/kustomize/services/content-historic/base/deploy.yaml
  openshift/kustomize/services/content/base/deploy.yaml
  openshift/kustomize/services/indexing/base/deploy.yaml
  openshift/kustomize/services/notification/base/deploy.yaml
  openshift/kustomize/services/reporting/base/deploy.yaml
  openshift/kustomize/services/transcription/base/deploy.yaml
  openshift/kustomize/shared_resources/overlays/dev/kustomization.yaml
  openshift/kustomize/shared_resources/overlays/prod/kustomization.yaml
  openshift/kustomize/shared_resources/overlays/test/kustomization.yaml
Labels: devops

#2380 MMI-3074 changes in the Prep Time Log modal
  app/editor/src/features/content/form/components/time-log/TimeLogSection.tsx
Labels: bug, editor

#2381 Fix db-connect script
  openshift/scripts/database-connect.sh
Labels: bug, devops

#2384 Fix Paper Ingest Service
  services/net/filemonitor/FilemonitorAction.cs
Labels: bug

#2386 Update DB template
  openshift/kustomize/postgres/standalone/base/statefulset.yaml
Labels: devops

#2388 Fix report issues
  api/node/src/utils/applyChartJsOptions.ts
  app/subscriber/src/features/my-reports/edit/ReportEditForm.tsx
  app/subscriber/src/features/my-reports/edit/settings/template/utils/getDatasets.ts
  app/subscriber/src/features/my-reports/edit/settings/template/utils/groupData.ts
Labels: bug, subscriber

#2390 Fix charts
  api/node/src/utils/applyChartJsOptions.ts
Labels: bug

#2389 MMI-3111 fix Enhance Summary method
  libs/net/template/ReportExtensions.cs
Labels: bug

#2392 Fix chart sorting date issue
  app/subscriber/src/features/my-reports/edit/settings/template/utils/groupData.ts
  libs/net/template/ReportExtensions.cs
Labels: bug, subscriber

#2394 MMI-3167 Added Video link to Help page
  app/subscriber/src/features/help/Help.tsx
Labels: subscriber

#2397 MMI-3105 Add unique key and default value for media type select in ContentForm
  app/editor/src/features/content/form/ContentForm.tsx
Labels: bug, editor
