Repository bcgov/tno, pull requests merged in 2025-02, with the labels that each got.

#2398 Update CHES library
  libs/net/ches/ChesService.cs
  libs/net/ches/Configuration/ChesOptions.cs
  libs/net/ches/Exceptions/ChesException.cs
  libs/net/ches/Models/AttachmentModel.cs
  libs/net/ches/Models/EmailContextModel.cs
  libs/net/ches/Models/EmailMergeModel.cs
  libs/net/ches/Models/EmailModel.cs
  libs/net/ches/Models/ErrorModel.cs
  libs/net/ches/Models/ErrorResponseModel.cs
  libs/net/ches/Models/IEmail.cs
  libs/net/ches/Models/MessageResponseModel.cs
  libs/net/ches/Models/StatusHistoryResponseModel.cs
  libs/net/ches/Models/StatusModel.cs
  libs/net/ches/Models/StatusResponseModel.cs
  libs/net/ches/TNO.Ches.csproj
  libs/net/core/Extensions/EnumExtensions.cs
  openshift/kustomize/services/notification/base/config-map.yaml
  openshift/kustomize/services/notification/base/deploy.yaml
  openshift/kustomize/services/reporting/base/config-map.yaml
  openshift/kustomize/services/reporting/base/deploy.yaml
Labels: enhancement

#2399 MMI-3113 featured story filter not showing other source for online media
  app/subscriber/src/components/media-type-filters/FilterOptions.tsx
  app/subscriber/src/features/home/constants/HomeFilterType.ts
Labels: bug, subscriber

#2404 MMI-3100 image tag email alert, migration 1.3.19
  app/editor/src/features/admin/notifications/constants/defaultRazorTemplate.ts
  libs/net/dal/Migrations/1.3.19/Up/PostUp/00-Notification_Template.sql
  libs/net/dal/Migrations/20250212193616_1.3.19.Designer.cs
  libs/net/dal/Migrations/20250212193616_1.3.19.cs
Labels: DB Migration, editor

#2391 MMI-3063 better UX for concurrency errors
  api/net/Middleware/ErrorHandlingMiddleware.cs
  app/editor/src/store/hooks/app/useToastError.tsx
  libs/net/core/Exceptions/ContentConflictException.cs
  libs/net/core/Extensions/ExceptionExtensions.cs
  libs/net/dal/Services/ContentService.cs
Labels: enhancement

#2409 Fix accumulate reports
  api/net/Areas/Services/Controllers/ReportController.cs
  app/subscriber/src/features/my-reports/edit/view/ReportHistoryForm.tsx
  libs/net/dal/Services/ReportInstanceService.cs
  libs/net/dal/Services/ReportService.cs
  libs/net/services/Helpers/ApiService.cs
  libs/net/services/Helpers/IApiService.cs
  services/net/reporting/ReportingManager.cs
Labels: bug
