Repository bcgov/tno, pull requests merged in 2025-06, with the labels that each got.

#2450 MMI-3247 Enhance highlight keywords
  app/subscriber/src/components/content-list/ContentRow.tsx
  app/subscriber/src/components/content-list/utils/highlightTerms.tsx
  app/subscriber/src/features/search-page/utils/formatSearch.ts
Labels: enhancement, subscriber

#2451 Mmi 3232 s3 downloader
  .gitignore
  tools/s3-downloader/.env.example
  tools/s3-downloader/.gitignore
  tools/s3-downloader/.python-version
  tools/s3-downloader/Makefile
  tools/s3-downloader/README.md
  tools/s3-downloader/build.py
  tools/s3-downloader/main.py
  tools/s3-downloader/pyproject.toml
  tools/s3-downloader/s3_downloader.spec
  tools/s3-downloader/src/UI/__init__.py
  tools/s3-downloader/src/UI/app.py
  tools/s3-downloader/src/UI/components/__init__.py
  tools/s3-downloader/src/UI/components/buttons_panel.py
  tools/s3-downloader/src/UI/components/file_details_dialog.py
  tools/s3-downloader/src/UI/components/history_widget.py
  tools/s3-downloader/src/UI/components/log_widget.py
  tools/s3-downloader/src/UI/components/numeric_table_widget_item.py
  tools/s3-downloader/src/UI/components/schedule_info_widget.py
  tools/s3-downloader/src/UI/components/storage_info_widget.py
  tools/s3-downloader/src/UI/components/storage_path_widget.py
  tools/s3-downloader/src/UI/controllers/__init__.py
  tools/s3-downloader/src/UI/controllers/download_controller.py
  tools/s3-downloader/src/UI/controllers/scheduler.py
  tools/s3-downloader/src/UI/controllers/settings_controller.py
  tools/s3-downloader/src/UI/main_window.py
  tools/s3-downloader/src/UI/s3_controller.py
  tools/s3-downloader/src/__init__.py
  tools/s3-downloader/src/client/__init__.py
  tools/s3-downloader/src/client/s3_client.py
  tools/s3-downloader/src/database/__init__.py
  tools/s3-downloader/src/database/models.py
  tools/s3-downloader/src/settings/__init__.py
  tools/s3-downloader/src/settings/default_settings.py
  tools/s3-downloader/src/settings/settings_loader.py
  tools/s3-downloader/uv.lock
Labels: enhancement

#2456 Fix syndication service
  libs/net/models/Areas/Services/Models/Ingest/SourceModel.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#2457 Optimize the tag parsing for Tag
  app/editor/src/features/content/form/components/tags/utils/tagParsing.ts
Labels: enhancement

#2463 MMI-3265 Fix Syndication service
  services/net/syndication/SyndicationAction.cs
Labels: bug
