Repository bcgov/tno, pull requests merged in 2025-10, with the labels that each got.

#2494 Mmi 3243 update
  api/net/Areas/Subscriber/Controllers/ReportController.cs
  app/editor/package.json
  app/subscriber/package.json
  app/subscriber/src/components/tool-bar/AddToReportMenu.tsx
  app/subscriber/src/components/tool-bar/utils/toInstanceContent.ts
  app/subscriber/src/features/my-reports/ReportPreview.tsx
  app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx
  app/subscriber/src/features/my-reports/edit/content/stories/ContentForm.tsx
  app/subscriber/src/features/my-reports/edit/content/stories/UserContentForm.tsx
  app/subscriber/src/store/hooks/subscriber/interfaces/IReportContentMutationModel.ts
  app/subscriber/src/store/hooks/subscriber/interfaces/index.ts
  app/subscriber/src/store/hooks/subscriber/useReports.ts
  app/subscriber/src/store/hooks/subscriber/utils/reportContentMutationHelpers.ts
  libs/net/dal/Models/ReportContentMutation.cs
  libs/net/dal/Services/Interfaces/IReportInstanceService.cs
  libs/net/dal/Services/Interfaces/IReportService.cs
  libs/net/dal/Services/ReportInstanceService.cs
  libs/net/dal/Services/ReportService.cs
  libs/net/models/Areas/Subscriber/Models/Report/ReportContentMutationModel.cs
  libs/npm/core/package.json
  libs/npm/core/src/hooks/api/interfaces/IReportContentMutationModel.ts
  libs/npm/core/src/hooks/api/interfaces/index.ts
  libs/npm/core/src/hooks/api/subscriber/useApiSubscriberReports.ts
Labels: enhancement, subscriber

#2501 Add PROD test env
  openshift/kustomize/prod-test/api-deploy.yaml
  openshift/kustomize/prod-test/api-routes.yaml
  openshift/kustomize/prod-test/api-service.yaml
  openshift/kustomize/prod-test/deployments/api-deploy.yaml
  openshift/kustomize/prod-test/editor-deploy.yaml
  openshift/kustomize/prod-test/editor-route.yaml
  openshift/kustomize/prod-test/editor-service.yaml
  openshift/kustomize/prod-test/subscriber-deploy.yaml
  openshift/kustomize/prod-test/subscriber-route.yaml
  openshift/kustomize/prod-test/subscriber-service.yaml
Labels: devops

#2498 Update Paper Ingest
  libs/net/services/Actions/Managers/ServiceActionManager`.cs
  libs/net/services/Config/ServiceOptions.cs
  libs/net/services/Logging/CustomLevelEnricher.cs
  libs/net/services/Logging/ExceptionEnricher.cs
  libs/net/services/Logging/MessageEnricher.cs
  libs/net/services/Managers/IngestManager`.cs
  libs/net/services/Runners/BaseService.cs
  libs/net/services/TNO.Services.csproj
  services/net/ches-retry/appsettings.json
  services/net/content/appsettings.json
  services/net/contentmigration/appsettings.json
  services/net/event-handler/appsettings.json
  services/net/extract-quotes/appsettings.json
  services/net/ffmpeg/appsettings.json
  services/net/filemonitor/FilemonitorAction.cs
  services/net/filemonitor/appsettings.json
  services/net/fileupload/appsettings.json
  services/net/folder-collection/appsettings.json
  services/net/image/appsettings.json
  services/net/indexing/appsettings.json
  services/net/nlp/appsettings.json
  services/net/notification/appsettings.json
  services/net/reporting/appsettings.json
  services/net/scheduler/appsettings.json
  services/net/syndication/appsettings.json
  services/net/transcription/appsettings.json
Labels: enhancement

#2503 MMI-3356 Fix media analytics
  libs/net/template/ReportExtensions.cs
Labels: bug

#2504 fix the adding content to report instance id bug
  app/editor/package.json
  app/subscriber/package.json
  app/subscriber/src/features/my-reports/edit/content/stories/UserContentForm.tsx
  libs/net/dal/Services/ReportService.cs
  libs/npm/core/package.json
  libs/npm/core/src/components/sentiment/SentimentPicker.tsx
Labels: bug, subscriber
