Repository bcgov/tno, pull requests merged in 2025-07, with the labels that each got.

#2467 MMI-3273 Fix Merge Show/Program
  app/editor/src/features/admin/series/SeriesList.tsx
  app/editor/src/features/admin/series/SeriesMerge.tsx
Labels: bug, editor

#2468 MMI-3261 Elasticsearch cloud
  openshift/kustomize/services/indexing/base/config-map.yaml
  openshift/kustomize/services/indexing/base/deploy.yaml
  openshift/kustomize/services/indexing/overlays/cloud-test/kustomization.yaml
  services/net/indexing/Config/IndexingOptions.cs
  services/net/indexing/IndexingManager.cs
  services/net/indexing/IndexingService.cs
  services/net/indexing/appsettings.Development.json
  services/net/indexing/appsettings.Staging.json
  services/net/indexing/appsettings.json
Labels: enhancement, devops

#2466 MMI-2918 Advanced search updates
  app/subscriber/src/features/search-page/SearchPage.tsx
  app/subscriber/src/features/search-page/components/advanced-search/AdvancedSearch.tsx
  app/subscriber/src/features/search-page/components/advanced-search/styled/AdvancedSearch.tsx
  libs/net/dal/Services/ContentService.cs
Labels: editor

#2474 MMI-3276 Allow images in Notifications
  api/net/Areas/Editor/Controllers/StorageController.cs
  api/net/Areas/Subscriber/Controllers/ContentController.cs
  api/net/appsettings.json
  app/editor/src/features/admin/notifications/constants/defaultRazorTemplate.ts
  libs/net/core/Extensions/StringExtensions.cs
  libs/net/dal/Config/StorageOptions.cs
  libs/net/template/Models/BaseTemplateModel.cs
  openshift/kustomize/services/notification/base/deploy.yaml
  services/docker-compose.yml
  services/net/notification/Config/NotificationOptions.cs
  services/net/notification/NotificationManager.cs
  services/net/notification/appsettings.json
  tools/scripts/gen-env-files.sh
Labels: enhancement

#2475 MMI-3277 Add Image Summary to Notification
  libs/net/dal/Migrations/1.3.31/Up/PostUp/00-Notification_Template.sql
  libs/net/dal/Migrations/20250726181358_1.3.31.Designer.cs
  libs/net/dal/Migrations/20250726181358_1.3.31.cs
Labels: enhancement, DB Migration

#2476 Fix pipeline
  openshift/kustomize/api/base/config-map.yaml
  openshift/kustomize/elastic/base/secret.yaml
  openshift/kustomize/tekton/base/tasks/build-all.yaml
  openshift/kustomize/tekton/base/tasks/deploy-all.yaml
  openshift/scripts/deploy.sh
  openshift/scripts/stop.sh
  openshift/scripts/up.sh
Labels: devops

#2478 Fix Indexer
  libs/net/dal/Services/ContentService.cs
  libs/net/models/Filters/ContentFilter.cs
  tools/indexer/IndexerManager.cs
Labels: enhancement
