Repository bcgov/tno, pull requests merged in 2025-04, with the labels that each got.

#2436 MMI-3185 Published on behaviour
  app/editor/src/features/content/form/hooks/useContentForm.ts
Labels: bug, editor

#2437 MMI 3200 UI
  app/editor/src/features/content/form/ContentForm.tsx
  app/editor/src/features/content/form/ContentStoryForm.tsx
  app/editor/src/features/content/form/components/tags/Tags.tsx
  app/editor/src/features/content/form/components/tags/TagsContext.tsx
  app/editor/src/features/content/form/components/tags/hooks/useTagManagement.ts
  app/editor/src/features/content/form/components/tags/index.ts
  app/editor/src/features/content/form/components/tags/types.ts
  app/editor/src/features/content/form/components/tags/utils/tagParsing.ts
  app/editor/src/features/content/form/utils/getTargetField.ts
  app/editor/src/features/content/form/utils/index.ts
Labels: enhancement

#2439 Fix pipeline
  openshift/kustomize/tekton/base/tasks/deploy-all.yaml
  openshift/kustomize/tekton/base/tasks/git-conditions.yaml
Labels: bug, devops
