Repository bcgov/tno, pull requests merged in 2025-03, with the labels that each got.

#2413 MMI-3172 change to make all options name to upper case for filtering
  app/subscriber/src/features/filter-media/FilterMediaLanding.tsx
Labels: bug, subscriber

#2414 Fix chart color
  app/subscriber/src/features/my-reports/edit/settings/template/charts/ConfigureDataset.tsx
  app/subscriber/src/features/my-reports/edit/settings/template/utils/getChartData.ts
  app/subscriber/src/features/my-reports/edit/settings/template/utils/groupData.ts
  app/subscriber/src/features/my-reports/edit/settings/template/utils/separateDatasets.ts
  libs/net/packages/TNO.Ches.2.0.1.nupkg
Labels: bug, subscriber

#2412 MMI-3042 Fix text
  services/net/filemonitor/FilemonitorAction.cs
  services/net/filemonitor/TNO.Services.FileMonitor.csproj
Labels: bug

#2415 Allow redirects
  libs/net/services/Runners/BaseService.cs
  services/net/syndication/SyndicationAction.cs
Labels: bug

#2417 Fix Ches Retry Service
  libs/net/dal/Services/ReportService.cs
  openshift/scripts/deploy.sh
  openshift/scripts/stop.sh
  openshift/scripts/up.sh
  services/net/ches-retry/ChesRetryManager.cs
Labels: bug

#2419 Auto restart
  libs/net/services/Config/ServiceOptions.cs
  libs/net/services/Managers/ServiceManager`.cs
  libs/net/services/Runners/BaseService.cs
  services/net/ches-retry/ChesRetryManager.cs
  services/net/reporting/ReportingManager.cs
Labels: enhancement

#2425 MMI-3212 Fix Scheduler Service
  services/net/scheduler/SchedulerManager.cs
Labels: bug

#2426 MMI-3212 Fix Scheduler Service Issue
  api/net/Areas/Services/Controllers/EventScheduleController.cs
  app/subscriber/src/components/layout/DefaultLayout.tsx
  app/subscriber/src/features/my-reports/MyReports.tsx
  app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx
  app/subscriber/src/store/hooks/subscriber/useReportSync.ts
  libs/net/dal/Services/ContentService.cs
  libs/net/reports/TNO.Reports.csproj
Labels: bug, subscriber

#2428 MMI-3213 Fix Ingest Services & Transcript Work Queue
  api/net/Areas/Editor/Controllers/WorkOrderController.cs
  libs/net/dal/Services/Interfaces/IWorkOrderService.cs
  libs/net/dal/Services/WorkOrderService.cs
  libs/net/models/Areas/Services/Models/Ingest/IngestModel.cs
Labels: bug

#2431 Fix report concurrency error
  api/net/Areas/Services/Controllers/EventScheduleController.cs
  api/net/Areas/Services/Controllers/ReportInstanceController.cs
  app/subscriber/src/features/my-reports/MyReports.tsx
  app/subscriber/src/features/my-reports/edit/ReportEditPage.tsx
  app/subscriber/src/store/hooks/subscriber/useReportSync.ts
Labels: bug

#2432 MMI-3214 Fix Transcription Queue
  libs/net/dal/Services/WorkOrderService.cs
Labels: bug, editor
